### ISSUE TITLE
sockets tests are flakey due to OS difference

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#2700]
I updated my machine to latest Ubuntu LTS, and now the sockets tests are flakey. I need to run some of them a few times before they pass. Here is an example failure:

````
$ ./tests/runner.py sockets.test_sockets_echo
[Browser harness server on process 16016]
test_sockets_echo (test_sockets.sockets) ... 
(process:16023): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
running websockify on 49160, forward to tcp 49159
WebSocket server settings:
  - Listen on :49160
  - Flash security policy server
  - SSL/TLS support
[Websockify on process [16032, 16033]]
  - proxying from :49160 to 127.0.0.1:49159

WARNING  root: -I or -L of an absolute path "-I/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/sockets" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
[browser launch: test.html ]
  1: 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
  1: 127.0.0.1: Version hybi-13, base64: 'False'
  1: connecting to: 127.0.0.1:49159

Traffic Legend:
    }  - Client receive
    }. - Client receive partial
    {  - Target receive

    >  - Target send
    >. - Target send partial
    <  - Client send
    <. - Client send partial

}>server: /media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/sockets/test_sockets_msg.h:16: int do_msg_read(int, msg_t *, int, int, struct sockaddr *, socklen_t *): Assertion `(*__errno_location ()) == 11' failed.
}>  1: handler exception: [Errno 107] Transport endpoint is not connected
  1: Traceback (most recent call last):
  File "/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/third_party/websockify/websockify/websocket.py", line 797, in top_new_client
    self.new_client()
  File "/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/third_party/websockify/websockify/websocketproxy.py", line 193, in new_client
    tsock.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected

  1: 127.0.0.1: exiting due to --run-once
  1: Closing socket listening at :49160
````

If I run it enough times it passes, though.

Any idea what could cause this? I know little about networking in general myself. @inolen @juj

**Comment by kripken** [comment]
This looks to have been fixed by #4160.
