### ISSUE TITLE
"_llvm_memcpy_... is not defined" when using fastcomp compiler

### ISSUE THREAD

**Issue by jlongster** [kripken/emscripten#2833]
I'm compiling libofx using Emscripten and it's going great. I found a bug with the fastcomp compiler though. The library parses SGML and when giving it some data to parse, it errors with this:

```
/Users/james/projects/budget/libofx.js:7628
    if (typeof e !== 'number' && e !== 'longjmp') throw e;
                                                        ^
ReferenceError: _llvm_memcpy_p0i8_p0i8_i32 is not defined
    at Array._llvm_memcpy_p0i8_p0i8_i32__wrapper [as 2108] (/Users/james/projects/budget/libofx.js:440806:117)
    at Object.dynCall_viiiii (/Users/james/projects/budget/libofx.js:440619:40)
    at invoke_viiiii (/Users/james/projects/budget/libofx.js:7563:29)
    at Array.__ZN18OfxStatusContainerD2Ev [as 71] (/Users/james/projects/budget/libofx.js:36442:6)
    at Object.dynCall_vi (/Users/james/projects/budget/libofx.js:440626:36)
    at invoke_vi (/Users/james/projects/budget/libofx.js:7572:25)
    at Array.__ZN18OfxStatusContainerD0Ev [as 72] (/Users/james/projects/budget/libofx.js:36343:2)
    at __ZN16OfxMainContainer13add_containerEP19OfxGenericContainer (/Users/james/projects/budget/libofx.js:27984:34)
```

It's not a bug on my part (I don't think) because if I compile everything with `EMCC_FAST_COMPILER=0` then it all works fine. I don't know what information you need for this, but you can grab a test case here: http://jlongster.com/s/fastcomp-bug.zip. Unzip and run `req.js` in node and you'll see the error.

I have a c++ file that is the interface between JS & libofx and I can give that too if needed, or the commands I used to compile everything.

**Comment by jlongster** [comment]
I cannot reproduce this on latest version of emscripten so the bug has been fixed at some point. Thanks!
