### ISSUE TITLE
Compiler assertion failure when building Bullet (ammo.js) with SSE support enabled.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3009]
Set up to build with the Emscripten branch https://github.com/juj/emscripten/tree/sse2 , then

    git clone https://github.com/juj/ammo.js.git
    cd ammo.js
    git checkout sse
    python make.py

Observed:

The build fails with 

    Linking CXX static library libBulletCollision.a
    [100%] Built target BulletCollision
    LLVM ERROR: I->getType() == I->getOperand(0)->getType()
    Stack dump:
    0.	Program arguments: C:/code/emsdk/clang/fastcomp/build_incoming_vs2010_64/bin/RelWithDebInfo\llc c:\users\jukka\appdata\local\temp\tmpcly5lc\temp.bc -march=js -filetype=asm -o c:\users\jukka\appdata\local\temp\tmp2mrtlm.4.js -O3 -emscripten-max-setjmps=20 
    1.	Running pass 'Expand and lower illegal >i32 operations into 32-bit chunks' on module 'c:\users\jukka\appdata\local\temp\tmpcly5lc\temp.bc'.
    Traceback (most recent call last):
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1655, in <module>
        _main(environ=os.environ)
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1643, in _main
        temp_files.run_and_clean(lambda: main(
      File "C:\code\emsdk\emscripten\incoming\tools\tempfiles.py", line 39, in run_and_clean
        return func()
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1651, in <lambda>
        DEBUG_CACHE=DEBUG_CACHE,
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1538, in main
        jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 805, in emscript_fast
        start_funcs = backend_output.index(start_funcs_marker)
    ValueError: substring not found
    Traceback (most recent call last):
      File "C:\code\emsdk\emscripten\incoming\emcc", line 1281, in <module>
        final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
      File "C:\code\emsdk\emscripten\incoming\tools\shared.py", line 1501, in emscripten
        assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
    AssertionError: Emscripten failed to generate .js

**Comment by juj** [comment]
Works in current incoming.
