### ISSUE TITLE
SDL 2 SDL_JoystickUpdate() breaks emterpreter compilation

### ISSUE THREAD

**Issue by dreamlayers** [kripken/emscripten#3141]
Use the following simple program:
```C
#include <SDL.h>
int main(void) {
    SDL_JoystickUpdate();
    return 0;
}
```
This is not proper use of SDL and not meant to be actually usable as a program. It just exists to pull in `SDL_JoystickUpdate()` and show the problem with emterpreter. I am using emcc 1.29.3 a1974e9. If I compile using `emcc -O3 -s USE_SDL=2 -s EMTERPRETIFY=1 -s 'EMTERPRETIFY_BLACKLIST=[ "_SDL_JoystickUpdate" ]' fail.c -o fail.js`, that works. However, if I remove that blacklist, and use `emcc -O3 -s USE_SDL=2 -s EMTERPRETIFY=1 fail.c -o fail.js` then compilation fails with:
```
Stack: Error
    at assertTrue (eval at globalEval (/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:111:8), <anonymous>:59:26)
    at getReg (/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:6371:13)
    at getReg (/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:6272:29)
    at /home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:7107:19
    at Array.forEach (native)
    at walkStatements (/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:7105:13)
    at getReg (/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:6530:59)
    at /home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:7107:19
    at Array.forEach (native)
    at walkStatements (/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js-optimizer.js:7105:13)

undefined:60
    throw msg;
          ^
Assertion failed: undefined
Traceback (most recent call last):
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/emterpretify.py", line 688, in <module>
    shared.Building.js_optimizer(infile, ['emterpretify'], extra_info={ 'emterpretedFuncs': list(emterpreted_funcs), 'externalEmterpretedFuncs': list(external_emterpreted_funcs), 'opcodes': OPCODES, 'ropcodes': ROPCODES, 'ASYNC': ASYNC, 'PROFILING': PROFILING }, output_filename=temp, just_concat=True)
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/shared.py", line 1637, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, jcache, debug, extra_info, just_split, just_concat)
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 553, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 553, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 459, in run_on_js
    filenames = [run_on_chunk(command) for command in commands]
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 247, in run_on_chunk
    assert proc.returncode == 0, 'Error in optimizer: ' + output
AssertionError: Error in optimizer: // return type: [_printf_core,0]
// EMTERPRET_INFO
```
After EMTERPRET_INFO I see JavaScript functions that would go into the output file and other stuff. I didn't paste that part here because it is very long.

**Comment by kripken** [comment]
Thanks, fixed.

**Comment by dreamlayers** [comment]
Thanks! DOSBox can now build and work with SDL 2 without `EMTERPRETIFY_BLACKLIST`. I am closing this issue now because it appears fixed and I don't want it cluttering the issue list.
