### ISSUE TITLE
EMSDK: installation fails when path contains UTF8 characters

### ISSUE THREAD

**Issue by lovasoa** [kripken/emscripten#3147]
Trying to install emsdk from a directory named `Téléchargements`, I got: 
```
olojkine@ophir-W54:~/Téléchargements/emsdk_portable$ ./emsdk install latest
Installing 'sdk-master-64bit'..
Installing 'clang-master-64bit'..
Traceback (most recent call last):
  File "./emsdk", line 1319, in <module>
    sys.exit(main())
  File "./emsdk", line 1304, in main
    tool.install()
  File "./emsdk", line 804, in install
    success = tool.install()
  File "./emsdk", line 812, in install
    success = build_fastcomp_tool(self)
  File "./emsdk", line 415, in build_fastcomp_tool
    fastcomp_root = tool.installation_path()
  File "./emsdk", line 637, in installation_path
    return sdk_path(pth)
  File "./emsdk", line 109, in sdk_path
    return to_unix_path(os.path.join(os.path.dirname(os.path.realpath(__file__)), path))
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```

I think this is because in  python 2 (contrarily to python3), strings are in ASCII by default.

**Comment by juj** [comment]
Thanks, I think this should be now fixed in the above commit.
