### ISSUE TITLE
native_optimizer crashes with commit 6eb8567a3cc7b2d1557f22617c52ce19f1a1c8fc

### ISSUE THREAD

**Issue by floooh** [kripken/emscripten#3149]
After updating incoming my Oryol engine demos crash in the native_optimizer stage, bisecting points to this commit:

```
6eb8567a3cc7b2d1557f22617c52ce19f1a1c8fc is the first bad commit
commit 6eb8567a3cc7b2d1557f22617c52ce19f1a1c8fc
Author: Alon Zakai <alonzakai@gmail.com>
Date:   Thu Jan 22 17:36:02 2015 -0800

    switch labeled one-time loops to labeled blocks, to reduce code size

:040000 040000 22f1720b5cb707859f7ca174cb13cb059596fa4c 22830bf915cf4163a26bce3b223d7496e6597881 M	tests
:040000 040000 0d2b203553452c8c8a9877242c14d2f07c727c0d 6e8c1e84896d9cf5811e84fa3221d179127f3c38 M	tools
```

The crash output is:
```
Linking CXX executable /Users/floh/projects/fips-deploy/oryol/emsc-make-release/Clear.html
Assertion failed: (isString()), function getIString, file /Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/optimizer/simple_ast.h, line 186.
Traceback (most recent call last):
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1536, in <module>
    flush_js_optimizer_queue()
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1445, in flush_js_optimizer_queue
    run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1416, in run_passes
    final = shared.Building.js_optimizer(final, passes, jcache, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/shared.py", line 1637, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, jcache, debug, extra_info, just_split, just_concat)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 552, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 552, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 453, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AssertionError: Error in optimizer:
make[3]: *** [/Users/floh/projects/fips-deploy/oryol/emsc-make-release/Clear.html] Error 1
make[2]: *** [code/Samples/Gfx/Clear/CMakeFiles/Clear.dir/all] Error 2
make[1]: *** [code/Samples/Gfx/Clear/CMakeFiles/Clear.dir/rule] Error 2
make: *** [Clear] Error 2
```

Running with EMCC_DEBUG doesn't seem to be that helpful. Building a trivial program (hello world) doesn't seem to trigger the bug. Let me know how I can help finding the problem (.bc files, build instructions, etc...)

Cheers,
-Floh

**Comment by floooh** [comment]
PS: maybe this part with EMCC_DEBUG is interesting because of the build parameters used:

```
DEBUG    root: emcc step "link" took 1.13 seconds
DEBUG    root: saving intermediate processing steps to /var/folders/t5/y4k268cs1fl4hsygfbrtjzl00000gn/T/emscripten_temp
DEBUG    root: emcc: LLVM opts: -strip-debug -disable-internalize -internalize -internalize-public-api-list=main,malloc,free,malloc,free -std-link-opts -disable-vectorize
DEBUG    root: emcc: LLVM opts: -pnacl-abi-simplify-preopt -pnacl-abi-simplify-postopt -disable-vectorize
DEBUG    root: emcc step "post-link" took 1.85 seconds
DEBUG    root: LLVM => JS
DEBUG    root: PYTHON not defined in ~/.emscripten, using "/usr/bin/python2"
DEBUG    root: JAVA not defined in ~/.emscripten, using "java"
DEBUG    root: not building relooper to js, using it in c++ backend
DEBUG    root: emscript: llvm backend: /Users/floh/projects/fips-sdks/osx/emsdk_portable/clang/fastcomp/build_incoming_64/bin/llc /var/folders/t5/y4k268cs1fl4hsygfbrtjzl00000gn/T/tmpHzfFKu/Clear.bc -march=js -filetype=asm -o /var/folders/t5/y4k268cs1fl4hsygfbrtjzl00000gn/T/emscripten_temp/tmpEivELR.4.js -O3 -emscripten-max-setjmps=20
DEBUG    root:   emscript: llvm backend took 0.292764902115 seconds
DEBUG    root: emscript: js compiler glue
DEBUG    root:   emscript: glue took 0.213292837143 seconds
DEBUG    root: asm text sizes[[2461194, 18744, 25], 3840, 314, 6696, 0, 3561, 28128, 1246, 234, 5427, 2496]
DEBUG    root:   emscript: final python processing took 0.0159378051758 seconds
DEBUG    root: emcc step "emscript (llvm=>js)" took 0.69 seconds
DEBUG    root: wrote memory initialization to /Users/floh/projects/fips-deploy/oryol/emsc-make-release/Clear.html.mem
DEBUG    root: emcc step "source transforms" took 0.11 seconds
DEBUG    root: running js post-opts
DEBUG    root: applying js optimization passes: ['asm', 'eliminate', 'simplifyExpressions', 'emitJSON']
chunkification: num funcs: 626 actual num chunks: 5 chunk size range: 522748 - 468385
DEBUG    root: js optimizer using native
splitting up js optimization into 5 chunks, using 4 cores  (total: 2.37 MB)
.
.
.
.
.
DEBUG    root: applying js optimization passes: ['asm', 'receiveJSON', 'outline', 'emitJSON']
chunkification: num funcs: 7 actual num chunks: 5 chunk size range: 1393800 - 1011691
splitting up js optimization into 5 chunks, using 4 cores  (total: 5.64 MB)
.
.
.
.
.
DEBUG    root: applying js optimization passes: ['asm', 'receiveJSON', 'registerizeHarder', 'minifyNames', 'cleanup', 'asmLastOpts', 'last', 'minifyWhitespace']
chunkification: num funcs: 7 actual num chunks: 5 chunk size range: 1228143 - 891356
DEBUG    root: js optimizer using native
splitting up js optimization into 5 chunks, using 4 cores  (total: 5.04 MB)
.
.
.
.
Assertion failed: (isString()), function getIString, file /Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/optimizer/simple_ast.h, line 186.
Traceback (most recent call last):
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1536, in <module>
    flush_js_optimizer_queue()
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1445, in flush_js_optimizer_queue
    run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1416, in run_passes
    final = shared.Building.js_optimizer(final, passes, jcache, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/shared.py", line 1637, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, jcache, debug, extra_info, just_split, just_concat)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 552, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 552, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 453, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
```

**Comment by kripken** [comment]
Should be fixed, please verify.

**Comment by kripken** [comment]
(The reason I didn't notice this more quickly is because it only fails when outlining is enabled.)

**Comment by floooh** [comment]
Ah, that's (not using outlining) probably was the reason why my simple hello-world-tests worked too. Everything is working now again, thanks!

**Comment by kripken** [comment]
Great!
