### ISSUE TITLE
missing function

### ISSUE THREAD

**Issue by alexey-sh** [kripken/emscripten#3182]
Hi.

I want to convert this [c++](http://download.yandex.ru/api-fotki/c-yamrsa.tar.gz) code to js.
I tried(os x 10.9.0):
```
alexey$ ./emcc -v
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.29.0
clang version 3.4 
Target: x86_64-apple-darwin13.0.0
Thread model: posix
INFO     root: (Emscripten: Running sanity checks)

alexey$ clang -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix

alexey$ ./emcc /Users/alexey/yandex_encrypter/encrypt.cpp 
warning: unresolved symbol: _ZN18CCryptoProviderRSAD1Ev
warning: unresolved symbol: _ZN18CCryptoProviderRSA7EncryptEPKcjPcRj
warning: unresolved symbol: _ZN18CCryptoProviderRSAC1Ev
warning: unresolved symbol: _ZN18CCryptoProviderRSA15ImportPublicKeyEPKc
warning: unresolved symbol: _Z13base64_encodePKhj

alexey$ node a.out.js a a
missing function: _ZN18CCryptoProviderRSAC1Ev
-1
-1
warning: a problem occurred in builtin C++ name demangling; build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling

/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:84
      throw ex;
            ^
abort() at Error
    at jsStackTrace (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:987:13)
    at stackTrace (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:1004:22)
    at abort (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:68910:25)
    at __ZN18CCryptoProviderRSAC1Ev [CCryptoProviderRSA::CCryptoProviderRSA()] (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:5427:72)
    at Array.__ZN18CCryptoProviderRSAC1Ev__wrapper [CCryptoProviderRSA::CCryptoProviderRSA?_()] [as 352] (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:66545:67)
    at Object.dynCall_vi (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:66391:33)
    at invoke_vi (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:7004:25)
    at _main (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:7515:4)
    at Object.asm._main (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:66995:19)
    at Object.callMain (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:68786:30)

alexey$ rm a.out.js 

alexey$ ./emcc -s DEMANGLE_SUPPORT=1 /Users/alexey/yandex_encrypter/encrypt.cpp 
warning: unresolved symbol: _ZN18CCryptoProviderRSAD1Ev
warning: unresolved symbol: _ZN18CCryptoProviderRSA7EncryptEPKcjPcRj
warning: unresolved symbol: _ZN18CCryptoProviderRSAC1Ev
warning: unresolved symbol: _ZN18CCryptoProviderRSA15ImportPublicKeyEPKc
warning: unresolved symbol: _Z13base64_encodePKhj

alexey$ node a.out.js a a
missing function: _ZN18CCryptoProviderRSAC1Ev
-1
-1

/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:84
      throw ex;
            ^
abort() at Error
    at jsStackTrace (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:987:13)
    at stackTrace (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:1004:22)
    at abort (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:102355:25)
    at __ZN18CCryptoProviderRSAC1Ev [CCryptoProviderRSA::CCryptoProviderRSA()] (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:5427:72)
    at Array.__ZN18CCryptoProviderRSAC1Ev__wrapper [CCryptoProviderRSA::CCryptoProviderRSA?_()] [as 353] (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:99881:67)
    at Object.dynCall_vi (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:99727:34)
    at invoke_vi (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:7004:25)
    at _main (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:7515:4)
    at Object.asm._main (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:100433:19)
    at Object.callMain (/Users/alexey/emsdk_portable/emscripten/1.29.0/a.out.js:102231:30)
```

What I am doing wrong?

Thanks

**Comment by alexey-sh** [comment]
```
alexey$ python tests/runner.py test_cases 
warning: incorrect target triple 'i386-pc-linux-gnu' (did you use emcc/em++ on all source files and not clang directly?)
....
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/fixablebadcasts_fastcomp'...
warning: unexpected number of arguments 2 in call to 'twoparam', should be 1
warning: unexpected number of arguments 4 in call to '_ZN7WebCore33signedPublicKeyAndChallengeStringEjRKN3WTF6StringERKNS_3URLE', should be 3
....
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/fuzz6_ta2'...
warning: unresolved symbol: strcmp

....
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/i24_ce_fastcomp'...
warning: unresolved symbol: copysignl
warning: unresolved symbol: isspace
warning: unresolved symbol: fmodl
warning: unresolved symbol: tolower
warning: unresolved symbol: _ZNSt9exceptionD2Ev
warning: unresolved symbol: _ZTISt9exception
warning: unresolved symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
....
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phi24_ta2'...
warning: unresolved symbol: strcmp
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phicubed'...
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phientryimplicit'...
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phientryimplicitmix'...
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phientryimplicitmoar'...
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/philoop_ta2'...
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phinonreachable64'...
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/phiptrtoint'...
warning: unresolved symbol: rand
WARNING  root: function requested to be exported, but not implemented: "_main"
....
Testing case '/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/sillyfuncast'...
warning: unexpected return type i32 in call to 'doit', should be void
<skipping: case "/Users/alexey/emsdk_portable/emscripten/1.29.0/tests/cases/sillyfuncast2_noasm" not relevant for asm.js> None
...

ok

----------------------------------------------------------------------
Ran 1 test in 97.328s

OK
```

**Comment by alexey-sh** [comment]
GOT IT!

```
./emcc /Users/alexey/yandex_encrypter/base64.cpp /Users/alexey/yandex_encrypter/CP_RSA.cpp /Users/alexey/yandex_encrypter/encrypt.cpp
```
