### ISSUE TITLE
sourcemapper.js is crashing on an invalid mapping with line number 0

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#3186]
I've traced it back to "//@line 0" in the generated JavaScript:

```
  $31 = (($30) - ($29))|0;
  $32 = $31 >>> 2; //@line 0 "emscripten/1.29.0/emscripten/system/include/libcxx/iterator"
  $$01$i$i = $26;$34 = $25;
  while(1) {
   $33 = HEAP32[$34>>2]|0; //@line 1749 "emscripten/1.29.0/emscripten/system/include/libcxx/algorithm"
   HEAP32[$$01$i$i>>2] = $33; //@line 1749 "emscripten/1.29.0/emscripten/system/include/libcxx/algorithm"
   $35 = (($34) + 4|0); //@line 1179 "emscripten/1.29.0/emscripten/system/include/libcxx/iterator"
   $36 = (($$01$i$i) + 4|0); //@line 1748 "emscripten/1.29.0/emscripten/system/include/libcxx/algorithm"
   $37 = ($35|0)==($28|0); //@line 1347 "emscripten/1.29.0/emscripten/system/include/libcxx/iterator"
   if ($37) {
    break;
   } else {
    $$01$i$i = $36;$34 = $35;
   }
  }
  $38 = (($32) + 1)|0; //@line 0 "emscripten/1.29.0/emscripten/system/include/libcxx/iterator"
  $scevgep17$i = (($26) + ($38<<2)|0);
```

The crash looks like this:

```
emscripten/1.29.0/emscripten/tools/node_modules/source-map/lib/source-map/source-map-generator.js:250
        throw new Error('Invalid mapping.');
        ^
Error: Invalid mapping.
    at SourceMapGenerator_validateMapping [as _validateMapping] (emscripten/1.29.0/emscripten/tools/node_modules/source-map/lib/source-map/source-map-generator.js:250:15)
    at SourceMapGenerator_addMapping [as addMapping] (emscripten/1.29.0/emscripten/tools/node_modules/source-map/lib/source-map/source-map-generator.js:99:12)
    at generateMap (emscripten/1.29.0/emscripten/tools/source-maps/sourcemapper.js:130:15)
    at Object.<anonymous> (emscripten/1.29.0/emscripten/tools/source-maps/sourcemapper.js:204:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

It looks like DILocation::getLineNumber() in LLVM returns 0 if the mapping is missing. Would it be a good idea to just skip those in JSBackend.cpp?

I tried to get a reduced test case but it's happening on a massive code base and a reduction doesn't look easy. Source maps seem to work fine if the mappings with a line of 0 are ignored.

**Comment by neilogd** [comment]
I also see the same thing happening too :(

**Comment by michaKFromParis** [comment]
Me too. Works with 1.29.0. Fails as soon as I switch to 1.30.0

**Comment by kripken** [comment]
This should be fixed on current incoming, we merged a pull for it.

**Comment by michaKFromParis** [comment]
I confirm the incoming branch resolved the issue

**Comment by kripken** [comment]
Great, thanks for confirming.
