### ISSUE TITLE
XXX missing C define EMSCRIPTEN_FULLSCREEN_SCALE_CENTER

### ISSUE THREAD

**Issue by lostdj** [kripken/emscripten#3208]
I'm trying to use SDL 2 port. Sorry, can't provide the code triggering this — it's huge.

Linux x86-64, Emscripten v1.29.10. The SDL 2 is from master, and I build it myself.

```
warning: unexpected number of arguments 0 in call to 'SDL_SYS_GetTLSData', should be 1
warning: unexpected number of arguments 0 in call to 'SDL_SYS_GetTLSData', should be 1
error: failure to execute js library "library_html5.js": XXX missing C define EMSCRIPTEN_FULLSCREEN_SCALE_CENTER!,,
preprocessed source (you can run a js engine on this to get a clearer error message sometimes):
=============
/*******************************************************************************
 * EMSCRIPTEN GLEW 1.10.0 emulation
 *
 * What it does:
 * - Stubs init function.
 * - GL Extensions support.
 *
 * Optional:
 * - isLinaroFork variable to enable glew-es specific error strings.
 *   This is enabled by default, but should be disabled when upstream glew conflicts.
 *
 * Authors:
 * - Jari Vetoniemi <mailroxas@gmail.com>
 ******************************************************************************/

var LibraryGLEW = {
  $GLEW__deps: ['glGetString'],
  $GLEW: {
    isLinaroFork: 1,
    extensions: null,

    error: {
      0:null, // GLEW_OK || GLEW_NO_ERROR
      1:null, // GLEW_ERROR_NO_GL_VERSION
      2:null, // GLEW_ERROR_GL_VERSION_10_ONLY
      3:null, // GLEW_ERROR_GLX_VERSION_11_ONLY

      4:null, // GLEW_ERROR_NOT_GLES_VERSION
      5:null, // GLEW_ERROR_GLES_VERSION
      6:null, // GLEW_ERROR_NO_EGL_VERSION
      7:null, // GLEW_ERROR_EGL_VERSION_10_ONLY

      8:null, // Unknown error
    },

    version: {
      1:null, // GLEW_VERSION
      2:null, // GLEW_VERSION_MAJOR
      3:null, // GLEW_VERSION_MINOR
      4:null, // GLEW_VERSION_MICRO
    },

    errorStringConstantFromCode: function(error) {
      if (GLEW.isLinaroFork) {
        switch (error) {
          case 4:return "OpenGL ES lib expected, found OpenGL lib"; // GLEW_ERROR_NOT_GLES_VERSION
          case 5:return "OpenGL lib expected, found OpenGL ES lib"; // GLEW_ERROR_GLES_VERSION
          case 6:return "Missing EGL version"; // GLEW_ERROR_NO_EGL_VERSION
          case 7:return "EGL 1.1 and up are supported"; // GLEW_ERROR_EGL_VERSION_10_ONLY
          default:break;
        }
      }

      switch (error) {
        case 0:return "No error"; // GLEW_OK || GLEW_NO_ERROR
        case 1:return "Missing GL version"; // GLEW_ERROR_NO_GL_VERSION
        case 2:return "GL 1.1 and up are supported"; // GLEW_ERROR_GL_VERSION_10_ONLY
        case 3:return "GLX 1.2 and up are supported"; // GLEW_ERROR_GLX_VERSION_11_ONLY
        default:return null;
      }
    },

    errorString: function(error) {
      if (!GLEW.error[error]) {
        var string = GLEW.errorStringConstantFromCode(error);
        if (!string) {
          string = "Unknown error";
          error = 8; // prevent array from growing more than this
        }
        GLEW.error[error] = allocate(intArrayFromString(string), 'i8', ALLOC_NORMAL);
      }
      return GLEW.error[error];
    },

    versionStringConstantFromCode: function(name) {
      switch (name) {
        case 1:return "1.10.0"; // GLEW_VERSION
        case 2:return "1"; // GLEW_VERSION_MAJOR
        case 3:return "10"; // GLEW_VERSION_MINOR
        case 4:return "0"; // GLEW_VERSION_MICRO
        default:return null;
      }
    },

    versionString: function(name) {
      if (!GLEW.version[name]) {
        var string = GLEW.versionStringConstantFromCode(name);
        if (!string)
          return 0;
        GLEW.version[name] = allocate(intArrayFromString(string), 'i8', ALLOC_NORMAL);
      }
      return GLEW.version[name];
    },

    extensionIsSupported: function(name) {
      if (!GLEW.extensions) {
        GLEW.extensions = Pointer_stringify(_glGetString(0x1F03)).split(' ');
      }

      if (GLEW.extensions.indexOf(name) != -1)
        return 1;

      // extensions from GLEmulations do not come unprefixed
      // so, try with prefix
      return (GLEW.extensions.indexOf("GL_" + name) != -1);
    },
  },

  glewInit: function() { return 0; },

  glewIsSupported: function(name) {
    var exts = Pointer_stringify(name).split(' ');
    for (i in exts) {
      if (!GLEW.extensionIsSupported(exts[i]))
        return 0;
    }
    return 1;
  },

  glewGetExtension: function(name) {
    return GLEW.extensionIsSupported(Pointer_stringify(name));
  },

  glewGetErrorString: function(error) {
    return GLEW.errorString(error);
  },

  glewGetString: function(name) {
    return GLEW.versionString(name);
  },

};

autoAddDeps(LibraryGLEW, '$GLEW');
mergeInto(LibraryManager.library, LibraryGLEW);


=============

Internal compiler error in src/compiler.js! Please raise a bug report at https://github.com/kripken/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "XXX missing C define EMSCRIPTEN_FULLSCREEN_SCALE_CENTER!" | undefined
Traceback (most recent call last):
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/emscripten.py", line 1673, in <module>
    _main(environ=os.environ)
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/emscripten.py", line 1661, in _main
    temp_files.run_and_clean(lambda: main(
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/emscripten.py", line 1669, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/emscripten.py", line 1556, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/emscripten.py", line 891, in emscript_fast
    cwd=path_from_root('src'), error_limit=300)
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/tools/jsrun.py", line 63, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/nix/store/8vnhq3w7kysmcgvamsqcv3j1pxfgkffq-nodejs-0.10.32/bin/node', '/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/src/compiler.js', '/tmp/tmpigDsqj.txt', ';', 'glue'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it, and do the work to get that through
// closure compiler if necessary. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..gener
Traceback (most recent call last):
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/emcc", line 1319, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/tools/shared.py", line 1522, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js
```

Ran a search for `EMSCRIPTEN_FULLSCREEN_SCALE_CENTER`:
```
src/library_html5.js:
  607        var windowedRttHeight = target.height;
  608  
  609:       if (strategy.scaleMode == {{{ cDefine('EMSCRIPTEN_FULLSCREEN_SCALE_CENTER') }}}) {
  610          __setLetterbox(target, (cssHeight - windowedCssHeight) / 2, (cssWidth - windowedCssWidth) / 2);
  611          cssWidth = windowedCssWidth;

 1344      var inAspectRatioFixedFullscreenMode = __currentFullscreenStrategy.scaleMode == {{{ cDefine('EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT') }}};
 1345      var inPixelPerfectFullscreenMode = __currentFullscreenStrategy.canvasResolutionScaleMode != {{{ cDefine('EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE') }}};
 1346:     var inCenteredWithoutScalingFullscreenMode = __currentFullscreenStrategy.scaleMode == {{{ cDefine('EMSCRIPTEN_FULLSCREEN_SCALE_CENTER') }}};
 1347      var screenWidth = inHiDPIFullscreenMode ? Math.round(window.innerWidth*window.devicePixelRatio) : window.innerWidth;
 1348      var screenHeight = inHiDPIFullscreenMode ? Math.round(window.innerHeight*window.devicePixelRatio) : window.innerHeight;


src/struct_info.json:
 1172              "EMSCRIPTEN_FULLSCREEN_SCALE_STRETCH",
 1173              "EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT",
 1174:             "EMSCRIPTEN_FULLSCREEN_SCALE_CENTER",
 1175              "EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE",
 1176              "EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_STDDEF",


system/include/emscripten/html5.h:
  250  #define EMSCRIPTEN_FULLSCREEN_SCALE_STRETCH 1
  251  #define EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT  2
  252: #define EMSCRIPTEN_FULLSCREEN_SCALE_CENTER  3
  253  
  254  #define EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE int


tests/test_html5_fullscreen.c:
  161      case 5: requestFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_STRETCH, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  162      case 6: requestFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  163:     case 7: requestFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_CENTER, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  164  
  165      case 8: enterSoftFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_STRETCH, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_STDDEF, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  ...
  169      case 12: enterSoftFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_STRETCH, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  170      case 13: enterSoftFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  171:     case 14: enterSoftFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_CENTER, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_DEFAULT); break;
  172  
  173      case 15: requestFullscreen(EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT, EMSCRIPTEN_FULLSCREEN_CANVAS_SCALE_NONE, EMSCRIPTEN_FULLSCREEN_FILTERING_NEAREST); break;
```

And in SDL 2: nothing.

**Comment by lostdj** [comment]
Tried it out with `-s USE_SDL=2` instead of my own build, got the same error.

**Comment by kripken** [comment]
Does emcc -v show any errors?

Which version of emscripten are you on?

Try emcc --clear-cache --clear-ports , perhaps a cache corruption.

- Alon

**Comment by lostdj** [comment]
> Does emcc -v show any errors?

No. It compiles successfuly hundreds of files and fails in the end, linking them all to an *executable*.

> Which version of emscripten are you on?

I did provide all the info in the first post. :o) It's Linux x86-64, Emscripten v1.29.10.

> Try emcc --clear-cache --clear-ports , perhaps a cache corruption.

It helped! Thanks. It wasn't corrupted, but compiled by a bit older Emscripten just from a few months ago. Perhaps there should be a mechanism checking for that? Or there is one and it failed...

***

While we're on topic, what is the reason for
```
/nix/store/9y8nrgrmn2vvmph6vygvwhyzyy5yslmn-emscripten-1.29.10/bin/tools/node_modules/source-map/lib/source-map/source-map-generator.js:250
        throw new Error('Invalid mapping.');
```
(of course, it doesn't happen in an optimized *release* build)
I commented out that line and it compiles fine.

Or should I create another issue?

**Comment by kripken** [comment]
We do check the version number and clear the cache, but we don't do it  with the ports directory. If something went wrong there, like a reboot in the middle of building a port, it's possible it was left in an inconsistent state.

The source mapper exception might be one of the open source mapping bugs, no one seems to have much time to work on debug info. That should only happen though on `-g4` builds?

- Alon

**Comment by lostdj** [comment]
> but we don't do it with the ports directory

I was building SDL2 from source by myself first time, not from ports. And actually it was the first time using SDL2, I had not it cached before it. Damn mystery...

> That should only happen though on -g4 builds?

Yup.

**Comment by kripken** [comment]
Ok. Yeah, there are known issues with `-g4` on large projects, I'm afraid. Few people use debug info, so it gets less attention.

**Comment by lostdj** [comment]
Oh well. Thanks again!
