### ISSUE TITLE
"location" undefined in hello_world_file.js when using nodejs

### ISSUE THREAD

**Issue by pkeir** [kripken/emscripten#3219]
Following the Emscripten tutorial, I find that running the file generated at the "Using files" section, "hello_world_file.js", will work in the browser, but not from the command-line; using nodejs. I receive the following error mesage:

```
$ node hello_world_file.js
/home/XXXX/code/cpp/emscripten/3_files/hello_world_file.js:16
      PACKAGE_PATH = encodeURIComponent(location.pathname.toString().substring
                                        ^
ReferenceError: location is not defined
    at /home/XXXX/code/cpp/emscripten/3_files/hello_world_file.js:16:41
    at Object.<anonymous> (/home/XXXX/code/cpp/emscripten/3_files/hello_world_file.js:162:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

It seems that the "window" variable is unavailable. I am using 32-bit Ubuntu 14.04.1 LTS (feisty) with node v0.12.0 and Emscripten 1.29.0.

**Comment by kripken** [comment]
Yes, preloading files only works on web pages or in web workers currently. I make it show an error message now.
