### ISSUE TITLE
Tests asm1i.test_async and asm3i.test_async fail.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3251]
Running on each OS, the test test_async fails in emterpreted mode with the following:

	======================================================================
	ERROR: test_async (test_core.asm1i)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/clb/slaves/emscripten/ubuntu-incoming/build/emscripten/tests/test_core.py", line 7254, in test_async
	    self.do_run(src, 'HelloWorld!99');
	  File "/home/clb/slaves/emscripten/ubuntu-incoming/build/emscripten/tests/runner.py", line 498, in do_run
	    raise e
	Exception: Expected to find 'HelloWorld!99' in 'HelloWorld!0
	', diff:

	--- expected
	+++ actual
	@@ -1 +1,2 @@
	-HelloWorld!99
	+HelloWorld!0
	+

	======================================================================
	ERROR: test_async (test_core.asm3i)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/clb/slaves/emscripten/ubuntu-incoming/build/emscripten/tests/test_core.py", line 7254, in test_async
	    self.do_run(src, 'HelloWorld!99');
	  File "/home/clb/slaves/emscripten/ubuntu-incoming/build/emscripten/tests/runner.py", line 498, in do_run
	    raise e
	Exception: Expected to find 'HelloWorld!99' in 'HelloWorld!0
	', diff:

	--- expected
	+++ actual
	@@ -1 +1,2 @@
	-HelloWorld!99
	+HelloWorld!0
	+

**Comment by kripken** [comment]
Is still the case on incoming? I fixed something that looks exactly like this yesterday.

**Comment by juj** [comment]
You're right, this no longer occurs, so I think you did fix it for good.
