### ISSUE TITLE
Build error when using Runtime.generateStructInfo

### ISSUE THREAD

**Issue by klaussilveira** [kripken/emscripten#3335]
I'm getting the following build error when trying to build [quakejs](https://github.com/inolen/quakejs):

    Exception message: "TypeError: Object #<Object> has no method 'generateStructInfo'" | TypeError: Object #<Object> has no method 'generateStructInfo'
        at Object.eval (eval at <anonymous> (eval at globalEval (/var/dev/emscripten/src/compiler.js:105:8)), <anonymous>:54:25)
        at Object.LibraryManager.load (eval at globalEval (/var/dev/emscripten/src/compiler.js:105:8), <anonymous>:474:9)
        at JSify (eval at globalEval (/var/dev/emscripten/src/compiler.js:105:8), <anonymous>:71:20)
        at runPhase (/var/dev/emscripten/src/compiler.js:298:5)
        at compile (/var/dev/emscripten/src/compiler.js:318:5)
        at Object.<anonymous> (/var/dev/emscripten/src/compiler.js:331:7)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
    Traceback (most recent call last):
      File "/var/dev/emscripten/emscripten.py", line 1691, in <module>
        _main(environ=os.environ)
      File "/var/dev/emscripten/emscripten.py", line 1679, in _main
        temp_files.run_and_clean(lambda: main(
      File "/var/dev/emscripten/tools/tempfiles.py", line 39, in run_and_clean
        return func()
      File "/var/dev/emscripten/emscripten.py", line 1687, in <lambda>
        DEBUG_CACHE=DEBUG_CACHE,
      File "/var/dev/emscripten/emscripten.py", line 1574, in main
        jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
      File "/var/dev/emscripten/emscripten.py", line 891, in emscript_fast
        cwd=path_from_root('src'), error_limit=300)
      File "/var/dev/emscripten/tools/jsrun.py", line 75, in run_js
        raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])

The code itself is simple:

	cb_context_t: Runtime.generateStructInfo([
		['void*', 'data'],
		['void*', 'cb']
	]),

**Comment by kripken** [comment]
I'm afraid we don't support that version of emscripten anymore - anything using JSify has been deprecated. Perhaps it's best to update QuakeJS to latest emscripten?

**Comment by kripken** [comment]
Oh, I think it relied on dlopen, which we also deprecated...

**Comment by klaussilveira** [comment]
I see. I'll dedicate some time upgrading, then. Thanks! :+1:
