### ISSUE TITLE
Assertion failed: cannot start async op with normal JS calling ccall

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3350]
I created a [simplified test case](https://gist.github.com/rodneyrehm/03debd117ffaf42b2209) for an error I don't understand regarding emterpreter async:

```
run() called, but dependencies remain, so not running
asyncified.js:133 pre-main prep time: 12 ms
asyncified.js:1663 set timer to release wait loop
asyncified.js:1663 waiting... 1428964466450
asyncified.js:130 Assertion failed: cannot start async op with normal JS calling ccall
asyncified.js:133 Assertion failed: cannot start async op with normal JS calling ccall
asyncified.js:53798 Uncaught abort("Assertion failed: cannot start async op with normal JS calling ccall") at Error
    at jsStackTrace (http://localhost/emasync/asyncified.js:1215:13)
    at stackTrace (http://localhost/emasync/asyncified.js:1232:22)
    at abort (http://localhost/emasync/asyncified.js:53794:44)
    at assert (http://localhost/emasync/asyncified.js:397:32)
    at Object.ccallFunc [as ccall] (http://localhost/emasync/asyncified.js:465:31)
    at runForrest (http://localhost/emasync/:14:27)
This error happened during an emterpreter-async save or load of the stack. Was there non-emterpreted code on the stack during save (which is unallowed)? You may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST, or EMTERPRETIFY_YIELDLIST (to consider certain functions ok to run during an emscripten_sleep_with_yield).
This is what the stack looked like when we tried to save it: 1,Error
    at Object.EmterpreterAsync.handle (http://localhost/emasync/asyncified.js:5369:40)
    at _emscripten_sleep (http://localhost/emasync/asyncified.js:5392:24)
    at emterpret (http://localhost/emasync/asyncified.js:47948:6)
    at _a_bit_of_stack (http://localhost/emasync/asyncified.js:50247:2)
    at emterpret (http://localhost/emasync/asyncified.js:47959:6)
    at _asyncified_method (http://localhost/emasync/asyncified.js:50237:2)
    at asm._asyncified_method (http://localhost/emasync/asyncified.js:51909:32)
    at Object.ccallFunc [as ccall] (http://localhost/emasync/asyncified.js:463:20)
    at runForrest (http://localhost/emasync/:14:27)
```

compilation (using emscripten 1.30.5) of the following - straight forward? - source is fine:

```c
#include <cstdlib>
#include <cstring>
#include "test.hpp"
#include <emscripten.h>

void a_bit_of_stack(char *source_string) {

  EM_ASM( console.log("waiting...", Date.now()); );
  emscripten_sleep(200);
  EM_ASM( console.log("we are done!", Date.now()); );
}

void asyncified_method(char *source_string) {
  EM_ASM_INT({
    console.log("set timer to release wait loop");
    _are_we_done_yet = false;
  }, 0);
  
  a_bit_of_stack(source_string);
  EM_ASM( done() );
}
```

what am I missing?

**Comment by kripken** [comment]
That `cannot start async op with normal JS calling ccall` error has just a few things that can cause it. Putting a debug print there in the code should show the problem.

**Comment by rodneyrehm** [comment]
> Putting a debug print there in the code should show the problem.

how? I wen't with `EM_ASM( console.log("...") )` and it gets to `emscripten_sleep()` but not past.

**Comment by kripken** [comment]
I mean in the output.js. Find that assertion, if checks some conditions in order to fire it. Knowing which failed will inform us here.

**Comment by rodneyrehm** [comment]
ah sorry, obvisouly my brain is already asleep. will let the body follow and check tomorrow :)

**Comment by rodneyrehm** [comment]
After realizing that ccall did not yet check for `{async: true}` I installed `incoming`, compiled the test again and found it to be working. sorry for the noise…

```
➜  emcc --version
emcc (Emscripten GCC-like replacement) 1.30.6 (commit f52c5f13b1b7a231fdafd7fce1ff07f42daab205)
```
