### ISSUE TITLE
SDL_mixer port doesn't load Mix_Chunks when using SDL2

### ISSUE THREAD

**Issue by elvissteinjr** [kripken/emscripten#3461]
This can be reproduced by compiling "tests/sdl_audio.c" with "-s USE_SDL=2". 
Mix_LoadWAV simply returns NULL without error in javascript console or Mix_GetError().

Mix_Music works fine with SDL2.

The FAQ page suggests that SDL(1)_mixer is usable with SDL2 and the SDL wiki says that there are next to no changes in the audio backend between SDL1 and SDL2 (although I'm not sure if that's even relevant for the Javascript implementation of SDL_mixer).

**Comment by kripken** [comment]
Thanks for filing, fixed on incoming. This was an old hack that had to be removed.

**Comment by sjm1982** [comment]
C:\Program Files\Emscripten>emcc tests/sdl2glshader.c -s USE_SDL=2 -s LEGACY_GL_EMULATION=1 -o s.html
WARNING:root:retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_9.zip
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\\emcc", line 1128, in <module>
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "C:\Program Files\Emscripten\emscripten\1.35.0\\emcc", line 1108, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 527, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\ports\sdl.py", line 57, in process_args
    get(ports, settings, shared)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\ports\sdl.py", line 23, in get
    ports.fetch_project('sdl2', 'https://github.com/emscripten-ports/SDL2/archive/' + TAG + '.zip', 'SDL2-' + TAG)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 469, in fetch_project
    retrieve()
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 441, in retrieve
    f = urllib2.urlopen(url)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>



i error 
hello i don't sdl2 connect and install 
how is help me 
than you so much
