### ISSUE TITLE
Error linking static libraries

### ISSUE THREAD

**Issue by ZengruiWang** [kripken/emscripten#3519]
Hi

After couple of days I have complied all the libraries I need for the project into LLVM static library, some of them are compiled in Visual Studio 2010 with `.bc` extension, while the others are built under Linux with the extension of `.a`, my problem is when linking them together in Visual Studio 2010, there are some warning message that I am not fully understand and when compiles for a while it stops working with a linking error message.

There are two types of warning message which I don't understand:
1)  C:\Program Files\Emscripten\clang\e1.30.0_64bit\llvm-nm: C:\Users\zwang\AppData\Local\Temp\emscripten_temp_uvimjz\ar_output_7520_2\box_0d9685b6.o: Invalid record.
(This is related to the Open Dynamic Engine, I compiled it in Linux using Emscripten Command which produced a `libode.a` file) What does "Invalid record" mean?
2)GCCLINK : warning : ignoring debug info with an invalid version (2) in C:\Users\zwang\AppData\Local\Temp\emscripten_temp_bg4toz\ar_output_6000_1\DOMLSInputImpl.o
(I think this refers to the Xerces-c library I compiled under linux) What is the warning indicates?

For the crash error, Windows pops up a window says "llvm-link.exe has stopped working" with detailed message:
Files that help describe the problem:
  C:\Users\zwang\AppData\Local\Temp\WER3611.tmp.WERInternalMetadata.xml
  C:\Users\zwang\AppData\Local\Temp\WER375A.tmp.appcompat.txt
  C:\Users\zwang\AppData\Local\Temp\WER378A.tmp.hdmp

And in the output window of Visual Studio the error message is as follows:
8>  Stack dump:
8>  0.	Program arguments: C:\Program Files\Emscripten\clang\e1.30.0_64bit\llvm-link @C:\Users\zwang\AppData\Local\Temp\tmpdggthe.response -o C:\Users\zwang\AppData\Local\Temp\tmpvrxc54\simplesmartbodyd.bc 
8>  Traceback (most recent call last):
8>    File "C:\Program Files\Emscripten\emscripten\1.30.0\\emcc", line 1238, in <module>
8>      shared.Building.link(linker_inputs, in_temp(target_basename + '.bc'), force_archive_contents=len([temp for i, temp in temp_files if not temp.endswith(STATICLIB_ENDINGS)]) == 0)
8>    File "C:\Program Files\Emscripten\emscripten\1.30.0\tools\shared.py", line 1429, in link
8>GCCLINK : assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error : ' + output
8>AssertionError : Linking error : 

What may be the case of this failure? It is a quite big project is it possible that it run out of memory?Also is there any will to link all the static libraries into one big one?

Thank you so much!

**Comment by ZengruiWang** [comment]
Finally, I found that the version of Emscripten under Windows and Linux is different, I downgrade the Linux one to 1.30.0 and Clang to 3.5 and everything is fine now.
