### ISSUE TITLE
emar can't handle different drive for SDK and project. // SDK-incoming 1.33.2

### ISSUE THREAD

**Issue by asRIA** [kripken/emscripten#3525]
I have project on different windows partition than Emscripten SDK. 
In this case I've got error during linking.

```
Traceback (most recent call last):
  File "C:\Emscripten\emscripten\incoming\emar", line 43, in <module>
    full_newname = os.path.relpath(os.path.join(dir_name, newname))
  File "C:\Emscripten\python\2.7.5.3_64bit\lib\ntpath.py", line 512, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive D:
Traceback (most recent call last):
  File "C:\Emscripten\emscripten\incoming\\emcc", line 1185, in <module>
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout, stderr, forced=forced_stdlibs)
  File "C:\Emscripten\emscripten\incoming\tools\system_libs.py", line 771, in calculate
    libfile = shared.Cache.get(name, lambda: create(name), extension=suffix)
  File "C:\Emscripten\emscripten\incoming\tools\cache.py", line 36, in get
    temp = creator()
  File "C:\Emscripten\emscripten\incoming\tools\system_libs.py", line 771, in <lambda>
    libfile = shared.Cache.get(name, lambda: create(name), extension=suffix)
  File "C:\Emscripten\emscripten\incoming\tools\system_libs.py", line 617, in create_libcxx
    return build_libcxx(os.path.join('system', 'lib', 'libcxx'), libname, libcxx_files, ['-Oz', '-Wno-warn-absolute-paths', '-I' + shared.path_from_root('system', 'lib', 'libcxxabi', 'include')], has_noexcept_version=True)
  File "C:\Emscripten\emscripten\incoming\tools\system_libs.py", line 88, in build_libcxx
    shared.Building.emar('cr', in_temp(lib_filename), o_s)
  File "C:\Emscripten\emscripten\incoming\tools\shared.py", line 1512, in emar
    assert os.path.exists(output_filename), 'emar could not create output file: ' + output_filename
```

Version: 
```
emcc (Emscripten gcc/clang-like replacement) 1.33.2 (commit de5ed239bdc0455629ad7cb74907450180a21f93)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kripken** [comment]
The error occurs in an optional feature (ar hashing), so we could make it ignore that error. However, I don't really know how windows relative paths work in python. @juj, do you know perhaps if there is a way to fix this issue (of wanting a relative path to something on a different drive)?
