### ISSUE TITLE
emscripten crashing after upgrade

### ISSUE THREAD

**Issue by mlogan** [kripken/emscripten#3578]
We've just upgraded to the latest version of emscripten (1.34.0) via the sdk, and I'm getting the following crash.

With the following `test.cpp`:

    #include <cstdio>
    int main() {
	printf("hello\n");
    }

And the command line:

    /opt/emsdk_portable/emscripten/master/em++  test.cpp  -o test.js

I get the following crash output: 

        =============

        Internal compiler error in src/compiler.js! Please raise a bug report at https://github.com/kripken/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "XXX missing C define _SC_PHYS_PAGES!" | undefined
        Traceback (most recent call last):
          File "/opt/emsdk_portable/emscripten/master/emscripten.py", line 1062, in <module>
            _main(environ=os.environ)
          File "/opt/emsdk_portable/emscripten/master/emscripten.py", line 1052, in _main
            temp_files.run_and_clean(lambda: main(
          File "/opt/emsdk_portable/emscripten/master/tools/tempfiles.py", line 39, in run_and_clean
            return func()
          File "/opt/emsdk_portable/emscripten/master/emscripten.py", line 1058, in <lambda>
            DEBUG_CACHE=DEBUG_CACHE,
          File "/opt/emsdk_portable/emscripten/master/emscripten.py", line 959, in main
            temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
          File "/opt/emsdk_portable/emscripten/master/emscripten.py", line 197, in emscript
            cwd=path_from_root('src'), error_limit=300)
          File "/opt/emsdk_portable/emscripten/master/tools/jsrun.py", line 75, in run_js
            raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
        Exception: Expected the command ['node', '/opt/emsdk_portable/emscripten/master/src/compiler.js', '/tmp/tmpgnKk3N.txt', '/opt/emsdk_portable/emscripten/master/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
        // and export values on it, and do the work to get that through
        // closure compiler if necessary. There are various ways Module can be used:
        // 1. Not defined. We create it here
        // 2. A function parameter, function(Module) { ..gener
        Traceback (most recent call last):
          File "/opt/emsdk_portable/emscripten/master/emcc", line 1294, in <module>
            final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
          File "/opt/emsdk_portable/emscripten/master/tools/shared.py", line 1535, in emscripten
            assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
        AssertionError: Emscripten failed to generate .js

The complete output (very very long) is at: https://gist.github.com/mlogan/a6ef2383807231b9a94a

This is on Ubuntu 14.04.

**Comment by mlogan** [comment]
I figured out what was going wrong: We had a stale `.emscripten_cache` directory - removing it fixed the crash.

Perhaps the cache directory should be versioned so that emscripten can delete it after upgrades?

**Comment by mlogan** [comment]
Interestingly, this crash didn't occur when I upgraded emscripten on my laptop (OS X), although I didn't clear the cache there.

**Comment by mlogan** [comment]
Ok, this was completely our fault - we were restoring the .emscripten_cache and .emscripten_ports directories from tarballs on our automated build machine.
