### ISSUE TITLE
Linking problem with new "use all of musl" fix with NO_FILESYSTEM=1

### ISSUE THREAD

**Issue by floooh** [kripken/emscripten#3627]
I'm getting a linker error with my Oryol demos which compile with '-s NO_FILESYSTEM=1' with the current incoming version after these changes had been merged: https://github.com/kripken/emscripten/issues/2701#event-357044425.  As a workaround, removing the NO_FILESYSTEM option fixes the problem, but it would be nice if NO_FILESYSTEM would continue to work as before.

Here's the console output:
```
[100%] Building CXX object code/Hello/CMakeFiles/hello.dir/hello.cc.o
Linking CXX executable /Users/floh/projects/fips-deploy/oryol/emsc-make-release/hello.html
VERBOSE is on, this generates a lot of output and can slow down compilation
adding ___cxa_atexit and deps atexit : function ___cxa_atexit() {
return _atexi
adding _atexit and deps  : function _atexit(func, arg) {
    __ATEX
adding _BDtoIHigh and deps  : true
adding _i64Subtract and deps  : function _i64Subtract(a, b, c, d) {

adding _i64Add and deps  : function _i64Add(a, b, c, d) {
    /*

adding _pthread_cleanup_push and deps  : function _pthread_cleanup_push(routine,
adding _memset and deps  : function _memset(ptr, value, num) {

adding _BDtoILow and deps  : true
adding _bitshift64Lshr and deps  : function _bitshift64Lshr(low, high, bits
adding _bitshift64Shl and deps  : function _bitshift64Shl(low, high, bits)
adding _pthread_cleanup_pop and deps  : function _pthread_cleanup_pop() {
    as
adding _abort and deps  : function _abort() {
    Module['abort'](
adding _memcpy and deps emscripten_memcpy_big : function _memcpy(dest, src, num) {
    d
adding _emscripten_memcpy_big and deps  : function _emscripten_memcpy_big(dest, sr
error: unresolved symbol: __syscall6
adding ___syscall6 and deps  : function ___syscall6() {
Module['printEr
adding _sysconf and deps __setErrNo,$ERRNO_CODES : function _sysconf(name) {
    // long sy
adding ___setErrNo and deps  : function ___setErrNo(value) {
    if (Mo
adding ERRNO_CODES and deps  : {EPERM:1,ENOENT:2,ESRCH:3,EINTR:4,EIO:5,
adding _sbrk and deps  : function _sbrk(bytes) {
    // Implement
adding _BItoD and deps  : true
adding Browser and deps $PATH,emscripten_set_main_loop,emscripten_set_main_loop_timing : {mainLoop:{scheduler:null,method:"",curr
adding PATH and deps  : undefined
adding _emscripten_set_main_loop and deps emscripten_set_main_loop_timing : function _emscripten_set_main_loop(func,
adding _emscripten_set_main_loop_timing and deps  : function _emscripten_set_main_loop_timin
adding _time and deps  : function _time(ptr) {
    var ret = (Dat
adding _pthread_self and deps  : function _pthread_self() {
    //FIXME:
error: unresolved symbol: __syscall140
adding ___syscall140 and deps  : function ___syscall140() {
Module['print
error: unresolved symbol: __syscall146
adding ___syscall146 and deps  : function ___syscall146() {
Module['print
error: unresolved symbol: __syscall54
adding ___syscall54 and deps  : function ___syscall54() {
Module['printE
adding ___dso_handle and deps  : allocate(1, "i32*", ALLOC_STATIC)
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 1071, in <module>
    _main(environ=os.environ)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 1061, in _main
    temp_files.run_and_clean(lambda: main(
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 1067, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 968, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 199, in emscript
    cwd=path_from_root('src'), error_limit=300)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/Users/floh/projects/fips-sdks/osx/emsdk_portable/node/0.10.18_64bit/bin/node', '/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/src/compiler.js', '/Users/floh/projects/fips-sdks/osx/emsdk_portable/.tmp/tmpNm2zKD.txt', '/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it, and do the work to get that through
// closure compiler if necessary. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..gener
Traceback (most recent call last):
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1300, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/shared.py", line 1536, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js
make[3]: *** [/Users/floh/projects/fips-deploy/oryol/emsc-make-release/hello.html] Error 1
make[2]: *** [code/Hello/CMakeFiles/hello.dir/all] Error 2
make[1]: *** [code/Hello/CMakeFiles/hello.dir/rule] Error 2
make: *** [hello] Error 2
[ERROR] Failed to build config 'emsc-make-release' of project 'oryol'
```

**Comment by floooh** [comment]
PS: here's the output without 'verbose', makes it clearer what function cannot be linked:
```
[100%] Building CXX object code/Hello/CMakeFiles/hello.dir/hello.cc.o
Linking CXX executable /Users/floh/projects/fips-deploy/oryol/emsc-make-release/hello.html
error: unresolved symbol: __syscall6
error: unresolved symbol: __syscall140
error: unresolved symbol: __syscall146
error: unresolved symbol: __syscall54
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 1071, in <module>
    _main(environ=os.environ)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 1061, in _main
    temp_files.run_and_clean(lambda: main(
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 1067, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 968, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emscripten.py", line 199, in emscript
    cwd=path_from_root('src'), error_limit=300)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/Users/floh/projects/fips-sdks/osx/emsdk_portable/node/0.10.18_64bit/bin/node', '/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/src/compiler.js', '/Users/floh/projects/fips-sdks/osx/emsdk_portable/.tmp/tmpwmc96l.txt', '/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it, and do the work to get that through
// closure compiler if necessary. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..gener
Traceback (most recent call last):
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1300, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/Users/floh/projects/fips-sdks/osx/emsdk_portable/emscripten/incoming/tools/shared.py", line 1536, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js
make[3]: *** [/Users/floh/projects/fips-deploy/oryol/emsc-make-release/hello.html] Error 1
make[2]: *** [code/Hello/CMakeFiles/hello.dir/all] Error 2
make[1]: *** [code/Hello/CMakeFiles/hello.dir/rule] Error 2
make: *** [hello] Error 2
[ERROR] Failed to build config 'emsc-make-release' of project 'oryol'
```

**Comment by floooh** [comment]
PPS: steps to repro with a simple hello-world sample:
```c
// hello.c
#include <stdio.h>
int main() {
    printf("Hello World!\n");
}
```
```
> emcc -s NO_FILESYSTEM=1 hello.c -o hello.html
warning: unresolved symbol: __syscall6
warning: unresolved symbol: __syscall140
warning: unresolved symbol: __syscall146
warning: unresolved symbol: __syscall54
>_
```

**Comment by kripken** [comment]
Ok, what was going on is that we just stripped out all syscalls, which broke printf when `NO_FILESYSTEM`. I introduced a hack similar to what we had before, to enable printf to work despite not having any underlying FS.

Side question, does Oryol not do any filesystem access? No loading of assets?

**Comment by floooh** [comment]
Awesome thanks! Oryol indeed doesn't do any traditional filesystem calls, it loads all data via its own 'HTTP filesystem wrapper' which uses emscripten_async_wget_data (or similar URL-loader calls on other platforms). I may implement some local virtual filesystem later for other platforms, but that's not a priority at the moment (may be useful on other platforms to implement a local cache). In some other cases I preprocess and bundle data during the build process, but this is embedded directly in the executable via C headers, and works the same on all platforms. This is mainly used for shaders. The whole architecture is really aimed at games that can load their data incrementally, and which don't require huge asset blobs.

Cheers :)
-Floh.

**Comment by kripken** [comment]
I see - nice design!
