### ISSUE TITLE
Unable to pass uint64_t through EM_ASM_

### ISSUE THREAD

**Issue by zz85** [kripken/emscripten#3683]
This follow reduced test case will cause emscripten compilation to fail 

```c
uint64_t test = 1;
EM_ASM_({
}, test);
```

```
LLVM ERROR: okToRemainIllegal(F)
Traceback (most recent call last):
  File "/usr/lib/emsdk_portable/emscripten/master/emscripten.py", line 1062, in <module>
    _main(environ=os.environ)
  File "/usr/lib/emsdk_portable/emscripten/master/emscripten.py", line 1052, in _main
    temp_files.run_and_clean(lambda: main(
  File "/usr/lib/emsdk_portable/emscripten/master/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/usr/lib/emsdk_portable/emscripten/master/emscripten.py", line 1058, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/usr/lib/emsdk_portable/emscripten/master/emscripten.py", line 959, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/usr/lib/emsdk_portable/emscripten/master/emscripten.py", line 95, in emscript
    backend_output = open(temp_js).read()
IOError: [Errno 2] No such file or directory: '/var/folders/5c/rq9sgx_55n55ds285t_gxr140000gn/T/tmprPH0rn.4.js'
Traceback (most recent call last):
  File "/usr/lib/emsdk_portable/emscripten/master/emcc", line 1294, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/lib/emsdk_portable/emscripten/master/tools/shared.py", line 1535, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js
```

**Comment by kripken** [comment]
64-bit integers don't exist in JS, so it is not possible to pass one from C. You can split it into two 32-bit chunks and receive them in JS, for example.

We should probably have a better error message than this. Relevant code is the `assert(okToRemainIllegal(F));` in `ExpandI64.cpp` in the backend.

**Comment by zz85** [comment]
ah make sense, thanks for the explanation! I'll close this issue.
