### ISSUE TITLE
Can't run tests on incoming branch

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#3697]
[This merge](https://github.com/kripken/emscripten/commit/615f7a96e31c9957ef39f21d32a839a09c026421) breaks tests in my setup. I get the following error on any test:

```
./runner.py test_hello_world
test_hello_world (test_core.default) ... (checking sanity from test runner)
INFO     root: (Emscripten: Running sanity checks)
FAIL

======================================================================
FAIL: test_hello_world (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/code/emscripten/tests/test_core.py", line 18, in test_hello_world
    self.do_run_from_file(src, output)
  File "/home/user/code/emscripten/tests/runner.py", line 476, in do_run_from_file
    includes, force_c, build_ll_hook, extra_emscripten_args)
  File "/home/user/code/emscripten/tests/runner.py", line 488, in do_run
    build_ll_hook=build_ll_hook, extra_emscripten_args=extra_emscripten_args, post_build=post_build)
  File "/home/user/code/emscripten/tests/runner.py", line 250, in build
    assert os.path.exists(filename + '.o.js'), 'Source compilation error: ' + output
AssertionError: Source compilation error: opt: Too many positional arguments specified!
Can specify at most 1 positional arguments: See: /home/user/code/tmp/emscripten/emsdk_portable/clang/tag-e1.34.4/build_tag-e1.34.4_64/bin/opt -help
Traceback (most recent call last):
  File "/home/user/code/emscripten/emcc", line 1260, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/home/user/code/emscripten/tools/shared.py", line 1412, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 


----------------------------------------------------------------------
Ran 1 test in 0.197s

FAILED (failures=1)
```

Is it because emscripten-clang should be built from incoming branch too?

**Comment by kripken** [comment]
Yes, you need all 3 repos to be incoming together.

That merge does use new functionality in incoming on the fastcomp branch (not clang).

**Comment by Kagami** [comment]
Thanks.
