### ISSUE TITLE
JS optimizer fails on windows (1.34.6)

### ISSUE THREAD

**Issue by dgrechka** [kripken/emscripten#3729]
Native JS optimizer fails on windows

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.6
clang version 3.7.0
Target: x86_64-pc-windows-msvc
Thread model: posix

node is v0.10.17

compilation flags are "-O3 -g3 -s DISABLE_EXCEPTION_CATCHING=0 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s ALLOW_MEMORY_GROWTH=1"

[temp_dir contents are here](http://home.dgrechka.net/filestore/for_external/emscripten_temp.zip)

The same compilation succeeds on linux.

```
DEBUG    root:   emscript: llvm backend took 18.9179999828 seconds
DEBUG    root: emscript: js compiler glue
DEBUG    root:   emscript: glue took 0.198999881744 seconds
DEBUG    root: asm text sizes[[135675783, 17486], 9142, 200, 5232, 0, 8587, 9286
8061, 3084, 294, 4014, 6066]
DEBUG    root:   emscript: final python processing took 9.59700012207 seconds
DEBUG    root: emcc step "emscript (llvm=>js)" took 30.03 seconds
DEBUG    root: applying pre/postjses
DEBUG    root: optimizing memory initialization
DEBUG    root: emcc step "source transforms" took 3.71 seconds
DEBUG    root: running js post-opts
DEBUG    root: applying js optimization passes: asm noop
chunkification: num funcs: 19096 actual num chunks: 27 chunk size range: 8086868
5 - 5122270
DEBUG    root: js optimizer using native
splitting up js optimization into 27 chunks, using 4 cores  (total: 206.54 MB)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\\emcc", line 1551, in
<module>
    flush_js_optimizer_queue()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\\emcc", line 1465, in
flush_js_optimizer_queue
    flush_js_optimizer_queue(p)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\\emcc", line 1456, in
flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\\emcc", line 1429, in
run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_opt
imizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\tools\shared.py", line
 1575, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_sp
lit, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\tools\js_optimizer.py"
, line 525, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engin
e, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\tools\tempfiles.py", l
ine 47, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\tools\js_optimizer.py"
, line 525, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engin
e, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.6\tools\js_optimizer.py"
, line 440, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\poo
l.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\poo
l.py", line 554, in get
    raise self._value
AssertionError: Error in optimizer:
NMAKE : fatal error U1077: '"C:\Program Files\Emscripten\emscripten\tag-1.34.6\e
mcc.BAT"' : return code '0x1'
Stop.
```

Is there any workaround? Can I make it running "non-native" optimizer if it exists?

**Comment by gouletr** [comment]
Is it safe to mix `-O3 -g3` ?

**Comment by kripken** [comment]
Ok, I think the issue here was that `EMULATE_FUNCTION_POINTER_CASTS` emits massive amounts of helper functions, and they all ended up in one too-big chunk for the optimizer. This should be fixed on incoming, I can build that bitcode file now, but please confirm, @dgrechka .

Side note, you can set `EMCC_NATIVE_OPTIMIZER=0` in the env to use the old optimizer, but a workaround should no longer be needed on incoming, and actually I don't think the other optimizer would help here - it uses more memory in fact, so it would have had even more of a problem with this bug.

@gouletr : yes, those are safe to mix, but `-g3` does disable some of the optimizations in `-O3`.

**Comment by juj** [comment]
This looks like we can close it as resolved. Feel free to reopen if the issue still persists!
