### ISSUE TITLE
Error at the end of linking

### ISSUE THREAD

**Issue by reduz** [kripken/emscripten#3756]
When compiling this file, which uses EM_ASM() macros:

http://pastebin.com/XKbhcDZE

This strange error happens at the end of linking:

/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
throw new JS_Parse_Error(message, line, col, pos);
^
TypeError: object is not a function
at new JS_Parse_Error (/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
at js_error (/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
at croak (/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
at token_error (/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
at unexpected (/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
at /home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:829:33
at block_ (/home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:999:32)
at /home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:978:43
at /home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:982:29
at /home/reduz/bin/emsdk_portable/emscripten/tag-1.34.7/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1112:43

**Comment by kripken** [comment]
Can you provide the header as well, so this compiles standalone? I tried to copy out the `EM_ASM` blocks but they build ok, so it must be something in the rest of the file, for which I also need the header.

**Comment by reduz** [comment]
It was that I forgot the _ in the EM_ASM_(). I was passing arguments but
not expecting a return value.. so I somehow missed that the function had to
be called with the _ in the end.  The example in the doc goes straight to a
function passing values and returning another so the fact a
EM_ASM_(code,values) can be used.

**Comment by kripken** [comment]
Ok, cool. I pushed an improvement to the [docs](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html?highlight=interacting#interacting-with-code-call-javascript-from-native) now.

**Comment by reduz** [comment]
Thanks!!
