### ISSUE TITLE
Missing input file for `--llvm-lto 3`

### ISSUE THREAD

**Issue by rfk** [kripken/emscripten#3765]
The `--llvm-lto 3` option doesn't seem to work with latest incoming, it gives me an error about " Could not open input file":

```
$> cat testit.c 

#include <stdio.h>

int main(void) {
  printf("hello world\n");
  return 0;
}
$>
$> emcc --llvm-lto 3 -o testit.js testit.c 
/usr/bin/opt: /tmp/tmpdHD8X2/testit.bc: error: Could not open input file: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1255, in <module>
    final = shared.Building.llvm_opt(in_temp(target_basename + '.bc'), llvm_opts, DEFAULT_FINAL)
  File "/build/emscripten/tools/shared.py", line 1412, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
$>
```

**Comment by kripken** [comment]
Thanks, this was not tested and broke recently with a build time optimization (skipping llvm-link). Fixed on incoming and added a test.

**Comment by rfk** [comment]
awesome, thanks for the fast response @kripken!
