### ISSUE TITLE
parallel JS optimisation fails on Windows

### ISSUE THREAD

**Issue by aardappel** [kripken/emscripten#3814]
(fingers crossed this is an actual bug this time ;)

Compiling on -O2, I get:

```
DEBUG:root:running js post-opts
DEBUG:root:applying js optimization passes: asm eliminate simplifyExpressions asmLastOpts last
chunkification: num funcs: 3517 actual num chunks: 25 chunk size range: 753676 - 513587
DEBUG:root:js optimizer using native
splitting up js optimization into 25 chunks, using 8 cores  (total: 16.99 MB)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1575, in <module>
    flush_js_optimizer_queue()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1480, in flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1453, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\shared.py", line 1584, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 525, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\tempfiles.py", line 64, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 525, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 440, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
WindowsError: [Error 2] The system cannot find the file specified
make: *** [lobster] Error 1
```

It compiles and runs just fine on `-O1`, or on `-g4 -O2` (since source maps disable the parallel optimization).

**Comment by kripken** [comment]
Perhaps running out of memory or disk space?

Does -O2 work on hello world?

**Comment by juj** [comment]
Try `set EMCC_DEBUG=1` and `set EM_BUILD_VERBOSE=3` before running the commands to get a more verbose output. What does that say?

**Comment by aardappel** [comment]
I have 16GB or ram with plenty of unused physical memory even, and running the build does not produce any spikes in that. 50GB free disk space.

setting `EMCC_CORES` to 2 still causes the problem, so its unhappy with any parallelism.

`emcc -O2 hello_world_sdl.cpp -o hello.html` also reproduces the problem! So definitely something with Windows, or my setup. Actually it produces a mildly different stack trace from the one above, but the same final error:

```
DEBUG:root:running js post-opts
DEBUG:root:applying js optimization passes: asm eliminate simplifyExpressions simplifyIfs registerize minifyNames asmLastOpts last minifyWhitespace cleanup
chunkification: num funcs: 40 actual num chunks: 1 chunk size range: 136548 - 136548
DEBUG:root:js optimizer using native
run_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpxzq6ec.jsfunc_0.js', 'asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1575, in <module>
    flush_js_optimizer_queue()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1480, in flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1453, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\shared.py", line 1584, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 525, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\tempfiles.py", line 64, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 525, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 444, in run_on_js
    filenames = [run_on_chunk(command) for command in commands]
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 276, in run_on_chunk
    proc = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

building with the debug/verbose flags increases the output to below (for my own project). There doesn't seem to be much different about the optimizer invocation that fails from the ones that succeed unless there's something wrong with the .js filename, but it deletes all of those at the end of the run it seems.
```
DEBUG:root:running js post-opts
DEBUG:root:applying js optimization passes: asm eliminate simplifyExpressions simplifyIfs registerize minifyNames asmLastOpts last minifyWhitespace cleanup
chunkification: num funcs: 3517 actual num chunks: 25 chunk size range: 753676 - 513587
DEBUG:root:js optimizer using native
splitting up js optimization into 25 chunks, using 8 cores  (total: 16.99 MB)
rrun_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exeun_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpwwfiq6.jsfunc_0.js', 'asm', 'eliminate', 'simpr', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpaqmz4b.jsfunc_1.js', 'asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']rrlifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']rrun_o
un_on_chun_n_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:unk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\us
un_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/option_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpv8oubb.jsfunc_2.js', 'asm', 'eliminate', 'simplifyExun_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optiers\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpz4ugc7.jsfunc_4.js', 'asm', 'eliminate', 'simplifyExpresmizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmptz8jo_.jsfunc_6.js', 'asm', 'eliminat:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpefxkk1.jsfunc_3.js', 'asm', 'eliminate', 'simplifyEmizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmprpf5gn.jsfunc_5.js', 'asm', 'eliminatpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']e', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespaxpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']sions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']ce']e', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespa

ce']


run_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmp4hovny.jsfunc_7.js', 'asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']
run_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe'r, 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpmazp_2.jsfunc_8.js', 'asm', 'eliminate', 'simplun_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe'ifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace'], 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmp6qouom.jsfunc_9.js', 'asm', 'eliminate', 'simpl
ifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']
run_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmputxuom.jsfunc_10.js', 'asm', 'eliminate', 'simprrlifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']un_un_
on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'con_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpb17uw8.jsfunc_12.js', 'asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmplw051y.jsfunc_11.js', 'asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']
rr
un_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exeun_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpl972_9.jsfunc_14.js', 'asm', 'eliminate', 'simpl', 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpsnsxy4.jsfunc_13.js', 'asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']ifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']

Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1575, in <module>
    flush_js_optimizer_queue()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1480, in flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\\emcc", line 1453, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\shared.py", line 1584, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 525, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\tempfiles.py", line 64, in run_and_clean
run_on_chunk: ['C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe'
    , 'c:\\users\\wouter\\appdata\\local\\temp\\emscripten_temp\\tmpt22cva.jsfunc_15.js', 'asm', 'eliminate', 'simpreturn func()
lifyExpressions', 'simplifyIfs', 'registerize', 'minifyLocals', 'asmLastOpts', 'last', 'minifyWhitespace']
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 525, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.9\tools\js_optimizer.py", line 440, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
WindowsError: [Error 2] The system cannot find the file specified
make: *** [lobster] Error 1
```

**Comment by juj** [comment]
I believe what has happened here is that the installation of `emsdk install sdk-tag-1.34.1-64bit` has failed to build the optimizer, and as a result the file `C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer/RelWithDebInfo/optimizer.exe` does not exist on your computer?

I see that we should immediately at least improve the error message in Emscripten to properly fail with a human-readable error when using optimizer path that doesn't exist. I'll work on adding that.

The second issue is why optimizer could not be built. Can you reissue `emsdk install sdk-tag-1.34.1-64bit > results.txt 2>&1` and post results.txt of the build?

**Comment by kripken** [comment]
> I see that we should immediately at least improve the error message in Emscripten to properly fail with a human-readable error when using optimizer path that doesn't exist. I'll work on adding that.

We already check if the native optimizer exists, and if not, use the js optimizer. Since the native one is used here, it must exist. Except perhaps it exists but is not an executable file somehow?

@aardappel , what files do you see in `~/.emscripten`?

**Comment by kripken** [comment]
Oops, I meant in `~/.emscripten_cache`.

Should be among other files an `optimizer.exe`, that you can execute.

**Comment by aardappel** [comment]
@juj: I did an `emsdk install latest` (1.34.9) which appeared to finish succesfully, and then activated it.

I just ran it again, and it fails with:

```
Running CMake: ['cmake', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Emscripten\\python\\2.7.5.3_64bit\\python.exe', 'C:/Program Files/Emscripten/emscripten/tag-1.34.9\\tools\\optimizer']
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer
Performing a parallel build with 7 cores.
Running build: ['C:\\Windows\\Microsoft.NET/Framework/v4.0.30319\\MSBuild.exe', '/t:Build', '/p:Configuration=RelWithDebInfo', '/p:Platform=Win32', '/nologo', '/verbosity:minimal', 'asmjs_optimizer.sln']
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: Th e build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, pleas e install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting th e Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Program Files\Emscri pten\emscripten\tag-1.34.9_64bit_optimizer\ZERO_CHECK.vcxproj]
Build failed due to exception!
Working directory: C:/Program Files/Emscripten/emscripten/tag-1.34.9_64bit_optimizer
Command '['C:\\Windows\\Microsoft.NET/Framework/v4.0.30319\\MSBuild.exe', '/t:Build', '/p:Configuration=RelWithDebInfo', '/p:Platform=Win32', '/nologo', '/verbosity:minimal', 'asmjs_optimizer.sln']' returned non-zero exit status 1
Installation failed!
```

The problem is likely in js_optimizer.py/find_msbuild() which appears to be hardcoded to find VS2013, whereas CMake generated build files for VS2015.

**Comment by juj** [comment]
That is correct, this looks like a discrepancy. We should be currently always using VS2013 to build, so CMake would be best not to generate build files for VS2015. I'll patch this up.

**Comment by DaveVoyles** [comment]
Has this been resolved? I'm having the same issue. I had VS 2015 express installed and ran into this issue, so I then installed 2010 express, but still have this problem. 

I figured settings my path to run MSBuild v140 would work, but no dice. 

I run

set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

followed by emsdk install latest

but still receive this error. Know of any way of correcting it?

**Comment by pailhead** [comment]
same issue

**Comment by juj** [comment]
This is now fixed by the above commit, and `emsdk` will correctly perform a VS2013 build even if VS2015 is present. The fix will be present in the next emsdk release, but if you want to hot-patch a fixed version to your system, you can directly set up a portable emsdk installation via git by calling

    git clone https://github.com/juj/emsdk/

which gets you the same starting point as if you had installed the portable SDK.

**Comment by DaveVoyles** [comment]
Thank you for following up. 

As a work around, I simpley went with the full installer, and everything worked like a charm.

**Comment by qq728804354** [comment]
vs2015 build optimizer.exe is not run work on win10 x64!
vs2015 构建 optimizer.exe 是不能工作 在win10 x64上！
