### ISSUE TITLE
LLVM ERROR: okToRemainIllegal(F)

### ISSUE THREAD

**Issue by claudiodaffra** [kripken/emscripten#3889]
LLVM gives me this error message , emscripten 1.34
int main ( void ) {
	double x = EM_ASM_DOUBLE({
	Module.print('I received: ' + $0);
	return $0 ;
	}, 4294967295 ); <--- here issue !
	printf ( "%lf",x ) ;
return 0 ;
}
 
i have pass a ulong  (0,4294967295) indeed long (-2147483647,+2147483647)
compiler fail
indeed if i pass 4294967295.0 as double compiler works fine.

here LLVM error bug , traceback

LLVM ERROR: okToRemainIllegal(F)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.34.1\emscripten.py", line 1062, in <module>
    _main(environ=os.environ)
  File "C:\Program Files\Emscripten\emscripten\1.34.1\emscripten.py", line 1052, in _main
    temp_files.run_and_clean(lambda: main(
  File "C:\Program Files\Emscripten\emscripten\1.34.1\tools\tempfiles.py", line 39, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\1.34.1\emscripten.py", line 1058, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "C:\Program Files\Emscripten\emscripten\1.34.1\emscripten.py", line 959, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "C:\Program Files\Emscripten\emscripten\1.34.1\emscripten.py", line 102, in emscript
    start_funcs = backend_output.index(start_funcs_marker)
ValueError: substring not found
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.34.1\emcc", line 1294, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\Program Files\Emscripten\emscripten\1.34.1\tools\shared.py", line 1535, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js

**Comment by kripken** [comment]
This may have been fixed, I don't see a crash in 1.35.4. Instead I see a warning

````
emcc a.cpp
a.cpp:8:6: warning: integer literal is too large to be represented in type 'long' and is subject to undefined behavior under C++98, interpreting as 'unsigned long'; this literal will have type 'long long'
      in C++11 onwards [-Wc++11-compat]
  }, 4294967295 );// <--- here issue !
     ^
emscripten/system/include/emscripten/emscripten.h:59:69: note: expanded from macro 'EM_ASM_DOUBLE'
#define EM_ASM_DOUBLE(code, ...) emscripten_asm_const_double(#code, __VA_ARGS__)
                                                                    ^
1 warning generated.
````

If you want that to be a double, sounds like in modern c++ you need either `.0` or to cast it to a double.
