### ISSUE TITLE
LLVM assertion: "Unsupported type" for [6 x i32] on incoming branch with Rust code

### ISSUE THREAD

**Issue by brson** [kripken/emscripten#3970]
On my emscripten branch of Rust using emscripten-fastcomp/incoming (0bf1ff848f0548516ab244254e43eca3365ffd2e) LLVM hits an assert compiling hello world when doing final linking with emcc.

```
$ emcc hello.ll
[6 x i32]
LLVM ERROR: false && "Unsupported type"
Traceback (most recent call last):
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emcc", line 12, in <module>
    emcc.run()
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emcc.py", line 1354, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/mnt/dev/emsdk_portable/emscripten/incoming/tools/shared.py", line 1593, in emscripten
    call_emscripten(cmdline)
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 1609, in _main
    temp_files.run_and_clean(lambda: main(
  File "/mnt/dev/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 1615, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 1512, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 106, in emscript
    backend_output = open(temp_js).read()
IOError: [Errno 2] No such file or directory: '/tmp/tmpUMYT0u.4.js'

```

The LLVM IR is in [this gist](https://gist.github.com/brson/6f9bb215e7a475876da3) (very large).

**Comment by brson** [comment]
The assert in question seems to be in JSBackend.cpp line 917:

```c++
std::string JSWriter::getCast(const StringRef &s, Type *t, AsmCast sign) {
  switch (t->getTypeID()) {
    default: {
      errs() << *t << "\n";
      assert(false && "Unsupported type");
    }
    case Type::VectorTyID:
      return std::string("SIMD_") + SIMDType(cast<VectorType>(t)) + "_check(" + s.str() + ")";
    case Type::FloatTyID: {
      if (PreciseF32 && !(sign & ASM_FFI_OUT)) {
        if (sign & ASM_FFI_IN) {
          return ("Math_fround(+(" + s + "))").str();
        } else {
          return ("Math_fround(" + s + ")").str();
        }
      }
      // otherwise fall through to double
    }
    case Type::DoubleTyID: return ("+" + s).str();
    case Type::IntegerTyID: {
      // fall through to the end for nonspecific
      switch (t->getIntegerBitWidth()) {
        case 1:  if (!(sign & ASM_NONSPECIFIC)) return sign == ASM_UNSIGNED ? (s + "&1").str()     : (s + "<<31>>31").str();
        case 8:  if (!(sign & ASM_NONSPECIFIC)) return sign == ASM_UNSIGNED ? (s + "&255").str()   : (s + "<<24>>24").str();
        case 16: if (!(sign & ASM_NONSPECIFIC)) return sign == ASM_UNSIGNED ? (s + "&65535").str() : (s + "<<16>>16").str();
        case 32: return (sign == ASM_SIGNED || (sign & ASM_NONSPECIFIC) ? s + "|0" : s + ">>>0").str();
        default: llvm_unreachable("Unsupported integer cast bitwidth");
      }
    }
    case Type::PointerTyID:
      return (sign == ASM_SIGNED || (sign & ASM_NONSPECIFIC) ? s + "|0" : s + ">>>0").str();
  }
}
```

**Comment by kripken** [comment]
Looks like the troubling function is `rust_begin_unwind`. Is that new in this build, or was it there before?

Is it necessary currently, as we don't support unwinding yet? Of course I should still fix this bug ;)

**Comment by kripken** [comment]
Fixed on incoming. Verified that that bitcode now builds and prints hello world properly.

**Comment by brson** [comment]
Thanks!
