### ISSUE TITLE
debugging async emterpreter failure

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#4046]
I'm trying to figure out what's causing my emscripted library to fail when async emterpreter is in play. For the record, the emterpreted code runs fine as long as the C code does not execute `emscripten_sleep(20);`. As soon as C is put to sleep things go bad.

According to previous advice (including [Deciding on which methods to Emterpret for async](https://github.com/kripken/emscripten/wiki/Emterpreter#dynamic-tools)) I'm building the library as follows for debugging:

```sh
emcc lib/libsass.a -o lib/libsass.js \
	-O0 \
	-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
	-s DISABLE_EXCEPTION_CATCHING=0 \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s EMTERPRETIFY=1 \
	-s EMTERPRETIFY_ASYNC=1 \
	-s EMTERPRETIFY_WHITELIST=@../empterpreter_whitelist.json \
	-s ASSERTIONS=1 \
	-s SAFE_HEAP=1 \
	-s DEMANGLE_SUPPORT=1 \
	--profiling-funcs \
	--minify 0 \
	--memory-init-file 1
```

Chrome now prints the following Error:

```
Uncaught abort(-12) at Error
    at jsStackTrace (http://test.dev/…/libsass.js:1255:13)
    at stackTrace (http://test.dev/…/libsass.js:1272:22)
    at abort (http://test.dev/…/libsass.js:411485:44)
    at SAFE_FT_MASK (http://test.dev/…/libsass.js:401118:15)
    at Object.dynCall_ii (http://test.dev/…/libsass.js:406174:28)
    at invoke_ii (http://test.dev/…/libsass.js:7148:32)
    at emterpret (http://test.dev/…/libsass.js:98079:11)
    at _sass_compiler_parse (http://test.dev/…/libsass.js:400464:2)
    at emterpret (http://test.dev/…/libsass.js:99628:11)
    at __Z20sass_compile_contextP12Sass_ContextPN4Sass7ContextE [sass_compile_context(Sass::Context**)] (http://test.dev/…/libsass.js:396744:2)
This error happened during an emterpreter-async save or load of the stack. Was there non-emterpreted code on the stack during save (which is unallowed)? You may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST.
This is what the stack looked like when we tried to save it: 2,Error
    at Object.EmterpreterAsync.handle (http://test.dev/…/libsass.js:6547:40)
    at _emscripten_sleep (http://test.dev/…/libsass.js:6572:24)
    at emterpret (http://test.dev/…/libsass.js:99573:6)
    at Array._sass_importer_emscripten (http://test.dev/…/libsass.js:395496:2)
    at emterpret (http://test.dev/…/libsass.js:98771:83)
    at Array.__ZN4Sass7Context11call_loaderERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKcRNS_11ParserStateEPNS_6ImportENS1_6vectorIP13Sass_ImporterNS5_ISI_EEEEb (http://test.dev/…/libsass.js:380730:2)
    at Object.dynCall_iiiiiiii (http://test.dev/…/libsass.js:399015:80)
    at invoke_iiiiiiii (http://test.dev/…/libsass.js:7085:38)
    at emterpret (http://test.dev/…/libsass.js:98112:11)
    at __ZN4Sass6Parser12parse_importEv (http://test.dev/…/libsass.js:400627:2)

```

But all the methods are already on the [whitelist](https://github.com/medialize/sass.js/blob/libsass-3.3.2/libsass/empterpreter_whitelist.json):

```
_sass_compiler_parse
__Z20sass_compile_contextP12Sass_ContextPN4Sass7ContextE
_sass_importer_emscripten
__ZN4Sass7Context11call_loaderERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKcRNS_11ParserStateEPNS_6ImportENS1_6vectorIP13Sass_ImporterNS5_ISI_EEEEb
__ZN4Sass6Parser12parse_importEv
```

When building with `-s ASSERTIONS=2` instead of `-s ASSERTIONS=1` I get the following error in Chrome:

```
Uncaught RangeError: Maximum call stack size exceeded
  (anonymous function) @ libsass.js:7430
  (anonymous function) @ libsass.js:1682068
```

Any hints to what I could try next are much appreciated :)

---

```
➜  emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.35.22 (commit ab420bc92d4aee0a81e67f647bc28506f6de3668)
➜  node --version
v4.2.2
```

**Comment by kripken** [comment]
Is the abort inside the `SAFE_FT_MASK` check for the mask? Or for an emterpreter assert in that method? Seeing the generated code for that method, and which line the abort hits, would help.

**Comment by rodneyrehm** [comment]
Hey Alon,

the generated file is 19MB and available to [download](http://rodneyrehm.de/t/libsass.js
). I'm not sure what `SAFE_FT_MASK()` does exactly or what it is you're looking for, but:

```js
function SAFE_FT_MASK(value, mask) {
 value = value | 0;
 mask = mask | 0;
 var ret = 0;
 ret = value & mask;
 asyncState ? abort(-12) | 0 : 0; // <- this is the abort() in question
 if ((ret | 0) != (value | 0)) ftfault(), asyncState ? abort(-12) | 0 : 0;
 return ret | 0;
}
```

**Comment by kripken** [comment]
Thanks. Ok, I wonder if this isn't a safe-heap issue, then - we should add `SAFE_FT_MASK` to the list of functions ok to call while async.

If you remove that aborting line (which is what applying that fix would do), does everything work?

**Comment by rodneyrehm** [comment]
> If you remove that aborting line (which is what applying that fix would do), does everything work?

Not exactly *work*, but now I get a different Error showing C functions that are *not* on the whitelist. I'll report back once I get did the whitelist-and-recompile dance… thx!

**Comment by rodneyrehm** [comment]
Looks like that was the culprit. After adding that last round of C functions to the whitelist, recompiling and disabling the offending line in `SAFE_FT_MASK()` I'm actually getting correct results. **Thank you!**

Now, what do I need to do in order to not have to patch the compiled file manually? I'm not in a hurry :)

**Comment by kripken** [comment]
Heh, just pull latest incoming :) I pushed the fix + a test.

**Comment by rodneyrehm** [comment]
<3

**Comment by mgreter** [comment]
:+1:
