### ISSUE TITLE
Rust hello world build failure on incoming

### ISSUE THREAD

**Issue by brson** [kripken/emscripten#4082]
I'm working again on landing Rust emscripten support, and on emscripten incoming (LLVM commit 6e11a1442a65c6dba432731cabe2394419c0955a) compiling hello world fails with the following

```
Traceback (most recent call last):
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emcc", line 13, in <module>
    emcc.run()
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emcc.py", line 1370, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/mnt/dev/emsdk_portable/emscripten/incoming/tools/shared.py", line 1588, in emscripten
    call_emscripten(cmdline)
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 1637, in _main
    temp_files.run_and_clean(lambda: main(
  File "/mnt/dev/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 1643, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 1540, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/mnt/dev/emsdk_portable/emscripten/incoming/emscripten.py", line 488, in emscript
    if metadata['simdUint8x16']:
KeyError: 'simdUint8x16'
```

[Bitcode here](https://gist.github.com/brson/20ea00dbd33727eb89c1).

The good news is that emscripten's LLVM no longer crashes rustc in x86 optimized builds.

**Comment by brson** [comment]
Since the error is about simd I imagine we're letting through some simd instructions emscripten doesn't want, but from the error I don't know what it is.

**Comment by kripken** [comment]
Are you sure you're using incoming on all 3 branches - emscripten, llvm and clang? And that you rebuilt llvm+clang on those? That error looks like a mismatch between the first two repos. Does `emcc -v` report any concerns?

**Comment by brson** [comment]
Oh, my. emcc says

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.22
clang version 3.8.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 7795e5fc3f35ae8e63fe191280bba7aed5b3878f) (https://github.com/kripken/emscripten-fastcomp/ 3acf8b4c4c5a4fc9c64f3dc52042f8bd2f42cbf5) (emscripten 1.35.14 : 1.35.14)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/dev/emsdk_portable/clang/fastcomp/build_incoming_64/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
WARNING:root:LLVM version appears incorrect (seeing "3.8", expected "3.9")
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.35.22, 1.35.14, 1.35.14)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:java does not seem to exist, required for closure compiler, which is optional (define JAVA in /home/brian/.emscripten if you want it)
WARNING:root:closure compiler will not be available
```

I've got rust on the latest incoming branch from the fastcomp repo (6e11a1442a65c6dba432731cabe2394419c0955a), but my emcc reports an old commit for the fastcomp directory. I must not have installed it correctly. How do I get an emcc that correpsonds to emscripten-fastcomp/incoming?


The warnings of having

**Comment by brson** [comment]
I've done `emsdk update && emsdk install emscripten-incoming-64bit && emsdk activate emscripten-incoming-64bit`.

**Comment by brson** [comment]
Oh, this is not a bug.

**Comment by bobvanluijt** [comment]
Ooo, but can you explain what you did to solve it?

I have: LLVM version appears incorrect (seeing "7.3", expected "3.9")
