### ISSUE TITLE
-O(2/s/z/...) optimizations lead to 'No such file or directory' error

### ISSUE THREAD

**Issue by Matthiasvanderhallen** [kripken/emscripten#4139]
When compiling with these flags on a macbook and emscripten 1.35.2,
```
em++ -O2 hello_world_file.cpp --preload-file hello_world_file.txt@tests/hello_world_file.txt -o hello.html
```

I get 'No such file or directory' errors:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/emcc", line 1602, in <module>
    flush_js_optimizer_queue()
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/emcc", line 1505, in flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/emcc", line 1478, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/shared.py", line 1634, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 538, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 538, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 444, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
```
The files are simply those of the tutorial: https://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html#using-files

-O1 or default of -O0 all work fine.

**Comment by kripken** [comment]
What does output with `EMCC_DEBUG=1` in the env look like?

**Comment by Matthiasvanderhallen** [comment]
```
DEBUG:root:PYTHON not defined in /Users/Matthias/.emscripten, using "/usr/local/opt/python/bin/python2.7"
DEBUG:root:JAVA not defined in /Users/Matthias/.emscripten, using "java"
DEBUG:root:PYTHON not defined in /Users/Matthias/.emscripten, using "/usr/local/opt/python/bin/python2.7"
DEBUG:root:JAVA not defined in /Users/Matthias/.emscripten, using "java"
WARNING:root:invocation: /usr/local/Cellar/emscripten/1.35.2/libexec/emcc -O2 hallo_world_file.cpp --preload-file hello_world_file.txt@tests/hello_world_file.txt -o hello.html --emscripten-cxx  (in /Users/Matthias/Desktop/emscripten)
WARNING:root:did not see a source tree above or next to the LLVM root directory (guessing based on directory of /usr/local/Cellar/emscripten/1.35.2/libexec/llvm/bin/llc), could not verify version numbers match
INFO:root:(Emscripten: Running sanity checks)
DEBUG:root:compiling to bitcode
DEBUG:root:emcc step "parse arguments and setup" took 0.00 seconds
DEBUG:root:compiling source file: hallo_world_file.cpp
DEBUG:root:running: /usr/local/Cellar/emscripten/1.35.2/libexec/llvm/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=35 -D__EMSCRIPTEN_tiny__=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/local/include -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/include/compat -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/include -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/include/emscripten -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/include/libc -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/include/libcxx -O2 -mllvm -disable-llvm-optzns -std=c++03 hallo_world_file.cpp -Xclang -isystem/usr/local/Cellar/emscripten/1.35.2/libexec/system/include/SDL -emit-llvm -c -o /var/folders/1t/3k8nqnf91_v0l326t7g4p_gc0000gn/T/tmpEuKRWT/hallo_world_file_0.o
DEBUG:root:emcc step "bitcodeize inputs" took 0.02 seconds
DEBUG:root:optimizing hallo_world_file.cpp
DEBUG:root:emcc: LLVM opts: -O3 -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 1]
DEBUG:root:emcc step "process inputs" took 0.01 seconds
DEBUG:root:will generate JavaScript
DEBUG:root:including libc.bc
DEBUG:root:including dlmalloc.bc
DEBUG:root:emcc step "calculate system libraries" took 0.02 seconds
DEBUG:root:linking: ['/var/folders/1t/3k8nqnf91_v0l326t7g4p_gc0000gn/T/tmpEuKRWT/hallo_world_file_0_1.o', '/Users/Matthias/.emscripten_cache/libc.bc', '/Users/Matthias/.emscripten_cache/dlmalloc.bc']
DEBUG:root:emcc step "link" took 0.00 seconds
DEBUG:root:saving intermediate processing steps to /var/folders/1t/3k8nqnf91_v0l326t7g4p_gc0000gn/T/emscripten_temp
DEBUG:root:(not saving intermediate /var/folders/1t/3k8nqnf91_v0l326t7g4p_gc0000gn/T/emscripten_temp/emcc-0-basebc.bc because deferring linking)
DEBUG:root:emcc: LLVM opts: -strip-debug -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush -globaldce -pnacl-abi-simplify-preopt -pnacl-abi-simplify-postopt -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 3]
DEBUG:root:emcc step "post-link" took 0.12 seconds
DEBUG:root:LLVM => JS
DEBUG:root:emscript: llvm backend: /usr/local/Cellar/emscripten/1.35.2/libexec/llvm/bin/llc /var/folders/1t/3k8nqnf91_v0l326t7g4p_gc0000gn/T/tmpEuKRWT/hello.bc -march=js -filetype=asm -o /var/folders/1t/3k8nqnf91_v0l326t7g4p_gc0000gn/T/emscripten_temp/tmpaF7j6F.4.js -O2
DEBUG:root:  emscript: llvm backend took 0.036386013031 seconds
DEBUG:root:emscript: js compiler glue
DEBUG:root:  emscript: glue took 0.184506893158 seconds
DEBUG:root:asm text sizes[[135686, 1672], 579, 130, 1513, 0, 402, 424, 430, 268, 866, 613]
DEBUG:root:  emscript: final python processing took 0.00269103050232 seconds
DEBUG:root:emcc step "emscript (llvm=>js)" took 0.24 seconds
DEBUG:root:setting up files
DEBUG:root:PYTHON not defined in /Users/Matthias/.emscripten, using "/usr/local/opt/python/bin/python2.7"
DEBUG:root:JAVA not defined in /Users/Matthias/.emscripten, using "java"
Packaging file "hello_world_file.txt" to VFS in path "/tests/hello_world_file.txt".
DEBUG:root:applying pre/postjses
DEBUG:root:wrote memory initialization to hello.html.mem
DEBUG:root:emcc step "source transforms" took 0.08 seconds
DEBUG:root:running js post-opts
DEBUG:root:applying js optimization passes: asm eliminate simplifyExpressions simplifyIfs registerize minifyNames asmLastOpts last minifyWhitespace cleanup
chunkification: num funcs: 54 actual num chunks: 1 chunk size range: 139247 - 139247
DEBUG:root:js optimizer using native
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/emcc", line 1602, in <module>
    flush_js_optimizer_queue()
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/emcc", line 1505, in flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/emcc", line 1478, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/shared.py", line 1634, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 538, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 538, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 448, in run_on_js
    filenames = [run_on_chunk(command) for command in commands]
  File "/usr/local/Cellar/emscripten/1.35.2/libexec/tools/js_optimizer.py", line 276, in run_on_chunk
    proc = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by kripken** [comment]
Looks like it's failing to run the native optimizer. Does `~/.emscripten_cache/optimizer.2.exe` not exist, or does it have the wrong permissions to be run?

**Comment by Matthiasvanderhallen** [comment]
That does not exist. An .exe file on a mac, however? :)

**Comment by kripken** [comment]
Heh, we just use `.exe` on all platforms as the suffix, even on linux ;)

Something is going wrong on your system. What are the full contents of `~/.emscripten_cache/`? It should store data there explaining if it tried to build the native optimizer, and if it failed, why.

You can also, as a workaround, disable the native optimizer (but things will be slower), with `EMCC_NATIVE_OPTIMIZER=0` in the env.

**Comment by Matthiasvanderhallen** [comment]
``export EMCC_NATIVE_OPTIMIZER=0`` did the trick, thank you!

The ~/.emscripten_cache/ folder contained the following files:
```
dlmalloc.bc			libc-mt.bc			libcxx.a			libcxxabi.bc			struct_info.compiled.json
dlmalloc_threadsafe.bc		libc.bc				libcxx_noexcept.a		pthreads.bc
```
I made these files available [here](https://drive.google.com/folderview?id=0ByfvlnRhkZKuZmhkY3FweXAyaDA&usp=sharing).

**Comment by kripken** [comment]
No sign it even tried to build the native optimizer. Weird. Possibly something we fixed since that version, worth checking on incoming.

**Comment by Matthiasvanderhallen** [comment]
Is there anything else you need me to do?

**Comment by kripken** [comment]
If this isn't fixed on incoming for you, some printouts in `tools/js_optimizer.py` which check if the native optimizer exists and decides to use it, might help.

**Comment by Matthiasvanderhallen** [comment]
Aha, I had not noticed my brew install was outdated, so it said there was no new version of emscripten. Now there is, I'll leave the results soon!

**Comment by Matthiasvanderhallen** [comment]
It still errors on 1.35.23 when `EMCC_NATIVE_OPTIMIZER=1` or simply not in environment.

```
  File "/usr/local/bin/em++", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/emcc.py", line 1650, in run
    JSOptimizer.flush()
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/emcc.py", line 1557, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/emcc.py", line 1530, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/tools/shared.py", line 1651, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/tools/js_optimizer.py", line 541, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/tools/js_optimizer.py", line 541, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/tools/js_optimizer.py", line 449, in run_on_js
    filenames = [run_on_chunk(command) for command in commands]
  File "/usr/local/Cellar/emscripten/1.35.23/libexec/tools/js_optimizer.py", line 277, in run_on_chunk
    proc = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```

Contents of `~/.emscripten_cache`:
    * dlmalloc.bc
    * libc.bc
    * struct_info.compiled.json

[struct_info.compiled.txt](https://github.com/kripken/emscripten/files/168798/struct_info.compiled.txt)

**Comment by Matthiasvanderhallen** [comment]
I noticed I had a `EMSCRIPTEN_NATIVE_OPTIMIZER` entry in the `.emscripten` config file that was outdated from the time that I experimented with the portable installation. 
Removing this entry made everything work.
Perhaps this kind of error could be signaled during the sanity check. However, I consider this issue closed and kindly thank you for all the help you've given.

**Comment by kripken** [comment]
Glad you figured this out. I added some logging now in debug mode that would have made figuring this out easier (it will print when the native optimizer is overridden, and to what).
