### ISSUE TITLE
What can I do to raise TOTAL_ENV_SIZE?

### ISSUE THREAD

**Issue by IngwiePhoenix** [kripken/emscripten#4181]
I just found myself confronted with:

```
exception thrown: Error: Environment size exceeded TOTAL_ENV_SIZE!,Error: Environment size exceeded TOTAL_ENV_SIZE!
    at ___buildEnvironment (/Users/Ingwie/Work/IceTea/icetea.js:1:102876)
    at _putenv (/Users/Ingwie/Work/IceTea/icetea.js:1:103504)
    at Array.ju (/Users/Ingwie/Work/IceTea/icetea.js:7:15333)
    at rj (/Users/Ingwie/Work/IceTea/icetea.js:20:69012)
    at vj (/Users/Ingwie/Work/IceTea/icetea.js:12:45904)
    at rj (/Users/Ingwie/Work/IceTea/icetea.js:20:68353)
    at Array.lm (/Users/Ingwie/Work/IceTea/icetea.js:8:79277)
    at rj (/Users/Ingwie/Work/IceTea/icetea.js:20:69012)
    at vj (/Users/Ingwie/Work/IceTea/icetea.js:12:45904)
    at rj (/Users/Ingwie/Work/IceTea/icetea.js:20:68353)
```

I know that my code _does_ some ENV manipulation, and in fact my code actually copies the host's ENV into the program by merging `ENV ` with `process.env`, but I didn't expect it to explode like that. When compiling natively, this works.

**Comment by kripken** [comment]
This isn't currently configurable in a nice way, but see library.js, you can just hack `TOTAL_ENV_SIZE` there. Our env support in general is not very thorough.

**Comment by IngwiePhoenix** [comment]
What's that hack you are suggesting, though? I'd like to incorperate it. :)

**Comment by kripken** [comment]
I meant, just edit that value in that file, to something bigger.

**Comment by IngwiePhoenix** [comment]
Could I also do that with a js file specified via —js-library? That way I could keep the change associated to my project.

**Comment by kripken** [comment]
Perhaps, if you copied it to another JS library, then it would override. I'm not sure though.

**Comment by IngwiePhoenix** [comment]
Alright. I'll have to try that then... Thanks!
