### ISSUE TITLE
Error setting -s EXPORTED_RUNTIME_METHODS=[FS_createPath]

### ISSUE THREAD

**Issue by lambdabaa** [kripken/emscripten#4342]
Notably `-s EXPORTED_RUNTIME_METHODS=[]` works for me, but using `[FS_createPath]` does not. See below...

```
Traceback (most recent call last):
  File "/home/gareth/Documents/emsdk_portable/emscripten/master/emcc", line 13, in <module>
    emcc.run()
  File "/home/gareth/Documents/emsdk_portable/emscripten/master/emcc.py", line 932, in run
    exec 'shared.Settings.' + key + ' = ' + value in globals(), locals()
  File "<string>", line 1, in <module>
NameError: name 'FS_createPath' is not defined
Makefile:20: recipe for target 'js/embuild.js' failed
make: *** [js/embuild.js] Error 1
```

**Comment by kripken** [comment]
I think you need quotes, `"FS_createPath"`. The shell might also need extra quotes outside like `-s 'EXPORTED_RUNTIME_METHODS=["FS_createPath"]'`.
