### ISSUE TITLE
[1.36.9] WindowsError: "The system cannot find the file specified"

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten#4519]
I was trying upgrade from precompiled 1.35.0 to 1.36.9 on Windows 10 Anniversary Update. Compilation was finished without any error but running it gives this error: 

```ts
em++ -s INVOKE_RUN=0 -std=c++11 --bind wrapper/bind.cpp -s EXPORT_NAME='_libflifem' -s MODULARIZE=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=['FS'] -s USE_LIBPNG=1 -s USE_ZLIB=1 -D NDEBUG -O2 -ftree-vectorize -g0 -Wall submodules/flif/maniac/util.cpp submodules/flif/maniac/chance.cpp submodules/flif/image/crc32k.cpp submodules/flif/image/image.cpp submodules/flif/image/image-png.cpp submodules/flif/image/image-pnm.cpp submodules/flif/image/image-pam.cpp submodules/flif/image/color_range.cpp submodules/flif/transform/factory.cpp submodules/flif/flif.cpp -o built/flif.js
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\\em++", line 16, in <module>
    emcc.run()
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\emcc.py", line 1811, in run
    JSOptimizer.flush()
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\emcc.py", line 1708, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\emcc.py", line 1681, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\tools\shared.py", line 1769, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\tools\js_optimizer.py", line 555, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\tools\tempfiles.py", line 78, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\tools\js_optimizer.py", line 555, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.9\tools\js_optimizer.py", line 450, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
WindowsError: [Error 2] The system cannot find the file specified
```

Omitting -O2 optimization option is a workaround, but I can't understand why this occurs.

**Comment by SaschaNaz** [comment]
Duplicate of #4506 X|
