### ISSUE TITLE
Missing functions in numeric Rust code

### ISSUE THREAD

**Issue by brson** [kripken/emscripten#4543]
I've run into test failures in the Rust standard l library that look like this:

```
running /mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js
Warning: _Unwind_RaiseException is not correctly implemented
TODO: Unwind_DeleteException
missing function: llvm_log10_f64
-1
warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling

/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:110
      throw ex;
      ^
abort(-1) at Error
    at jsStackTrace (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:1092:13)
    at stackTrace (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:1109:12)
    at abort (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:635207:44)
    at _llvm_log10_f64 (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:2036:59)
    at Array.__ZN3std3f645tests10test_log1017h9ce0a62d0ce43aa1E (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:82367:9)
    at Object.dynCall_v (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:632292:31)
    at invoke_v (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:7531:24)
    at Array.__ZN50__LT_F_u20_as_u20_alloc__boxed__FnBox_LT_A_GT__GT_8call_box17hf1790612779c2855E (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d
3f1.js:551088:2)
    at Array.__ZN3std9panicking3try7do_call17hb117fcd9509a1f90E (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:551116:31)
    at Object.dynCall_vi (/mnt2/dev/rust2/build/x86_64-unknown-linux-gnu/stage2-std/asmjs-unknown-emscripten/release/deps/std-15b0260ec019d3f1.js:632250:32)
```

The problem I assume is this line: "missing function: llvm_log10_f64". I've seen this for the following functions:

- llvm_exp2_f32
- llvm_log2_f32
- llvm_log10_f32
- llvm_exp2_f64
- llvm_log2_f64
- llvm_log10_f64

**Comment by kripken** [comment]
PR in #4544.

**Comment by brson** [comment]
Thanks!

**Comment by kripken** [comment]
Fixed by that PR.
