### ISSUE TITLE
The parser is failing when _emscripten_replace_memory is present

### ISSUE THREAD

**Issue by yurydelendik** [kripken/emscripten#4715]
When running `emcc t.c -s BINARYEN=1 -O3 -s VERBOSE=1 -s ONLY_MY_CODE=1 -s ALLOW_MEMORY_GROWTH=1 -o t.js` (where t.c can be somthing simple), the following error thrown:

```

true:
==========
;
 }

Traceback (most recent call last):
  File "/Users/yury/Work/junk/test-wasdk/node_modules/wasdk/bin/emscripten/emcc", line 13, in <module>
    emcc.run()
  File "/Users/yury/Work/junk/test-wasdk/node_modules/wasdk/bin/emscripten/emcc.py", line 2030, in run
    subprocess.check_call(cmd, stdout=open(wasm_text_target, 'w'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/yury/Work/junk/test-wasdk/node_modules/wasdk/bin/binaryen/bin/a
```

The parser is failing at parsing 'true' that is present in non-asm.js function.

**Comment by kripken** [comment]
Looks like the `ONLY_MY_CODE` option is the culprit here. It isn't much tested, I'm afraid. Especially it's combo with other options, in this case the problem was with memory growth.

Fixes in those 2 PRs.
