### ISSUE TITLE
Compiling to WASM fails on OSX with fastcomp clang

### ISSUE THREAD

**Issue by johannhof** [kripken/emscripten#4733]
I get the following error message when trying to compile to WebAssembly using emcc incoming installed through emsdk.

<details><p>

```
λ emcc --clear-cache && emcc --clear-ports && emcc hello.c -s WASM=1 -o hello.html
INFO:root:clearing cache as requested by --clear-cache
INFO:root:(Emscripten: Running sanity checks)
INFO:root:clearing ports and cache as requested by --clear-ports
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:retrieving port: binaryen from https://github.com/WebAssembly/binaryen/archive/version_21.zip
WARNING:root:unpacking port: binaryen
INFO:root:generating port: binaryen_tag_version_21.txt... (this will be cached in "/Users/johann/.emscripten_cache/asmjs/binaryen_tag_version_21.txt" for subsequent builds)
INFO:root:building port: binaryen
-- The C compiler identification is Clang 3.9.0
-- The CXX compiler identification is Clang 3.9.0
-- Check for working C compiler: /Users/johann/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang
-- Check for working C compiler: /Users/johann/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /Users/johann/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang++
-- Check for working CXX compiler: /Users/johann/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Building with -std=c++11
-- Building with -msse2
-- Building with -mfpmath=sse
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -fPIC
-- Building with -O2
-- Building with -UNDEBUG
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   binaryen

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/johann/.emscripten_ports/binaryen/binaryen-version_21
Scanning dependencies of target emscripten-optimizer
Scanning dependencies of target wasm
Scanning dependencies of target asmjs
Scanning dependencies of target support
Scanning dependencies of target passes
[  5%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/parser.cpp.o
[  4%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o
[  5%] Building CXX object src/asmjs/CMakeFiles/asmjs.dir/asm_v_wasm.cpp.o
[  5%] Building CXX object src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/simple_ast.cpp.o
[  7%] Building CXX object src/asmjs/CMakeFiles/asmjs.dir/shared-constants.cpp.o
[  8%] Building CXX object src/support/CMakeFiles/support.dir/archive.cpp.o
[ 10%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm.cpp.o
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/emscripten-optimizer/parser.cpp:17:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/emscripten-optimizer/parser.h:25:10: fatal error:
      'algorithm' file not found
#include <algorithm>
         ^
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/emscripten-optimizer/optimizer-shared.cpp:17:10: fatal error:
      'limits' file not found
#include <limits>In file included from
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/asmjs/asm_v_wasm.cpp:         ^17
:
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/asm_v_wasm.h:20:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/mixed_arena.h:20:10: fatal error:
      'atomic' file not found
#include <atomic>
         ^
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/emscripten-optimizer/simple_ast.cpp:17:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/emscripten-optimizer/simple_ast.h:20:10: fatal error:
      'algorithm' file not found
#include <algorithm>
         ^
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/asmjs/shared-constants.cpp:17:
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/asmjs/shared-constants.h:20:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/emscripten-optimizer/istring.h:22:10: fatal error:
      'unordered_set' file not found
#include <unordered_set>
         ^
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/support/archive.cpp:17:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/support/archive.h:27:10: fatal error:
      'cstdint' file not found
#include <cstdint>
         ^
[ 11%] Building CXX object src/passes/CMakeFiles/passes.dir/pass.cpp.o
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm/wasm.cpp:17:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm.h:46:10: fatal error:
      'cassert' file not found
#include <cassert>
         ^
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/passes/pass.cpp:17:10: fatal error:
      'chrono' file not found
#include <chrono>
         ^
1 error generated.
make[2]: *** [src/asmjs/CMakeFiles/asmjs.dir/shared-constants.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object src/support/CMakeFiles/support.dir/bits.cpp.o
1 error generated.
make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/parser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 14%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-binary.cpp.o
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/support/bits.cpp:19:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/support/bits.h:20:10: fatal error:
      'climits' file not found
#include <climits>
         ^
1 error generated.
make[2]: *** [src/support/CMakeFiles/support.dir/bits.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm/wasm-binary.cpp:17:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm-binary.h:24:10: fatal error:
      'cassert' file not found
[ 16%] Building CXX object src/passes/CMakeFiles/passes.dir/CoalesceLocals.cpp.o
#include <cassert>
         ^
1 error generated.
1 error generated.
make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/optimizer-shared.cpp.o] Error 1
make[2]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/simple_ast.cpp.o] Error 1
make[1]: *** [src/emscripten-optimizer/CMakeFiles/emscripten-optimizer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object src/wasm/CMakeFiles/wasm.dir/wasm-s-parser.cpp.o
[ 19%] Building CXX object src/passes/CMakeFiles/passes.dir/CodePushing.cpp.o
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/passes/CoalesceLocals.cpp:25:10: fatal error:
      'algorithm' file not found
#include <algorithm>
         ^
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/passes/CodePushing.cpp:22:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm.h:46:10: fatal error:
      'cassert' file not found
#include <cassert>
         ^
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm/wasm-s-parser.cpp:17:
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm-s-parser.h:25:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm.h:46:10: fatal error:
      'cassert' file not found
#include <cassert>
         ^
1 error generated.
make[2]: *** [src/support/CMakeFiles/support.dir/archive.cpp.o] Error 1
make[1]: *** [src/support/CMakeFiles/support.dir/all] Error 2
1 error generated.
make[2]: *** [src/asmjs/CMakeFiles/asmjs.dir/asm_v_wasm.cpp.o] Error 1
make[1]: *** [src/asmjs/CMakeFiles/asmjs.dir/all] Error 2
[ 20%] Building CXX object src/passes/CMakeFiles/passes.dir/DeadCodeElimination.cpp.o
[ 22%] Building CXX object src/passes/CMakeFiles/passes.dir/DuplicateFunctionElimination.cpp.o
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/passes/DeadCodeElimination.cpp:31:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm.h:46:10: fatal error:
      'cassert' file not found
#include <cassert>
         ^
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/passes/DuplicateFunctionElimination.cpp:23:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm.h:46:10: fatal error:
      'cassert' file not found
#include <cassert>
         ^
1 error generated.
1 error generated.
make[2]: *** [src/wasm/CMakeFiles/wasm.dir/wasm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/passes/CMakeFiles/passes.dir/pass.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 23%] Building CXX object src/passes/CMakeFiles/passes.dir/ExtractFunction.cpp.o
In file included from /Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/passes/ExtractFunction.cpp:21:
/Users/johann/.emscripten_ports/binaryen/binaryen-version_21/src/wasm.h:46:10: fatal error:
      'cassert' file not found
#include <cassert>
         ^
1 error generated.
make[2]: *** [src/passes/CMakeFiles/passes.dir/CoalesceLocals.cpp.o] Error 1
1 error generated.
make[2]: *** [src/passes/CMakeFiles/passes.dir/CodePushing.cpp.o] Error 1
1 error generated.
make[2]: *** [src/passes/CMakeFiles/passes.dir/DeadCodeElimination.cpp.o] Error 1
1 error generated.
make[2]: *** [src/passes/CMakeFiles/passes.dir/DuplicateFunctionElimination.cpp.o] Error 1
1 error generated.
make[2]: *** [src/passes/CMakeFiles/passes.dir/ExtractFunction.cpp.o] Error 1
make[1]: *** [src/passes/CMakeFiles/passes.dir/all] Error 2
1 error generated.
make[2]: *** [src/wasm/CMakeFiles/wasm.dir/wasm-s-parser.cpp.o] Error 1
1 error generated.
make[2]: *** [src/wasm/CMakeFiles/wasm.dir/wasm-binary.cpp.o] Error 1
make[1]: *** [src/wasm/CMakeFiles/wasm.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/johann/emsdk_portable/emscripten/incoming/emcc", line 13, in <module>
    emcc.run()
  File "/Users/johann/emsdk_portable/emscripten/incoming/emcc.py", line 1334, in run
    compile_source_file(i, input_file)
  File "/Users/johann/emsdk_portable/emscripten/incoming/emcc.py", line 1323, in compile_source_file
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "/Users/johann/emsdk_portable/emscripten/incoming/emcc.py", line 1306, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "/Users/johann/emsdk_portable/emscripten/incoming/tools/system_libs.py", line 636, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "/Users/johann/emsdk_portable/emscripten/incoming/tools/ports/binaryen.py", line 34, in process_args
    get(ports, settings, shared)
  File "/Users/johann/emsdk_portable/emscripten/incoming/tools/ports/binaryen.py", line 29, in get
    return [shared.Cache.get('binaryen_tag_' + TAG, create, what='port', extension='.txt')]
  File "/Users/johann/emsdk_portable/emscripten/incoming/tools/cache.py", line 95, in get
    temp = creator()
  File "/Users/johann/emsdk_portable/emscripten/incoming/tools/ports/binaryen.py", line 24, in create
    ports.build_native(os.path.join(ports.get_dir(), 'binaryen', 'binaryen-' + TAG))
  File "/Users/johann/emsdk_portable/emscripten/incoming/tools/system_libs.py", line 607, in build_native
    subprocess.check_call(['cmake', '--build', '.'] + make_args, env=env)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2
```

</p></details>

With the built-in AppleClang (I commented out this section https://github.com/kripken/emscripten/blob/incoming/tools/shared.py#L1185 ) it works fine.

Anything I'm doing wrong? :)

**Comment by kripken** [comment]
No, you're doing it right, we have a known bug there that we are still working on, I'm afraid: https://github.com/WebAssembly/binaryen/issues/822

**Comment by johannhof** [comment]
Oh, I must have missed that issue on binaryen. I'll try your proposed solution from #4734.

Thanks!

**Comment by kripken** [comment]
Ok, let's close this in favor of that issue.
