### ISSUE TITLE
Permission error while building on MacOS

### ISSUE THREAD

**Issue by akatechis** [kripken/emscripten#4745]
```
$ emsdk install sdk-incoming-64bit
Installing SDK 'sdk-incoming-64bit'..
Installing tool 'clang-incoming-64bit'..
Repository 'https://github.com/kripken/emscripten-fastcomp/' already cloned to directory '/Users/alex/emsdk_portable/clang/fastcomp/src', skipping.
Fetching latest changes to the branch 'incoming' for '/Users/alex/emsdk_portable/clang/fastcomp/src'...
Already up-to-date.
Successfully updated and checked out branch 'incoming' on repository '/Users/alex/emsdk_portable/clang/fastcomp/src'
Current repository version: "Thu, 10 Nov 2016 16:55:54 -0800 dfcb07a871addf339ffac17e606e16e97e8c5f71"
Repository 'https://github.com/kripken/emscripten-fastcomp-clang/' already cloned to directory '/Users/alex/emsdk_portable/clang/fastcomp/src/tools/clang', skipping.
Fetching latest changes to the branch 'incoming' for '/Users/alex/emsdk_portable/clang/fastcomp/src/tools/clang'...
Already up-to-date.
Successfully updated and checked out branch 'incoming' on repository '/Users/alex/emsdk_portable/clang/fastcomp/src/tools/clang'
Current repository version: "Thu, 3 Nov 2016 12:23:18 -0700 b6ea91778b2b30e6746f2a5f2baba463948729a4"
Running CMake: ['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '/Users/alex/emsdk_portable/clang/fastcomp/src']
Traceback (most recent call last):
  File "/Users/alex/emsdk_portable/emsdk", line 1797, in <module>
    sys.exit(main())
  File "/Users/alex/emsdk_portable/emsdk", line 1780, in main
    success = tool.install()
  File "/Users/alex/emsdk_portable/emsdk", line 1061, in install
    success = tool.install()
  File "/Users/alex/emsdk_portable/emsdk", line 1070, in install
    success = build_fastcomp_tool(self)
  File "/Users/alex/emsdk_portable/emsdk", line 638, in build_fastcomp_tool
    success = cmake_configure(cmake_generator, build_root, fastcomp_src_root, build_type, args)
  File "/Users/alex/emsdk_portable/emsdk", line 584, in cmake_configure
    ret = subprocess.check_call(cmdline, cwd=build_root)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by akatechis** [comment]
Closing this, since it was my issue. I had forgotten to actually install CMake (doh)

**Comment by Pyrolistical** [comment]
well, the error message could be a bit more helpful
