### ISSUE TITLE
Embind test "no undefined entry in overload table for free functions" fails

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4787]
Running `other.test_embind` after PR #3450 is merged fails with the following:

    embind: no undefined entry in overload table for free functions: FAIL

    TypeError: Cannot read property 'hasOwnProperty' of undefined
        at Object.<anonymous> (c:\users\clb\appdata\local\temp\emscripten_test_other_9_59vs\a.out.js:141147:32)
        at runTest (c:\users\clb\appdata\local\temp\emscripten_test_other_9_59vs\a.out.js:139715:23)
        at run_all (c:\users\clb\appdata\local\temp\emscripten_test_other_9_59vs\a.out.js:139735:26)
        at run_all_tests (c:\users\clb\appdata\local\temp\emscripten_test_other_9_59vs\a.out.js:140242:5)
        at Object.<anonymous> (c:\users\clb\appdata\local\temp\emscripten_test_other_9_59vs\a.out.js:142857:5)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:475:10)
    error: [TypeError: Cannot read property 'hasOwnProperty' of undefined]

@AlexPerrot : does that reproduce for you?

**Comment by AlexPerrot** [comment]
Woops, I forgot to add the bindings for the free functions to test.
You'll find the fix in #4788 
I properly tested it this time, all tests in `other.test_embind` are passing for me.

**Comment by AlexPerrot** [comment]
@juj @azakai The embind test are OK for me on latest incoming, so I think this can be closed

**Comment by kripken** [comment]
Yes, thanks.
