### ISSUE TITLE
binaryen port failing to compile on windows

### ISSUE THREAD

**Issue by sheldon** [kripken/emscripten#4821]
Hi

I'm trying to compile some a rust hello world into wasm32 and running into trouble compiling the binaryen port.

I'm on the 1.37.1 tag of emscripten, compiled from source, on windows 10 using Microsoft Visual C++ Build Tools 2015 as a compiler.

I noticed there's some mention of cmake in https://github.com/kripken/emscripten/issues/4207, not sure if that's relevant as the code patch looks good to me.

```
PS C:\Users\Sheldon\Downloads\hello_rust_emscripten> cargo rustc --verbose --target=wasm32-unknown-emscripten -- -C linker=emcc.bat
   Compiling hello_rust_emscripten v0.1.0 (file:///C:/Users/Sheldon/Downloads/hello_rust_emscripten)
     Running `rustc src\main.rs --crate-name hello_rust_emscripten --crate-type bin -g -C linker=emcc.bat -C metadata=959c6ce9e63f1554 --out-dir C:\Users\Sheldon\Downloads\hello_rust_emscripten\target\wasm32-unknown-emscripten\debug --emit=dep
-info,link --target wasm32-unknown-emscripten -L dependency=C:\Users\Sheldon\Downloads\hello_rust_emscripten\target\wasm32-unknown-emscripten\debug\deps`
error: linking with `emcc.bat` failed: exit code: 1
  |
  = note: "emcc.bat" "-L" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "C:\\Users\\Sheldon\\Downloads\\hello_rust_emscripten\\target\\wasm32-unknown-emscripten\\debug\\h
ello_rust_emscripten.0.o" "-o" "C:\\Users\\Sheldon\\Downloads\\hello_rust_emscripten\\target\\wasm32-unknown-emscripten\\debug\\hello_rust_emscripten.js" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\Sheldon\\Downloads\\hello_rust_emsc
ripten\\target\\wasm32-unknown-emscripten\\debug\\deps" "-L" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\Users\\Sheldon\\.rustup\\to
olchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libstd-610aec1c0c2edd5b.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libpani
c_unwind-f2d5dd75c5a64c5f.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libunwind-cce8009dda26867d.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-
windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librand-d2f56491199d3b9f.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcollections-4f02fd86535a3157.r
lib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librustc_unicode-8d6c34ad46f07f91.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\r
ustlib\\wasm32-unknown-emscripten\\lib\\liballoc-198f48436646c796.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liballoc_system-22e63f2ceba0e6f8.rlib" "C:\\Users\\S
heldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liblibc-9b19cb4b417215a8.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emsc
ripten\\lib\\libcore-ec0461203eec19c8.rlib" "C:\\Users\\Sheldon\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcompiler_builtins-ad8606f391af463e.rlib" "-l" "c" "-s" "BINARYEN=1" "-s" "ERR
OR_ON_UNDEFINED_SYMBOLS=1"
  = note: INFO:root:generating port: binaryen_tag_version_21.txt... (this will be cached in "C:\Users\Sheldon\.emscripten_cache\asmjs\binaryen_tag_version_21.txt" for subsequent builds)
INFO:root:building port: binaryen
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/Sheldon/.emscripten_ports/binaryen/binaryen-version_21/CMakeFiles/CMakeTmp



  Run Build Command:"nmake" "/NOLOGO" "cmTC_028c8\fast"

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" -f
  CMakeFiles\cmTC_028c8.dir\build.make /nologo -L
  CMakeFiles\cmTC_028c8.dir\build

  Building C object CMakeFiles/cmTC_028c8.dir/testCCompiler.c.obj

        C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe
  @C:\Users\Sheldon\AppData\Local\Temp\nmAF8.tmp

  testCCompiler.c

  Linking C executable cmTC_028c8.exe

        "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe
  --intdir=CMakeFiles\cmTC_028c8.dir --manifests --
  C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo
  @CMakeFiles\cmTC_028c8.dir\objects1.rsp
  @C:\Users\Sheldon\AppData\Local\Temp\nmC31.tmp

  RC Pass 1 failed to run.

  NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' :
  return code '0xffffffff'

  Stop.

  NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio
  14.0\VC\bin\nmake.exe"' : return code '0x2'

  Stop.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (PROJECT)


ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\master\\emcc", line 13, in <module>
    emcc.run()
  File "C:\Program Files\Emscripten\emscripten\master\emcc.py", line 1492, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "C:\Program Files\Emscripten\emscripten\master\tools\system_libs.py", line 620, in get_ports
    ret += filter(lambda f: not f.endswith('.txt'), port.get(Ports, settings, shared))
  File "C:\Program Files\Emscripten\emscripten\master\tools\ports\binaryen.py", line 29, in get
    return [shared.Cache.get('binaryen_tag_' + TAG, create, what='port', extension='.txt')]
  File "C:\Program Files\Emscripten\emscripten\master\tools\cache.py", line 95, in get
    temp = creator()
  File "C:\Program Files\Emscripten\emscripten\master\tools\ports\binaryen.py", line 24, in create
    ports.build_native(os.path.join(ports.get_dir(), 'binaryen', 'binaryen-' + TAG))
  File "C:\Program Files\Emscripten\emscripten\master\tools\system_libs.py", line 596, in build_native
    subprocess.check_call(['cmake', '-DCMAKE_BUILD_TYPE=' + cmake_build_type, '.'])
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '.']' returned non-zero exit status 1
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
-- Configuring incomplete, errors occurred!
See also "C:/Users/Sheldon/.emscripten_ports/binaryen/binaryen-version_21/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Sheldon/.emscripten_ports/binaryen/binaryen-version_21/CMakeFiles/CMakeError.log".


error: aborting due to previous error

error: Could not compile `hello_rust_emscripten`.

Caused by:
  process didn't exit successfully: `rustc src\main.rs --crate-name hello_rust_emscripten --crate-type bin -g -C linker=emcc.bat -C metadata=959c6ce9e63f1554 --out-dir C:\Users\Sheldon\Downloads\hello_rust_emscripten\target\wasm32-unknown-emsc
ripten\debug --emit=dep-info,link --target wasm32-unknown-emscripten -L dependency=C:\Users\Sheldon\Downloads\hello_rust_emscripten\target\wasm32-unknown-emscripten\debug\deps` (exit code: 101)
PS C:\Users\Sheldon\Downloads\hello_rust_emscripten>
```

Any help greatly appreciated.

**Comment by kripken** [comment]
I don't know much about windows, but I think the core error is `The C compiler "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" is not able to compile a simple test program`. Maybe visual studio isn't set up properly to be used on the commandline? Or maybe cmake isn't invoking it properly?

**Comment by sheldon** [comment]
Yeah, I saw the same. Initially I had pathing troubles, but the output above was after I added cl.exe into the path.

I managed to install emscripten from source using this same compiler setup, even without the manual path hacking. I had to install cmake to get that compile working, so I'm pretty confident the compiler works in general, and cmake knows how to use it (even without any special pathing).

Perhaps something about emscripten's own compilation setup in cmake is different from the binaryen one, but I'm afraid I'm too much of a noob to all these things to find the difference.

Happy to try anything to debug if someone can point me in the right direction.

**Comment by kripken** [comment]
Hmm, that reminds me we had such an issue, where emcc's invocation of cmake was wrong. But it was fixed before 1.37.1 which you said you are on.

One option is you can try to build binaryen yourself, it will be in something like `~/.emscripten_ports/binaryen/binaryen-version_22/`, so going there and doing `cmake` and `make` (or windows equivalent) could work. If it does, this might work around the issue, as it shouldn't try to rebuild it again.

**Comment by dschuff** [comment]
I think in order to run cmake you need to do it from the visual studio developer command prompt, which injects more stuff into your envrionment than just path to the executables. I don't think the command line `cl.exe` will really work properly without that. (the `vcvars*.bat` files do the equivalent environment stuff for an existing shell instance).

**Comment by ctaggart** [comment]
@kripken I got stuck too on Windows with it complaining about binaryen. It looks like there may some

```
C:\Users\c\.emscripten_ports\binaryen\binaryen-version_23>cmake --build . -- -j 8
NMAKE : fatal error U1065: invalid option 'j'
Stop.
```

For me, `rustc` is trying to invoke `emcc` when this error occurs.
```
rustc --target=wasm32-unknown-emscripten hello.rs -o hello.html -C linker=emcc.bat > build.txt 2>&1
```
build.txt:
```
error: linking with `emcc.bat` failed: exit code: 1
  |
  = note: "emcc.bat" "-L" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "hello.0.o" "-o" "hello.html" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libstd-610aec1c0c2edd5b.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libpanic_unwind-f2d5dd75c5a64c5f.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libunwind-cce8009dda26867d.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librand-d2f56491199d3b9f.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcollections-4f02fd86535a3157.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\librustc_unicode-8d6c34ad46f07f91.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liballoc-198f48436646c796.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liballoc_system-22e63f2ceba0e6f8.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\liblibc-9b19cb4b417215a8.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcore-ec0461203eec19c8.rlib" "C:\\Users\\c\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\libcompiler_builtins-ad8606f391af463e.rlib" "-l" "c" "-s" "BINARYEN=1" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
  = note: WARNING:root:retrieving port: binaryen from https://github.com/WebAssembly/binaryen/archive/version_23.zip
WARNING:root:unpacking port: binaryen
INFO:root:generating port: binaryen_tag_version_23.txt... (this will be cached in "C:\Users\c\.emscripten_cache\asmjs\binaryen_tag_version_23.txt" for subsequent builds)
INFO:root:building port: binaryen
NMAKE : fatal error U1065: invalid option 'j'
Stop.
ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again
Traceback (most recent call last):
  File "C:\emscripten\emscripten\incoming\\emcc", line 13, in <module>
    emcc.run()
  File "C:\emscripten\emscripten\incoming\emcc.py", line 1512, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "C:\emscripten\emscripten\incoming\tools\system_libs.py", line 620, in get_ports
    ret += filter(lambda f: not f.endswith('.txt'), port.get(Ports, settings, shared))
  File "C:\emscripten\emscripten\incoming\tools\ports\binaryen.py", line 29, in get
    return [shared.Cache.get('binaryen_tag_' + TAG, create, what='port', extension='.txt')]
  File "C:\emscripten\emscripten\incoming\tools\cache.py", line 95, in get
    temp = creator()
  File "C:\emscripten\emscripten\incoming\tools\ports\binaryen.py", line 24, in create
    ports.build_native(os.path.join(ports.get_dir(), 'binaryen', 'binaryen-' + TAG))
  File "C:\emscripten\emscripten\incoming\tools\system_libs.py", line 608, in build_native
    subprocess.check_call(['cmake', '--build', '.'] + make_args)
  File "C:\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2
-- Building for: NMake Makefiles
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building with /wd4146
-- Building with /WX-
-- Building with /O2
-- Building with -D_CRT_SECURE_NO_WARNINGS
-- Building with -D_SCL_SECURE_NO_WARNINGS
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/c/.emscripten_ports/binaryen/binaryen-version_23


error: aborting due to previous error
```

From `(['cmake', '--build', '.'] + make_args)` it looks like `make_args` are probably set wrong. If I do a `cmake --build .` in that folder, it does build, but I'm not sure how to use it or what the rest of a manual work-a-round would be.

**Comment by ctaggart** [comment]
In my case, it looks like the generator ends up being `NMake Makefiles`. Is there a away for me to configure `emcc` so that the generator is `Visual Studio 14 2015 Win64` via environment variables or options?

https://github.com/kripken/emscripten/blob/master/tools/system_libs.py#L599-L605
``` py
      # Check which CMake generator CMake used so we know which form to pass parameters to make/msbuild/etc. build tool.
      generator = re.search('CMAKE_GENERATOR:INTERNAL=(.*)$', open('CMakeCache.txt', 'r').read(), re.MULTILINE).group(1)

      # Make variants support '-jX' for number of cores to build, MSBuild does /maxcpucount:X
      num_cores = os.environ.get('EMCC_CORES') or str(multiprocessing.cpu_count())
      make_args = []
      if 'Makefiles' in generator: make_args = ['--', '-j', num_cores]
      elif 'Visual Studio' in generator: make_args = ['--config', cmake_build_type, '--', '/maxcpucount:' + num_cores]
```

**Comment by juj** [comment]
Yeah, the generator should not end up being NMake Makefiles on Windows, but it should be Visual Studio 2015. I'm not sure why it doesn't go that way. CMake autodetects the compiler, and on Windows I think it looks up Visual Studio from the VSINSTALLDIR and VCINSTALLDIR environment variables, so you should not need to be in Visual Studio Command Prompt (although should be able to use that to override your desired flavor, 32 vs 64 bit etc)

Although I don't think there should be a fundamental issue why NMake couldn't be used to drive the build, as long as NMake is able to find cl.exe. Pushed the above commit to at least fix the problem that -jX is attempted to be passed to NMake.

Can you try running the following set of commands:

    git clone https://github.com/juj/emsdk.git
    cd emsdk
    emsdk install binaryen-master-64bit

Does that successfully build Binaryen?

**Comment by ctaggart** [comment]
@juj, yes that does successfully build Binaryen. It is actually working for me from master too, so my problem appears to be solved. I'm not sure which change did it, but I see `['cmake', '-G', 'Visual Studio 14 Win64'` now. On this laptop, where I had the problem, I only have the [Visual C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools) installed.

**Comment by gouletr** [comment]
@juj For me that command fails with:
```
d:\dev\emsdk>emsdk install binaryen-master-64bit
Error: No tool or SDK found by name 'binaryen-master-64bit'.
```
am I missing something?

**Comment by its2mc** [comment]
Same thing with me.. and I am on linux
Ubuntu 16.4 to be precise..

**Comment by its2mc** [comment]
/Documents/git/emsdk$ emsdk install binaryen-master-64bit
Error: No tool or SDK found by name 'binaryen-master-64bit'.

Heres a screen shot of my error.

**Comment by juj** [comment]
If you have bootstrapped emsdk via a `git clone`, then `binaryen-master-64bit` should be present. However there has existed a particular footgun where if one types `emsdk update` on a git bootstrapped repository, it will overwrite the git repository to latest stable release, which is generally older. Authored https://github.com/juj/emsdk/commit/836d2ce941e8d6ec2bc92222629114752c2327d0 to remove that source of error.

@gouletr, @its2mc : try doing `git status -uno` in the emsdk directory. If that shows that the file `emsdk` appears to have local changes, then the above overwrite has occurred. In that case, run `git clean` to undo the local changes, and then `git pull` to update to newest version. After the above commit, that confusion should no longer be possible. Sorry for this particular UX issue, the workflow was very confusing here earlier!

**Comment by juj** [comment]
@sheldon : tried to reproduce the root issue, but was unable to get it to manifest in current incoming branch, so perhaps it was resolved since? `python embuilder.py build binaryen` runs fine (in emsdk, one needs to remove line `BINARYEN_ROOT='foo'` in `.emscripten` file before running that)

**Comment by sheldon** [comment]
Hey @juj 

Admittedly I haven't tried in a while, so if attempts to reproduce are passing now I'd be ok to close this out. I'm afraid I'm putting my energy elsewhere at the moment, so I won't have the chance to retest again soon.

Thanks for the efforts in trying to resolve. If I do come back to it and have trouble I'll open a new bug 👍
