### ISSUE TITLE
exec makem.js error

### ISSUE THREAD

**Issue by Sirormy** [kripken/emscripten#4823]
when I run this:
```bash
sudo node makem.js
```

It build for a while, and report the error,  I tried :

```
EMCC_DEBUG=1
sudo emcc --clear-cache
```

And it`s not  worked. How do I fix this?

```
Running command: /usr/local/Cellar/emscripten/1.36.14/bin/emcc -I/Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/include -I/Users/Sirormy/Dev/git/jsartoolkit5/build/ -I/Users/Sirormy/Dev/git/jsartoolkit5/emscripten/ /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/lib/SRC/AR/arLabelingSub/*.c /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/lib/SRC/AR/*.c /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/lib/SRC/ARICP/*.c /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/lib/SRC/ARMulti/*.c /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/lib/SRC/Gl/gsub_lite.c -Oz  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s NO_BROWSER=1  --memory-init-file 0  --bind    -o /Users/Sirormy/Dev/git/jsartoolkit5/build/libar.bc

stderr: WARNING:root:Assigning a non-existent settings attribute "NO_BROWSER"
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)


Running command: /usr/local/Cellar/emscripten/1.36.14/bin/emcc -I/Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/include -I/Users/Sirormy/Dev/git/jsartoolkit5/build/ -I/Users/Sirormy/Dev/git/jsartoolkit5/emscripten/  /Users/Sirormy/Dev/git/jsartoolkit5/build/*.bc /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/ARToolKitJS.cpp -Oz  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s NO_BROWSER=1  --memory-init-file 0  --bind   -g  -s ASSERTIONS=1  -s ALLOW_MEMORY_GROWTH=1  -s DEMANGLE_SUPPORT=1   -o /Users/Sirormy/Dev/git/jsartoolkit5/build/artoolkit.debug.js

stderr: WARNING:root:Assigning a non-existent settings attribute "NO_BROWSER"
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
INFO:root:generating system library: libcxx_noexcept.a... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/libcxx_noexcept.a" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxxabi.bc... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/libcxxabi.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
INFO:root: - ok
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/1.36.14/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1875, in run
    JSOptimizer.flush()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1771, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1744, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/shared.py", line 1810, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/js_optimizer.py", line 559, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/js_optimizer.py", line 559, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/js_optimizer.py", line 451, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory

exec error: Error: Command failed: /usr/local/Cellar/emscripten/1.36.14/bin/emcc -I/Users/Sirormy/Dev/git/jsartoolkit5/emscripten/artoolkit5/include -I/Users/Sirormy/Dev/git/jsartoolkit5/build/ -I/Users/Sirormy/Dev/git/jsartoolkit5/emscripten/  /Users/Sirormy/Dev/git/jsartoolkit5/build/*.bc /Users/Sirormy/Dev/git/jsartoolkit5/emscripten/ARToolKitJS.cpp -Oz  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s NO_BROWSER=1  --memory-init-file 0  --bind   -g  -s ASSERTIONS=1  -s ALLOW_MEMORY_GROWTH=1  -s DEMANGLE_SUPPORT=1   -o /Users/Sirormy/Dev/git/jsartoolkit5/build/artoolkit.debug.js
WARNING:root:Assigning a non-existent settings attribute "NO_BROWSER"
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
INFO:root:generating system library: libcxx_noexcept.a... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/libcxx_noexcept.a" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxxabi.bc... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/libcxxabi.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/Users/Sirormy/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
INFO:root: - ok
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/1.36.14/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1875, in run
    JSOptimizer.flush()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1771, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1744, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/shared.py", line 1810, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/js_optimizer.py", line 559, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/js_optimizer.py", line 559, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/tools/js_optimizer.py", line 451, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
```

**Comment by Sirormy** [comment]
remove "EMSCRIPTEN_NATIVE_OPTIMIZER" from ~/.emscripten fixed this.
