### ISSUE TITLE
EMTERPRETIFY_ASYNC doesn't work

### ISSUE THREAD

**Issue by tbodt** [kripken/emscripten#5123]
Test program:

```c
#include <emscripten.h>
int main() {
    emscripten_sleep(1);
}
```

Output:

```
/Users/tbodt/Developer/github/tbodt/qemu.js/emscripten/gettext-0.19.8/gettext-tools/a.out.js:110
      throw ex;
      ^

TypeError: asm.emtStackSave is not a function
    at Object.callMain (a.out.js:6551:32)
    at doRun (a.out.js:6617:60)
    at run (a.out.js:6631:5)
    at Object.<anonymous> (a.out.js:6708:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

Compiled with `emcc test.c -s EMTERPRETIFY_ASYNC=1`

**Comment by satoshinm** [comment]
I think you need to enable EMTERPRETIFY (https://github.com/kripken/emscripten/wiki/Emterpreter) with EMTERPRETIFY_ASYNC? This works for me:

```sh
emcc test.c -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1
```

**Comment by kripken** [comment]
Yes, that's the issue. I added an error now, so if you just do `EMTERPRETIFY_ASYNC` it will tell that it requires `EMTERPRETIFY`.
