### ISSUE TITLE
emc++ fails to generate wasm.

### ISSUE THREAD

**Issue by mseddon** [kripken/emscripten#5270]
I have `emcc` compiling a hello world c program to wasm perfectly fine.

Now I turn to testing `emc++`.  I create the unremarkable `main.cpp`:

```c
#include <iostream>

int main(int argc, char *argv[]) {
    std::cout << "Hello world";
}
```
Version info:
```
em++ -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp.git 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-pc-windows-msvc
Thread model: posix
INFO:root:(Emscripten: Running sanity checks)
```

And invoke emscripten: `em++ main.cpp -Oz -s WASM=1`

This fails:

```
build executables
save the before js
process input
run polyfill packer on a.out.js.temp2.js

C:\Users\Matt\.emscripten_cache\pack-asmjs.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverride
s[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&
&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if
(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](fil
ename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filen
Assertion failed: u.u32_ > INT32_MAX, at: C:\Program Files\Emscripten\emscripten\1.35.0\third_party\wasm-polyfill\src\pack-asmjs.cpp,1268,NumLit at Error
    at jsStackTrace (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:1:20862)
    at stackTrace (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:1:21045)
    at ___assert_fail (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:1:103537)
    at Rb (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:1981)
    at ac (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:38093)
    at lc (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:54597)
    at mc (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:55910)
    at ac (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:40156)
    at mc (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:56132)
    at nc (C:\Users\Matt\.emscripten_cache\pack-asmjs.js:12:58798)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\third_party\wasm-polyfill\wasmator.py", line 94, in <module>
    out = emscripten.run_js(pack_asmjs, args=[os.path.basename(tempfile2), 'output.binary'], stdout=PIPE)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\shared.py", line 868, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['C:/Program Files/Emscripten/node/4.1.1_64bit/bin/node.exe', 'C:\\Users\\Matt\\.emscripten_cache\\pack-asmjs.js', 'a.out.js.temp2.js', 'output.binary'] to finish with return code 0, but it return
ed with code 7 instead! Output:
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\emcc", line 1835, in <module>
    subprocess.check_call([shared.PYTHON, shared.path_from_root('third_party', 'wasm-polyfill', 'wasmator.py'), js_target, wasm_target, shared.Settings.EXPORT_NAME])
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/Program Files/Emscripten/python/2.7.5.3_64bit/python.exe', 'C:\\Program Files\\Emscripten\\emscripten\\1.35.0\\third_party\\wasm-polyfill\\wasmator.py', 'a.out.js', 'a.out.wasm', u'Mo
dule']' returned non-zero exit status 1
```

I notice this failure is identical to https://github.com/kripken/emscripten/issues/3855, down to the stack trace, but this appears to be blocking me from using WASM=1 and C++ *entirely*, at least on this machine, so I am unsure if this is actually a duplicate,  or something more serious triggering the same error.

**Comment by mseddon** [comment]
As an update- I've tried this on another Windows 10 machine with the same result.

**Comment by kripken** [comment]
1.35.0 is too old a version of emscripten, wasm support was not yet mature enough yet. (In particular, `run polyfill packer` is an old and obsoleted method of converting to wasm.) I'd recommend updating to the current `incoming` branch.

**Comment by mseddon** [comment]
Oh! I was using the installer on the website, thanks for the heads up, I will try `incoming` instead.

**Comment by juj** [comment]
Sorry about that - we have recently deprecated the NSIS installers on Windows because vs-tool is no longer a supported project and there has been little value to having a special .exe installer. Updated the documentation at https://github.com/kripken/emscripten/pull/5275/files to remove references to those.

**Comment by mseddon** [comment]
Thanks, that'll hopefully steer people away from making the same mistake!
