### ISSUE TITLE
other.test_binaryen_names failure

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#5307]
Running on `incoming` with binaryen `master` branch on Linux Mint 18, I'm seeing

```bash
$ python tests/runner.py other.test_binaryen_names
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_other']
Running test_other: (1 tests)
test_binaryen_names (test_other.other) ... [] False
['-g'] True
['-O1'] False
calling $27 resulted in (i32.const 0) but the function type is 0
exception thrown: 0

/dev/shm/tmp/emscripten_test_other_gxiH4K/a.out.js:149
      throw ex;
      ^
0
ERROR

======================================================================
ERROR: test_binaryen_names (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/clb/emsdk/emscripten/incoming/tests/test_other.py", line 7348, in test_binaryen_names
    self.assertContained('hello, world!', run_js('a.out.js'))
  File "/home/clb/emsdk/emscripten/incoming/tools/shared.py", line 1061, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "/home/clb/emsdk/emscripten/incoming/tools/jsrun.py", line 128, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/home/clb/emsdk/node/4.1.1_64bit/bin/node', 'a.out.js'] to finish with return code 0, but it returned with code 7 instead! Output: hello, world!

----------------------------------------------------------------------
Ran 1 test in 6.904s

FAILED (errors=1)
```

@kripken , does this reproduce for you?

**Comment by kripken** [comment]
That was a problem with an earlier interpreter, but on incoming it should use a new enough one. Is that fully updated incoming? which binaryen tag is it getting - should be 33?

**Comment by juj** [comment]
Oops, sorry about the noise, I notice I had had local changes in Binaryen tree which is why I was stuck at older version when updating. Cleaning that up and running `incoming` against latest `master` fixes the run. Thanks!
