### ISSUE TITLE
Error while running source /usr/lib/emsdk/emsdk_env.sh on linux

### ISSUE THREAD

**Issue by BrieucP** [kripken/emscripten#5334]
I installed emsdk from aur on Archlinux, then the sdk-incoming-64bit but when I run source ./usr/lib/emsdk_env.sh I got the following output

```
source /usr/lib/emsdk/emsdk_env.sh
Traceback (most recent call last):
  File "./emsdk", line 2198, in <module>
    sys.exit(main())
  File "./emsdk", line 1852, in main
    if len(sys.argv) <= 1 or sys.argv[1] == 'help' or sys.argv[1] == '--help':
TypeError: object of type 'filter' has no len()
/usr/lib/emsdk/emsdk_env.sh:.:26: aucun fichier ou dossier de ce type: ./emsdk_set_env.sh

```

**Comment by gogoprog** [comment]
This is related to emsdk and should be closed, see your own issue :
https://github.com/juj/emsdk/issues/83
