### ISSUE TITLE
Difficulties with tools/gen_struct_info.py

### ISSUE THREAD

**Issue by nazar-pc** [kripken/emscripten#5495]
I've tried to use this script for defines, but got some issues.
The first one was following:
```
Traceback (most recent call last):
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 524, in <module>
    main(sys.argv[1:])
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 517, in main
    defines.extend(data['defines'])
AttributeError: 'dict' object has no attribute 'extend'
```
When I've changed `dict` to `list` I've got following:
```
Traceback (most recent call last):
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 525, in <module>
    main(sys.argv[1:])
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 521, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 346, in inspect_code
    for name, type_ in defines.items():
AttributeError: 'list' object has no attribute 'items'
```

As Python is not the language I know, can't fix it myself.
@ngld, maybe you can help with this as the author of original PR that introduced this script?

The source files I'm trying to extract defines from: https://github.com/rweather/noise-c/blob/6243290cf66b6b518ed0c0ca91b54a1ec68f6b78/include/noise/protocol/constants.h

**Comment by nazar-pc** [comment]
I've end up creating wrapper function where necessary. Feel free to reopen if feel necessary.
