### ISSUE TITLE
Compiling error on macOS

### ISSUE THREAD

**Issue by orklann** [kripken/emscripten#5550]
emcc version on macOS 10.12
```
emcc (Emscripten gcc/clang-like replacement) 1.37.18 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Compiling command:
```
emcc -O3 -s WASM=1 -s SIDE_MODULE=1 a.c -o a.wasm
```

Error output:
```
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.37.18/libexec/emcc.py", line 1785, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/usr/local/Cellar/emscripten/1.37.18/libexec/emcc.py", line 2256, in do_binaryen
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

`a.c` is in the current directory, and it's a simple c function.

Need some help.

**Comment by orklann** [comment]
Solved after munally install binaryen and correct the path in `~/.emscripten`
