### ISSUE TITLE
Exception in thread Thread-3

### ISSUE THREAD

**Issue by stolk** [kripken/emscripten#5551]
I installed emscripten that is bundled with ubuntu: 1.22.1-1build1

When I compile my source code, it works.
But if I then link, I get a Python exception.

```
bram@ubuntu64:~/apps/Smatch/JS$ emcc --version
emcc (Emscripten GCC-like replacement) 1.22.1 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
bram@ubuntu64:~/apps/Smatch/JS$ make
em++ -DJS -DLANDSCAPE -D_POSIX_C_SOURCE=199309L -I/home/bram/src/stb/ -I/home/bram/src/dutch-blunt/src -I/home/bram/apps/GBase/src -I../PI -g -Wall -Wno-missing-braces -Wno-unknown-pragmas -MMD -MP -O2 -Wno-warn-absolute-paths -std=c++11 -o bin/smatch.html  src/main.cpp \
-L. \
-lpi -ldblunt -lbase \
--preload-file ../Sounds@ \
--preload-file ../Art@ \
-s TOTAL_MEMORY=33554432 \

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

```

My emscripten settings:
```

# Note: If you put paths relative to the home directory, do not forget os.path.expanduser

import os

# this helps projects using emscripten find it
EMSCRIPTEN_ROOT = os.path.expanduser(os.getenv('EMSCRIPTEN') or '/home/bram/src/emscripten') # directory
LLVM_ROOT = os.path.expanduser(os.getenv('LLVM') or '/usr/bin') # directory
LLVM_ADD_VERSION = "3.8"
PYTHON = os.path.expanduser(os.getenv('PYTHON') or '/usr/bin/python2') # executable

# See below for notes on which JS engine(s) you need
NODE_JS = os.path.expanduser(os.getenv('NODE') or '/usr/bin/nodejs') # executable
SPIDERMONKEY_ENGINE = [os.path.expanduser(os.getenv('SPIDERMONKEY') or 'js')] # executable
V8_ENGINE = os.path.expanduser(os.getenv('V8') or 'd8') # executable

JAVA = 'java' # executable

TEMP_DIR = '/tmp'

CRUNCH = os.path.expanduser(os.getenv('CRUNCH') or 'crunch') # executable

#CLOSURE_COMPILER = '..' # define this to not use the bundled version

########################################################################################################


# Pick the JS engine to use for running the compiler. This engine must exist, or
# nothing can be compiled.
#
# Recommendation: If you already have node installed, use that. Otherwise, build v8 or
#                 spidermonkey from source. Any of these three is fine, as long as it's
#                 a recent version (especially for v8 and spidermonkey).

COMPILER_ENGINE = NODE_JS
#COMPILER_ENGINE = V8_ENGINE
#COMPILER_ENGINE = SPIDERMONKEY_ENGINE


# All JS engines to use when running the automatic tests. Not all the engines in this list
# must exist (if they don't, they will be skipped in the test runner).
#
# Recommendation: If you already have node installed, use that. If you can, also build
#                 spidermonkey from source as well to get more test coverage (node can't
#                 run all the tests due to node issue 1669). v8 is currently not recommended
#                 here because of v8 issue 1822.

JS_ENGINES = [NODE_JS] # add this if you have spidermonkey installed too, SPIDERMONKEY_ENGINE]

TOTAL_MEMORY = 128*1024*1024

```

**Comment by stolk** [comment]
Seems related to #2697 which has the same error message.
According to that discussion, Ubuntu package is to blaim.

**Comment by stolk** [comment]
Ok, I uninstalled emscripten, and used the emsdk instead.
This works.
So I guess the lesson learned here is: don't use the packages provided by Ubuntu.
Maybe warn against it, in the docs?
