### ISSUE TITLE
Can't build with -s WASM=1 : thinks that SIMD is being used

### ISSUE THREAD

**Issue by mchiasson** [kripken/emscripten#5561]
I'm on Emscripten 1.37.21 and ported one of our product, Works fine, but then I tried to compile it in WebAssembly, and I am getting this assertion
```
Traceback (most recent call last):
  File "/home/mchiasson/emsdk_portable/emscripten/tag-1.37.21/em++", line 16, in <module>
    emcc.run()
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/emcc.py", line 1534, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/tools/shared.py", line 2020, in emscripten
    call_emscripten(cmdline)
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/emscripten.py", line 2236, in _main
    temp_files.run_and_clean(lambda: main(
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/emscripten.py", line 2241, in <lambda>
    DEBUG=DEBUG,
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/emscripten.py", line 2141, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/emscripten.py", line 98, in emscript
    glue, forwarded_data = compiler_glue(metadata, settings, libraries, compiler_engine, temp_files, DEBUG)
  File "/mnt/storage/mchiasson/emsdk_portable/emscripten/tag-1.37.21/emscripten.py", line 219, in compiler_glue
    assert not (metadata['simd'] and settings['WASM']), 'SIMD is used, but not supported in WASM mode yet'
AssertionError: SIMD is used, but not supported in WASM mode yet
```

I'm currently using these compiler flags
```
-s USE_SDL=2 -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s FETCH=1 -s TOTAL_MEMORY=536870912 -s WASM=1
```
We are **not** doing any SIMD operations in our code, which is why this error is a bit confusing to us. Any idea?

**Comment by dschuff** [comment]
It's possible that the autovectorizer is creating some SIMD operations.
Emscripten has it disabled in a few places but maybe it's still doing
something. You could try adding -fno-vectorize to your CFLAGS.

**Comment by juj** [comment]
Try searching the codebase if anything with the LLVM attribute `__vector_size__` is getting compiled in. That is one way to get SIMD operations in the code even when one doesn't do any SIMD explicitly. See https://github.com/kripken/emscripten/blob/master/system/include/emscripten/vector.h#L18 for an example of a line that results in the generation of SIMD code.

**Comment by mchiasson** [comment]
Sorry, I found the issue. it is on my side. the SIMD symbols were coming from a static library that I cross-built manually (`libjpeg.bc`) which I forgot to re-compile it in WASM. You can close this issue.

**Comment by kripken** [comment]
Good, glad you found it.
