### ISSUE TITLE
`other.test_llvm_lit` fails, cannot find module `lit.main`

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten#5628]
```
$ python2 tests/runner.py other.test_llvm_lit
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_other']
Running test_other: (1 tests)
test_llvm_lit (test_other.other) ... ['/usr/bin/python2', '/home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/llvm-lit', '-v', '/home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/test/CodeGen/JS']
Traceback (most recent call last):
  File "/home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/llvm-lit", line 43, in <module>
    from lit.main import main
ImportError: No module named lit.main
FAIL

======================================================================
FAIL: test_llvm_lit (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saschanaz/emscripten/tests/test_other.py", line 3562, in test_llvm_lit
    assert p.returncode == 0, 'LLVM tests must pass with exit code 0'
AssertionError: LLVM tests must pass with exit code 0

----------------------------------------------------------------------
Ran 1 test in 0.082s

FAILED (failures=1)
```

**Comment by SaschaNaz** [comment]
`pip install lit` helped :smile:
