### ISSUE TITLE
Impossible to diagnose uglifyjs failures (JS_Parse_Error)

### ISSUE THREAD

**Issue by vvuk** [kripken/emscripten#5700]
Any code included with `--pre/post-js` gets run through Emscripten's uglifyjs.  This doesn't cope with lots of more modern JS, as is documented in other issues.  However, figuring out _why_ it fails is currently next to impossible.  Including some bit of modern JS will result in an error that looks a lot like this:

```
DEBUG:root:config forcing native optimizer at C:/proj/emsdk/clang/e1.37.21_64bit/optimizer.exe
splitting up js optimization into 2 chunks, using 2 cores  (total: 0.51 MB)
running cleanup on shell code

C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
        ^
TypeError: (intermediate value) is not a function
    at new JS_Parse_Error (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:261:21)
    at js_error (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:272:15)
    at croak (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:742:17)
    at token_error (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:749:17)
    at unexpected (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:755:17)
    at Object.semicolon (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:775:51)
    at prog1 (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:1314:29)
    at C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:879:40
    at block_ (C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:999:32)
    at C:\proj\emsdk\emscripten\1.37.21\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:978:43
Traceback (most recent call last):
  File "C:/proj/emsdk/emscripten/1.37.21/em++", line 16, in <module>
    emcc.run()
  File "C:\proj\emsdk\emscripten\1.37.21\emcc.py", line 1763, in run
    optimizer.flush()
  File "C:\proj\emsdk\emscripten\1.37.21\emcc.py", line 229, in flush
...
```

Note that there's zero information about where the error is happening, what file it's happening in, or even what line in one of Emscripten's temporaries it's happening in!  The `JS_Parse_Error` code in `parse-js.js` looks like it's supposed to report a line/col, but that `toString` isn't showing up in any output.

You can hack `js_error` to look like this to get a line/column, but even then you're going to be hunting for the file it's actually in.

```
function js_error(message, line, col, pos) {
  var p = new JS_Parse_Error(message, line, col, pos);
  process.stderr.write(p.toString());
  throw p;
};
```

One solution for now could be to do something like the above, but change the output to be of a form parseable by `emcc.py`; it can look for parse errors in stdout/stderr, and then print the actual error source and a few lines of context from the data it's currently processing.

**Comment by vvuk** [comment]
It doesn't actually help -- I mean it would, I guess, if I had any idea how to run uglify at that point :)  I hacked in what I suggested in the first comment and it actually works quite well.  I can't make a PR right now though because I did it directly in the emsdk-pulled `.py` files, so they weren't under git control (oops!).  I'll fix that when I'm on better internet than a train and send a PR.  With that change the error looks like this:

```
JS optimizer error:
Unexpected token: punc (:) (line: 4024, col: 17, pos: 162345)
Error context:
=======
ction(ptr) {
  var obj = Handler._map.get(ptr);
  if (obj) {
    return obj;
  }
  var shptr = _::Handler_shWrap(ptr);
  obj = Object.create(Handler.prototype);
  obj.shptr = shptr;
  obj.ptr = p
=======
```
This let me fix the problem (the bogus `::` in my generator)... I could do a proper `^` indicator too on the exact character, this is just 100 bytes of context on either side.

**Comment by kripken** [comment]
Nice, looking forward to the PR :)

About running uglify by itself, sorry, I should have been clearer, you can do that with `nodejs tools/js-optimizer.js [filename]`. Basically the js optimizer loads uglify to parse the input and emit the output (if more params are passed, it will run those as optimization passes; with just the input file, all it does is parsing and emitting).

**Comment by ThorstenBux** [comment]
@vvuk do you have the changes you made handy somewhere? Cause I have the exact same problem.

**Comment by ThorstenBux** [comment]
@kripken that is the way I made the uglifier print out something useful:

```
$EMSCRIPTEN_HOME/emscripten/1.37.22/tools/eliminator/node_modules/uglify-js/bin/uglifyjs [emscripten_temp]/emcc-2-pre-post.js
```

**Comment by kripken** [comment]
@vvuk ping, you said you had a PR for this?

**Comment by kripken** [comment]
I guess @vvuk doesn't have time for this. Added the help-wanted tag, would be great if someone could look into this.

At minimum we should probably add an entry to the FAQ about an error with `JS_Parse_Error` in it. But reading the discussion above, there might be more we can do. And perhaps we can print something helpful in the log after such an error.

**Comment by elHamil** [comment]
Hi all. I ran into the same problem, and fixed it with a quick&dirty hack. Sadly my employer wouldn't like me spending a lot of time polishing it up and turning it into a proper PR, but here is the hack just in case it helps anyone else:

In `\tools\eliminator\node_modules\uglify-js\lib\parse-js.js`, find the functions `JS_Parse_Error`, `js_error` and `croak` and change them to:

```
function JS_Parse_Error(message, line, col, pos) {
        this.message = message;
        this.line = line;
        this.col = col;
        this.pos = pos;
        try {
                ({})();
        } catch(ex) {
                // hack: cut away the 1st line from the stack trace, because it just says "TypeError: {} is not a function", which is confusing
                var indexOfFirstNewline = ex.stack.search(/\r?\n/);
                this.stack = ex.stack.substr(indexOfFirstNewline);
        };
};

function js_error(message, line, col, pos, fullText) {
        // hack: manually print the error message, because someone higher up silently eats the exception and doesn't print it. TODO: investigate why it gets eaten.
        // see https://github.com/kripken/emscripten/issues/5700
        process.stderr.write("\n" + "JS optimizer error:\n" + message + " (line: " + line + ", col: " + col + ", pos: " + pos + ")\n");
        if (typeof fullText !== 'undefined') {
            var iNewlineBeforeError = fullText.lastIndexOf('\n', pos);
            var iNextNewlineAfterError = fullText.indexOf('\n', pos);
            if (iNewlineBeforeError == -1) // could happen if we were on the first line
                iNewlineBeforeError = 0;
            if (iNextNewlineAfterError == -1) // could happen if we were on the last line
                iNextNewlineAfterError = fullText.length;
            var iNewlineSeveralLinesBeforeError = iNewlineBeforeError;
            if (iNewlineSeveralLinesBeforeError > 0) {
                for (var i = 0; i < 4; i++) // to show 4 lines before the error
                    iNewlineSeveralLinesBeforeError = fullText.lastIndexOf('\n', iNewlineSeveralLinesBeforeError-1);
            }
            var textOfErrorLine = fullText.substring(iNewlineBeforeError+1, iNextNewlineAfterError);
            var textOfSeveralLinesBeforeError = fullText.substring(iNewlineSeveralLinesBeforeError+1, iNewlineBeforeError);
            var indicator = textOfErrorLine.replace(/[^\t]/g, ' '); // replace everything except tabs by space
            indicator = indicator.substr(0, col) + '^';
            process.stderr.write("Error context:\n=======\n" + textOfSeveralLinesBeforeError + "\n" + textOfErrorLine + "\n" + indicator + "\n=======\n");
        }
        throw new JS_Parse_Error(message, line, col, pos);
};

        function croak(msg, line, col, pos) {
                var ctx = S.input.context();
                js_error(msg,
                         line != null ? line : ctx.tokline,
                         col != null ? col : ctx.tokcol,
                         pos != null ? pos : ctx.tokpos,
                         ctx.text); // hack: send the full text of the js code file into the error-reporting function, so we can show a few lines of context before the error
        };
```

This will print an output like for example:
```
JS optimizer error:
Unexpected token: name (result) (line: 179, col: 5, pos: 8674)
Error context:
=======
        // copy whole array from JS memory to C++ heap:
        var cppHeapArray = new Uint8Array(Module.HEAPU8.buffer, cppHeapPtr, jsTypedArray.byteLength);
        cppHeapArray.set(new Uint8Array(jsTypedArray.buffer));
        // call the C++ code, pass the pointer to the new array on the C++ heap:
        let result = callback(cppHeapPtr, jsTypedArray.byteLength);
            ^
=======

E:\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:307
        throw new JS_Parse_Error(message, line, col, pos);
        ^

    at new JS_Parse_Error (E:\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:261:21)
```

**Comment by kripken** [comment]
Thanks @elHamil , that's very helpful!

After reading that, I wrote up #6545 which will hopefully finally fix this issue.
