### ISSUE TITLE
OSError: [Errno 2] No such file or directory when using SIDE_MODULE=1

### ISSUE THREAD

**Issue by ChrisZieba** [kripken/emscripten#5795]
I'm trying to compile a stand alone module using this command:

```
emcc hello_world.c -Os -s WASM=1 -s SIDE_MODULE=1 -o hello_world.wasm
```

but I'm getting this error:

```
Traceback (most recent call last):
  File "/home/latb/emsdk/emscripten/tag-1.37.22/emcc", line 13, in <module>
    emcc.run()
  File "/home/latb/emsdk/emscripten/tag-1.37.22/emcc.py", line 1812, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/latb/emsdk/emscripten/tag-1.37.22/emcc.py", line 2279, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 506, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Does anyone know how I can resolve this?

Here is the c code (contents of `hello_world.c`) I'm trying to compile:

```c
int doubler(int x) {
  return 2 * x;
}
```

**Comment by kripken** [comment]
I believe this is fixed by #5763, which just landed on incoming right now.

You can also work around it (instead of getting incoming) by first building a non-side module wasm (remove `-s SIDE_MODULE=1` from that command).
