### ISSUE TITLE
Error in js optimizer

### ISSUE THREAD

**Issue by kodabb** [kripken/emscripten#585]
This is a writeup on replicating the errors we get trying to optimise Hedgewars.
First off. settings.js implies typed arrays mode 1 is best (we do use a lot of floats in the visual gears) but your comment on the mailing list suggests it isn't as good? At any rate, SDL seems nonfunctional with it enabled.

Welp. Setting things up.
This is a minor set of variations on https://code.google.com/r/xymengxy-webport/ which you probably already checked out.
So, if you did, just alter your .hg/hgrc URL to this new one.
This version is synced against most recent emscripten (mostly) and has INLINING_LIMIT = 0 set.

```
$ hg clone https://code.google.com/r/kyberneticist-webport/

$ export EMSCRIPTEN_ROOT=/path/to/checkout/of/kyberneticist-webport/web_exp/emscripten/emscripten
$ export EMCC_DEBUG=1
$ export PATH=${PATH}:${EMSCRIPTEN_ROOT}
```

Note, been also setting: EMSCRIPTEN_ROOT = os.path.expanduser('/path/to/checkout/of/kyberneticist-webport/web_exp/emscripten/emscripten')  from your ~/.emscripten file - I'm not sure if that's necessary along w/ the env var.

```
$ cd /path/to/checkout/of/kyberneticist-webport
$ cd project_files/web_exp
$ cmake -DWEB=ON
$ make
```

Wait...

```
/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:136
  return ident in generatedFunctions;
                  ^
TypeError: Cannot use 'in' operator to search for 'hwidb_get' in null
    at isGenerated (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:136:19)
    at /home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:213:31
    at traverse (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:183:18)
    at traverseChildren (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:157:23)
    at traverse (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:189:9)
    at traverseChildren (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:157:23)
    at traverse (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:189:9)
    at traverseChildren (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:157:23)
    at traverse (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:189:9)
    at traverseChildren (/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/js-optimizer.js:157:23)
Traceback (most recent call last):
  File "/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten//emcc", line 919, in <module>
    flush_js_optimizer_queue()
  File "/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten//emcc", line 900, in flush_js_optimizer_queue
    final = shared.Building.js_optimizer(final, js_optimizer_queue)
  File "/home/nemo/hg/hedgewars/webport2/web_exp/emscripten/emscripten/tools/shared.py", line 861, in js_optimizer
    assert len(output) > 0 and not output.startswith('Assertion failed'), 'Error in js optimizer: ' + output
AssertionError: Error in js optimizer: 
make[2]: *** [bin/emcc_build/hwjs.html] Error 1
make[1]: *** [bin/emcc_build/CMakeFiles/hwjs.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by juj** [comment]
Closing as old, the js optimizer is no longer relevant, and superseded by the optimizer implemented in C++11.
