### ISSUE TITLE
emcc.py throws if HTML shell contains Unicode character

### ISSUE THREAD

**Issue by kdex** [kripken/emscripten#5884]
For instance, try insering a `→` character into an HTML shell. On compilation, that will throw with something similar to:

```bash
Traceback (most recent call last):
  File "/srv/emsdk/emscripten/incoming/emcc.py", line 2725, in <module>
    run()
  File "/srv/emsdk/emscripten/incoming/emcc.py", line 1854, in run
    memfile, optimizer)
  File "/srv/emsdk/emscripten/incoming/emcc.py", line 2613, in generate_html
    html.write(html_contents.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3119: ordinal not in range(128)
```

**Comment by saschanaz** [comment]
It seems we should also encode conditionally in line 2613 as other lines in #5814 does.
