### ISSUE TITLE
emcc hello.c failed on Win10: ERROR:root:Invoking Process failed by Clang.exe

### ISSUE THREAD

**Issue by clarkeligong** [kripken/emscripten#5949]
hi, I just installed the latest emcc, but stopped by running the first demo, can anyone help me out? 
It seems clang.exe failed to output .o file, I don't know whether it is a problem with its -o parameter, which cannot located by clang.exe?
I tried to run clang.exe command with other -o parameter manully, it works!!!
So maybe I can reset the -o parameter of clang.exe?! but how?!

following are output:

```
D:\MEAN-doc\tools\emscripten>emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.22
clang version 4.0.0  (emscripten 1.37.22 : 1.37.22)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\MEAN-doc\tools\emscripten\clang\e1.37.22_64bit
INFO:root:(Emscripten: Running sanity checks)

D:\MEAN-doc\tools\emscripten>emcc --clear-cache
INFO:root:clearing cache as requested by --clear-cache
INFO:root:(Emscripten: Running sanity checks)

D:\MEAN-doc\tools\emscripten>emcc test/hello.c
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "C:\Users\Administrator\.emscripten_
cache\asmjs\dlmalloc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "C:\Users\Administrator\.emscripten_cach
e\asmjs\libc.bc" for subsequent builds)
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\site.py", line 548, in <module>
    main()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\site.py", line 537, in main
    aliasmbcs()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\site.py", line 465, in aliasmbcs
    import locale, codecs
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\locale.py", line 12, in <module>
    """
KeyboardInterrupt
Process PoolWorker-1:
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 258, in _bootstr
ap
    self.run()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 65, in mapstar
    return map(*args)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 13, in call_process
    proc.communicate()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 803, in communicate
    self.wait()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 997, in wait
 Traceback (most recent call last):
   _subprocess.INFINITE)
KeyboardInterrupt
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc", line 13, in <module>
    emcc.run()
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc.py", line 298, in run
    shared.check_sanity(force=DEBUG)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\shared.py", line 523, in check_sanity
    if sanity_data != generate_sanity():
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\\emcc", line 13, in <module>
    emcc.run()
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\shared.py", line 501, in generate_sanity
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc.py", line 1417, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_te
mp, stdout_=None, stderr_=None, forced=forced_stdlibs)
      File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 493, in calculate
    libfile = shared.Cache.get(name, do_create, extension=suffix)
return EMSCRIPTEN_VERSION + '|' + LLVM_ROOT + '|' + get_clang_version() + ('_wasm' if Settings.WASM_BACKEND else
 '')
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\cache.py", line 100, in get
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\shared.py", line 332, in get_clang_version
    temp = creator()
      File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 491, in do_create
response = Popen([CLANG, '-v'], stderr=PIPE).communicate()[1]
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    ret = create(name)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 134, in create_libc
    return build_libc(libname, libc_files, args)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 80, in build_libc
    run_commands(commands)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 28, in run_commands
    pool.map_async(call_process, commands, chunksize=1).get(maxint)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 548, in get
        self.wait(timeout)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 543, in wait
    self._cond.wait(timeout)
errread, errwrite)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\threading.py", line 358, in wait
    _sleep(delay)
KeyboardInterrupt
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc", line 13, in <module>
    emcc.run()
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc.py", line 1357, in run
    shared.Building.llvm_opt(temp_file, options.llvm_opts, new_temp_file)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\shared.py", line 1886, in llvm_opt
    D:/MEAN-doc/tools/emscripten/clang/e1.37.22_64bit\opt.exeproc = Popen([LLVM_OPT] + inputs + opts + ['-o', ta
rget], stdout=PIPE)
: c:/users/admini~1/appdata/local/temp\tmp2vg3gh\iswblank.c.o: error: Could not open input file: no such file or
 directory
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
KeyboardInterruptProcess PoolWorker-3:

Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 258, in _bootstr
ap
    self.run()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 65, in mapstar
    return map(*args)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 13, in call_process
    proc.communicate()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 803, in communicate
    self.wait()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 997, in wait
    _subprocess.INFINITE)
KeyboardInterrupt
Process PoolWorker-4:
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 258, in _bootstr
ap
    self.run()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 65, in mapstar
    return map(*args)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 13, in call_process
    proc.communicate()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 803, in communicate
    self.wait()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 997, in wait
    _subprocess.INFINITE)
KeyboardInterrupt

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ERROR:root:Invoking Process failed: <<< D:/MEAN-doc/tools/emscripten/clang/e1.37.22_64bit\clang.exe -target asmj
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

s-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=37 -D__EMSCRIPTEN_tiny__=22 -D_LIBCPP_ABI_V
ERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -
isystemD:\MEAN-doc\tools\emscripten\emscripten\1.37.22\system\include\libcxx -Xclang -isystemD:\MEAN-doc\tools\e
mscripten\emscripten\1.37.22\system\lib\libcxxabi\include -Xclang -isystemD:\MEAN-doc\tools\emscripten\emscripte
n\1.37.22\system\include\compat -Xclang -isystemD:\MEAN-doc\tools\emscripten\emscripten\1.37.22\system\include -
Xclang -isystemD:\MEAN-doc\tools\emscripten\emscripten\1.37.22\system\include\SSE -Xclang -isystemD:\MEAN-doc\to
ols\emscripten\emscripten\1.37.22\system\include\libc -Xclang -isystemD:\MEAN-doc\tools\emscripten\emscripten\1.
37.22\system\lib\libc\musl\arch\emscripten -Xclang -isystemD:\MEAN-doc\tools\emscripten\emscripten\1.37.22\syste
m\local\include -ID:\MEAN-doc\tools\emscripten\emscripten\1.37.22\system\lib\libc\musl\src\internal -ID:\MEAN-do
c\tools\emscripten\emscripten\1.37.22\system\lib\libc\musl\arch\js -Werror -Wno-return-type -Wno-parentheses -Wn
o-ignored-attributes -Wno-shift-count-overflow -Wno-shift-negative-value -Wno-dangling-else -Wno-unknown-pragmas
 -Wno-shift-op-parentheses -Wno-string-plus-int -Wno-logical-op-parentheses -Wno-bitwise-op-parentheses -Wno-vis
ibility -Wno-pointer-sign -Os -mllvm -disable-llvm-optzns D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\system
\lib\libc\musl\src\ctype\iswcntrl.c -fno-inline-functions -Xclang -isystemD:\MEAN-doc\tools\emscripten\emscripte
n\1.37.22\system\include\SDL -emit-llvm -c -o c:/users/admini~1/appdata/local/temp\tmp2vg3gh\iswcntrl.c.o >>>
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc", line 13, in <module>
    emcc.run()
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc.py", line 1320, in run
    compile_source_file(i, input_file)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\emcc.py", line 1311, in compile_source_file
    execute(args) # let compiler frontend print directly, so colors are saved (PIPE kills that)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\shared.py", line 2600, in execute
    return Popen(cmd, *args, **kw).communicate() # let compiler frontend print directly, so colors are saved (PI
PE kills that)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
KeyboardInterrupt
Process PoolWorker-2:
Traceback (most recent call last):
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 258, in _bootstr
ap
    self.run()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 65, in mapstar
    return map(*args)
  File "D:\MEAN-doc\tools\emscripten\emscripten\1.37.22\tools\system_libs.py", line 13, in call_process
    proc.communicate()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 803, in communicate
    self.wait()
  File "D:\MEAN-doc\tools\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 997, in wait
    _subprocess.INFINITE)
KeyboardInterrupt
error: unable to open output file 'c:/users/admini~1/appdata/local/temp\tmp2vg3gh\iswcntrl.c.o':
      'no such file or directory'
1 error generated.
```

**Comment by saschanaz** [comment]
The log says several KeyboardInterrupt after starting to build libc.bc. Did you press Control+C because building libc took too much time?

**Comment by clarkeligong** [comment]
yes, I did press Ctrl+C

**Comment by saschanaz** [comment]
You should wait until libc build succeeds which may take a very long time depending on your machine's performance. Fortunately it will be cached so you only have to wait once.

**Comment by clarkeligong** [comment]
Ok, now I just waited for ca. 10 Minutes, it turns out followings:

![image](https://user-images.githubusercontent.com/3594419/34194932-1569072e-e596-11e7-826c-59b2b5994eed.png)

seems has error and the cache is cleared! 
Is Win10 a stable environment for emscripten? Maybe I should change to Linux OS ?!

**Comment by clarkeligong** [comment]
Followings come after ca. 15 Minuten:

![image](https://user-images.githubusercontent.com/3594419/34195066-a81057da-e596-11e7-9338-5778207dd82a.png)

**Comment by saschanaz** [comment]
>Is Win10 a stable environment for emscripten? Maybe I should change to Linux OS ?!

In fact I'm developing in Windows 10 so yes it's supported and should be stable.

Not sure where that `str` and `NoneType` error occurs. It should be investigated...

**Comment by saschanaz** [comment]
Can you once again do `--clear-cache` and try again?

**Comment by juj** [comment]
The concatenation error looks like a bug. Try setting the environment variables `set EMCC_DEBUG=1` and do a rerun of `emcc test/hello.c`, and paste the results - that should help us to get to debugging. Also, what does your file `c:\users\administrator\.emscripten` look like?

**Comment by clarkeligong** [comment]
Strange! Everything work fine as I retried this morning, still donot know why. 

here is c:\users\administrator\.emscripten look like:
import os
LLVM_ROOT='D:/MEAN-doc/tools/emscripten/clang/e1.37.22_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='D:/MEAN-doc/tools/emscripten/clang/e1.37.22_64bit/optimizer.exe'
BINARYEN_ROOT='D:/MEAN-doc/tools/emscripten/clang/e1.37.22_64bit/binaryen'
NODE_JS='D:/MEAN-doc/tools/emscripten/node/4.1.1_64bit/bin/node.exe'
PYTHON='D:/MEAN-doc/tools/emscripten/python/2.7.5.3_64bit/python.exe'
JAVA='D:/MEAN-doc/tools/emscripten/java/7.45_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='D:/MEAN-doc/tools/emscripten/emscripten/1.37.22'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/admini~1/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

![image](https://user-images.githubusercontent.com/3594419/34229195-5f5c70c8-e60e-11e7-95ff-31a6da4ccb46.png)
