### ISSUE TITLE
SDL2 application will break when using pthreads

### ISSUE THREAD

**Issue by aliasdevelopment** [kripken/emscripten#6009]
I have made a SDL2 application using the linker flag "-s USE_SDL=2" which works as expected.
I have made a ASIO application using https://github.com/emscripten-ports/asio which works as expected.
I have made a ASIO/pthread application with works as expected using the linker flags "-s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -s PROXY_TO_PTHREAD=1"

But I can not merge these applications together. It seems as if USE_SDL and USE_PTHREADS/PROXY_TO_PTHREAD works against each other. I known that many older tutorials states that multithreading is not possible, but also knows that a lot of activities has been done to change this.

I get the following error when combining SDL and pthreads:
pthread-main.js onmessage() captured an uncaught exception: ReferenceError: screen is not defined

I can understand that I would make sense that the resources for rendering would only be available for the main thread, but pthread is missing some features/resources for SDL to possible.

Is it by design that USE_SDL and USE_PTHREADS/PROXY_TO_PTHREAD work against each other?
Would it be possible to use SDL from the main thread and still use pthreads for additional work?

**Comment by jakogut** [comment]
I'm encountering this same issue. USE_SDL and USE_PTHREAD/PROXY_TO_PTHREAD seem to be incompatible.

**Comment by jakogut** [comment]
Digging into the issue further, the stack trace shows:

`ReferenceError: screen is not defined
    at Array.ASM_CONSTS (http://localhost:6931/test.js:1501:32)
    at _emscripten_asm_const_i (http://localhost:6931/test.js:1526:26)
    at _Emscripten_VideoInit (wasm-function[17363]:43)
    at _SDL_VideoInit (wasm-function[17486]:635)
    at _SDL_InitSubSystem (wasm-function[17481]:203)
    at _SDL_Init (wasm-function[17612]:3)
    at _main (wasm-function[310]:133)
    at Module._main (http://localhost:6931/test.js:11418:75)
    at ___call_main (http://localhost:6931/test.js:1877:24)
    at ___emscripten_thread_main (wasm-function[18150]:23)
onmessage @ test.worker.js:181
`
Looking at the Emscripten port of SDL2, `video/emscripten/SDL_emscriptenvideo.c:145`:

`    mode.w = EM_ASM_INT_V({
        return screen.width;
    }); 

    mode.h = EM_ASM_INT_V({
        return screen.height;
    }); 
`

So it seems that the `Emscripten_VideoInit` function tries to get the screen dimensions from the JS object `screen`, but the object isn't being proxied to the new thread `main` is running in.

**Comment by jakogut** [comment]
I've resolved the issues with proxying `EM_ASM` calls in the `sdl2` port (my fixes are available at https://github.com/jakogut/SDL2/tree/sdl2-proxy-pthread-fixes), now I'm getting:

```
TypeError: Cannot read property 'getContext' of undefined
    at Object.createContext (http://localhost:6931/test.js:6608:19)
    at _eglCreateContext (http://localhost:6931/test.js:6793:24)
    at _SDL_EGL_CreateContext (wasm-function[17463]:337)
    at _Emscripten_GLES_CreateContext (wasm-function[17453]:12)
    at _SDL_GL_CreateContext (wasm-function[17025]:143)
    at _GLES2_CreateRenderer (wasm-function[17017]:489)
    at _SDL_CreateRenderer (wasm-function[17662]:303)
    at _main (wasm-function[388]:376)
    at Module._main (http://localhost:6931/test.js:12316:33)
    at ___call_main (http://localhost:6931/test.js:2000:24)
```
 
Doing a little digging around seems to indicate that the EGL code at `src/library_egl.js` is unable to access the canvas object, probably because those calls need proxied as well. @kripken, can you shed any light on this issue?

**Comment by kripken** [comment]
This may be stuff that has not been proxied yet, yes - @juj can confirm.

**Comment by kripken** [comment]
Looks like the PR for this is https://github.com/emscripten-core/emscripten/pull/9336 - would be good to get that landed. @jakogut - is there something blocking it?

**Comment by jakogut** [comment]
@kripken No blockers, just have to address the feedback given. I can look at doing that later this week.

**Comment by Hossein-Noroozpour** [comment]
Hi, is there any update for this issue?

**Comment by Hossein-Noroozpour** [comment]
Hi, is there any update for this issue.

**Comment by janpaul123** [comment]
For those coming across this, it looks like https://github.com/emscripten-ports/SDL2/pull/127 is still open.

**Comment by SoapyMan** [comment]
So question is... when? 😅

**Comment by zengming00** [comment]
I ran into the same problem when I added network support to a working SDL2 project
#10665
#13755

**Comment by flyingllama87** [comment]
+1 running into this issue.

**Comment by HarrievG** [comment]
+1 ,
But , retrieving the size from screen can be replaced with just  Module['canvas'].width/height

**Comment by magne4000** [comment]
Is this still an issue since https://github.com/libsdl-org/SDL/pull/5365has been merged?

**Comment by connorjclark** [comment]
Fixing your link: https://github.com/libsdl-org/SDL/pull/5365

I believe https://github.com/libsdl-org/SDL/pull/6142 is what may have resolved this, which I think incorporated the changes I suggested to the author in my previous comment.
