### ISSUE TITLE
Js generation issue with 1.37.27

### ISSUE THREAD

**Issue by djdeath** [kripken/emscripten#6036]
Hi,

I'm trying to generate a "release" build of my application (i.e. not using -g4) but it seems emcc fails to generate the final .js file (the .wasm is generated fine).

Here is the error : 
```
djdeath@delly:~/src/mesa-src/gputop$ ninja -C meson-emscripten-release/
ninja: Entering directory `meson-emscripten-release/'
[1/1] Linking target gputop-ui/gputop-ui.js.
FAILED: gputop-ui/gputop-ui.js 
/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/em++  -o gputop-ui/gputop-ui.js 'gputop-ui/gputop-ui.js@exe/gputop-ui-main.cpp.o' 'gputop-ui/gputop-ui.js@exe/gputop-ui-multilines.cpp.o' 'gputop-ui/gputop-ui.js@exe/gputop-ui-timeline.cpp.o' 'gputop-ui/gputop-ui.js@exe/gputop-ui-topology.cpp.o' 'gputop-ui/gputop-ui.js@exe/gputop-ui-utils.cpp.o' 'gputop-ui/gputop-ui.js@exe/imgui_imgui_impl_sdl_gles2.cpp.o' 'gputop-ui/gputop-ui.js@exe/gputop-emscripten-network.c.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group gputop-ui/libimgui.a gputop-client-c/libgputop_client.a gputop-client-c/libgputop_client_oa.a mesa/libmesa.a subprojects/protobuf-c-1.3.0/libprotobuf-c.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/../subprojects/protobuf-c-1.3.0:$ORIGIN/../subprojects/protobuf-3.5.0' -Wl,-rpath-link,/home/djdeath/src/mesa-src/gputop/meson-emscripten-release/subprojects/protobuf-c-1.3.0:/home/djdeath/src/mesa-src/gputop/meson-emscripten-release/subprojects/protobuf-3.5.0 -s WASM=1 -O2 -s FULL_ES2=1 -s USE_SDL=2 

/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
        ^
TypeError: (intermediate value) is not a function
    at new JS_Parse_Error (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
    at js_error (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
    at croak (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
    at token_error (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
    at unexpected (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
    at Object.semicolon (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
    at prog1 (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
    at simple_statement (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
    at /home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
    at block_ (/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:999:32)
Traceback (most recent call last):
  File "/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/em++", line 16, in <module>
    emcc.run()
  File "/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/emcc.py", line 1849, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/emcc.py", line 2391, in do_binaryen
    emit_symbol_map=emit_symbol_map)
  File "/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/shared.py", line 2295, in minify_wasm_js
    js_file = Building.js_optimizer_no_asmjs(js_file, passes)
  File "/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/shared.py", line 2168, in js_optimizer_no_asmjs
    subprocess.check_call(NODE_JS + [js_optimizer.JS_OPTIMIZER, filename] + passes, stdout=open(next, 'w'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/djdeath/src/emscripten/emsdk-portable/node/4.1.1_64bit/bin/node', '/home/djdeath/src/emscripten/emsdk-portable/emscripten/1.37.27/tools/js-optimizer.js', '/tmp/tmpG138aA/gputop-ui.bc.o.js.mem.js', 'noPrintMetadata', 'JSDCE', 'minifyWhitespace']' returned non-zero exit status 1
ninja: build stopped: subcommand failed.
```

The same project compiled with -g4 manages to generate the .js fine.
Also switching from -O2 to -O1 works. -O3 doesn't.

**Comment by djdeath** [comment]
Actually I left a ```let plop = function() {};" in a EM_ASM macro. Turning the let into var fixes the problem \o/
