### ISSUE TITLE
Cannot read property 'apply' of undefined, at constructor call with Embind

### ISSUE THREAD

**Issue by N0omB** [kripken/emscripten#6054]
I may got a stupid problem, but I do not understand where my error is.

When I execute my constructor via this phrase:
```
var test = new Module.Cal01_View()
```

I arise this exception trace:
```
Cal01_View.js:7940 Uncaught TypeError: Cannot read property 'apply' of undefined
    at Object.asm.stackSave (http://localhost:3000/Cal01_View/Cal01_View.js:7940:23)
    at abortStackOverflow (http://localhost:3000/Cal01_View/Cal01_View.js:1201:126)
    at wasm-function[456]:25
    at wasm-function[1394]:13
    at dynCall_ii_429 (eval at makeDynCaller (http://localhost:3000/Cal01_View/Cal01_View.js:3377:19), <anonymous>:4:12)
    at Cal01_View.constructor_body (http://localhost:3000/Cal01_View/Cal01_View.js:6976:37)
    at Cal01_View.<anonymous> (http://localhost:3000/Cal01_View/Cal01_View.js:3500:31)
    at new Cal01_View (eval at createNamedFunction (http://localhost:3000/Cal01_View/Cal01_View.js:2101:14), <anonymous>:4:34)
    at <anonymous>:1:12
```
Does somebody have an idea, what I am doing wrong?

I do not have any main() method in my Cal01_View.cpp and want to use the WASM file only after constructed this object and via this object.
I also had good experiences with other files and classes, where this procedure worked.
But I do not find any special differences between my other files and this one.

For further information, I have this constructor:
```
Cal01_View::Cal01_View()
{
         //text on dialog window
	monthAndYear = std::string("");
	buttonDate = std::string("");
	outputLog = std::string("");
	//creates new calendar
	cal = new Calendar();
}
```

and these binds at the end of my Cal01_View.cpp:
```
EMSCRIPTEN_BINDINGS(rwmp_binds){
	using namespace emscripten;
	class_<Cal01_View>("Cal01_View")
		.constructor()
		.function("OnCancel", &Cal01_View::OnCancel)
		.function("OnOK", &Cal01_View::OnOK)
		.function("OnInitDialog", &Cal01_View::OnInitDialog)
		.function("OnBnClickedButtonPreviousmonth", &Cal01_View::OnBnClickedButtonPreviousmonth)
		.function("OnBnClickedButtonNextmonth", &Cal01_View::OnBnClickedButtonNextmonth)
		.function("OnDateClick", &Cal01_View::OnDateClick)
		.function("OnBnClickedButtonAdddate", &Cal01_View::OnBnClickedButtonAdddate)
		;
}
```

and use this command to compile:
```
emcc --bind Cal01_View.cpp -o Cal01_View.js -s WASM=1 -std=c++11
```

**Comment by N0omB** [comment]
recompiled it now again, and now it finally works
still dont know what the error was, but hey it seems to run now
