### ISSUE TITLE
I can't use SIDE_MODULE=1

### ISSUE THREAD

**Issue by Code-Hex** [kripken/emscripten#6108]
Hello.
I'm trying now `emcc fib.ll -s SIDE_MODULE=1 -O1 -o index.html`. 
So I got some messages after It is failed to compile LLVM IR.

```
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
'core2' is not a recognized processor for this target (ignoring processor)
'+cx16' is not a recognized feature for this target (ignoring feature)
'+fxsr' is not a recognized feature for this target (ignoring feature)
'+mmx' is not a recognized feature for this target (ignoring feature)
'+sse' is not a recognized feature for this target (ignoring feature)
'+sse2' is not a recognized feature for this target (ignoring feature)
'+sse3' is not a recognized feature for this target (ignoring feature)
'+ssse3' is not a recognized feature for this target (ignoring feature)
'+x87' is not a recognized feature for this target (ignoring feature)
'core2' is not a recognized processor for this target (ignoring processor)
'core2' is not a recognized processor for this target (ignoring processor)
'+cx16' is not a recognized feature for this target (ignoring feature)
'+fxsr' is not a recognized feature for this target (ignoring feature)
'+mmx' is not a recognized feature for this target (ignoring feature)
'+sse' is not a recognized feature for this target (ignoring feature)
'+sse2' is not a recognized feature for this target (ignoring feature)
'+sse3' is not a recognized feature for this target (ignoring feature)
'+ssse3' is not a recognized feature for this target (ignoring feature)
'+x87' is not a recognized feature for this target (ignoring feature)
'core2' is not a recognized processor for this target (ignoring processor)
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emcc.py", line 1619, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/tools/shared.py", line 2086, in emscripten
    call_emscripten(cmdline)
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emscripten.py", line 2265, in _main
    temp_files.run_and_clean(lambda: main(
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/tools/tempfiles.py", line 79, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emscripten.py", line 2270, in <lambda>
    DEBUG=DEBUG,
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emscripten.py", line 2166, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emscripten.py", line 1717, in emscript_wasm_backend
    wast = build_wasm(temp_files, infile, outfile, settings, DEBUG)
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emscripten.py", line 1805, in build_wasm
    assert shared.Settings.BINARYEN_ROOT, 'need BINARYEN_ROOT config set so we can use Binaryen s2wasm on the backend output'
AssertionError: need BINARYEN_ROOT config set so we can use Binaryen s2wasm on the backend output
```
However, I wrote to `~/.emscripten` as follow this before executing `emcc`.
```
import os

EMSCRIPTEN_ROOT = os.path.expanduser(os.getenv('EMSCRIPTEN', '/usr/local/Cellar/emscripten/1.37.28/libexec')) # directory
LLVM_ROOT = os.path.expanduser(os.getenv('LLVM', '/usr/local/opt/llvm/bin')) # directory
BINARYEN_ROOT = os.path.expanduser(os.getenv('BINARYEN', '/usr/local/opt/binaryen'))

# See below for notes on which JS engine(s) you need
NODE_JS = os.path.expanduser(os.getenv('NODE', '/Users/codehex/.nodebrew/current/bin/node')) # executable
SPIDERMONKEY_ENGINE = [os.path.expanduser(os.getenv('SPIDERMONKEY', 'js'))] # executable
V8_ENGINE = os.path.expanduser(os.getenv('V8', 'd8')) # executable

JAVA = 'java' # executable
TEMP_DIR = '/tmp'
CRUNCH = os.path.expanduser(os.getenv('CRUNCH', 'crunch')) # executable
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

I installed each platforms as follows.

```
brew install binaryen
brew install emscripten
```

This is versions of each platforms.

```
emcc (Emscripten gcc/clang-like replacement) 1.37.28 ()
binaryen 40

% clang -v
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

## What I did?

1. I wrote c code like this.
```c
#include <stdio.h>
#include <stdlib.h>

int main() {
    char *a = (char *)calloc(1, 15);
    a = "Hello, world!\n";
    const char *x = a;
    fprintf(stdout, "%s", x);
    return 0;
}
```

2. I ran this command.
```
clang -emit-llvm -O0 fib.c -S # I got fib.ll 
emcc fib.ll -s SIDE_MODULE=1 -O1 -o index.html
```

3 Fail.

I'd like to convert the above C code to webassembly.
How can I solve this problem?
Thanks.

**Comment by juj** [comment]
Not sure about brew and cellar, perhaps that might be an issue with their setup, but you can compile the above to wasm with

```bash
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
emcc fib.c -o fib.html -s WASM=1
```

You can substitute `latest` with `sdk-incoming-64bit binaryen-master-64bit` if you want to get the latest development code from the current `incoming` branch instead.

**Comment by Code-Hex** [comment]
@juj I tried `emcc fib.c -o fib.html -s WASM=1` and it got it well compiled!!
But why does not work if the following way?

```sh
clang -emit-llvm -O0 fib.c -S
emcc fib.ll -o index.html -s WASM=1
```

**Comment by kripken** [comment]
> clang -emit-llvm -O0 fib.c -S

That will emit LLVM IR for your native platform, x86 darwin. You should use emcc to compile the source files too, then it will use the proper IR for the wasm target.

**Comment by Code-Hex** [comment]
I see. 
I was thinking that ecmscripten can compile to wasm from LLVM IR.
Actually, I am currently developing a module for transpilling Perl to LLVM IR, and eventually trying to generate webassembly using ecmscripten at finally.
Therefore, I really wanted to generate WebAssembly using LLVM IR.

I will devise a bit more devise by myself.
Thanks @juj @kripken
