### ISSUE TITLE
WebAssembly backend doesn't support EXPORTED_FUNCTIONS

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#6149]
Using latest sdk-incoming-64bit compiled with `--build=Release --enable-wasm`.

```
$ cat simple.c
int add(int a, int b) {
  return a + b;
}
$ emcc simple.c -Os -s WASM=1 -s EXPORTED_FUNCTIONS='["_add"]' -o simple.js
$ wasm-dis simple.wasm                                                     
(module
 (type $0 (func (param i32 i32) (result i32)))
 (export "_add" (func $0))
 (func $0 (; 0 ;) (type $0) (param $var$0 i32) (param $var$1 i32) (result i32)
  (i32.add
   (get_local $var$1)
   (get_local $var$0)
  )
 )
)
$ EMCC_WASM_BACKEND=1 emcc simple.c -Os -s WASM=1 -s EXPORTED_FUNCTIONS='["_add"]' -o simple.js
$ wasm-dis simple.wasm                                                                         
(module
)
```

`main` function seems to be exported fine though.

Is this expected behaviour?

**Comment by kripken** [comment]
That looks like a bug. Very strange though, since this should be tested on the wasm waterfall...

Does that also happen in `-O2`? (if not, it could be metadce related)

**Comment by kripken** [comment]
Oh wait, what is `--enable-wasm`? Is this using the wasm backend in the fastcomp fork of LLVM? That's several LLVM versions behind, and might just be broken - something close to LLVM master should be ok.

**Comment by Kagami** [comment]
>Does that also happen in -O2? (if not, it could be metadce related)

You are right, `-O2` is fine.
(Btw, js backend exports functions with underscore but wasm without.)

>Oh wait, what is --enable-wasm? Is this using the wasm backend in the fastcomp fork of LLVM?

Yes. I didn't know that it's not recommended (since `emcc` provides useful option), I will try with latest vanilla LLVM then. Thanks.

**Comment by Kagami** [comment]
Same issue with master version:

```
$ /usr/lib/llvm/7/bin/llc --version
LLVM (http://llvm.org/):
  LLVM version 7.0.0svn
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: sandybridge

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

**Comment by Kagami** [comment]
Hm, I actually found sort of workaround: you need to specify `EXPORTED_FUNCTIONS='["_add", "add"]'` for WebAssembly backend to get `add` export.
I guess this needs to be fixed because different backends shouldn't produce different export names?

**Comment by kripken** [comment]
That's very strange, and looks like a bug. It's true that the different backends have different prefixing, but that is lower level than `EXPORTED_FUNCTIONS` which should provide a consistent interface.

We do have tests for this, though, so it's odd it fails for you. Does `./tests/runner.py test_exported_response` pass, for example? You can see in the test code (in `tests/test_core.py`) that it prefixes `main` and `other_function`.

**Comment by Kagami** [comment]
This fails:

```diff
diff --git a/tests/test_core.py b/tests/test_core.py
index d469a4c5b..b1c5eeb08 100644
--- a/tests/test_core.py
+++ b/tests/test_core.py
@@ -6370,7 +6370,7 @@ def process(filename):
     '''
     open('exps', 'w').write('["_main","_other_function"]')
 
-    self.emcc_args += ['-s', 'EXPORTED_FUNCTIONS=@exps']
+    self.emcc_args += ['-s', 'EXPORTED_FUNCTIONS=@exps', '-s', 'ASSERTIONS=0', '-O3']
     self.do_run(src, '''waka 5!''')
     assert 'other_function' in open('src.cpp.o.js').read()
 
```

```
$ ./tests/runner.py test_exported_response
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_core']
Running test_core: (1 tests)
test_exported_response (test_core.default) ... (checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
(test did not pass in JS engine: ['/home/kagami/code/tmp/emsdk/node/8.9.1_64bit/bin/node'])
ERROR

======================================================================
ERROR: test_exported_response (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kagami/code/tmp/emsdk/emscripten/incoming/tests/test_core.py", line 6374, in test_exported_response
    self.do_run(src, '''waka 5!''')
  File "/home/kagami/code/tmp/emsdk/emscripten/incoming/tests/runner.py", line 689, in do_run
    raise e
Exception: Expected to find 'waka 5!' in 'TypeError: Module._other_function is not a function
    at Array.ASM_CONSTS (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18080)
    at _emscripten_asm_const_i (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18163)
    at wasm-function[64]:24
    at Object.Module._main (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:96591)
    at Object.callMain (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97682)
    at doRun (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98425)
    at run (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98593)
    at runCaller (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97301)
    at removeRunDependency (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:12554)
    at receiveInstance (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:15289)
exception thrown: TypeError: Module._other_function is not a function,TypeError: Module._other_function is not a function
    at Array.ASM_CONSTS (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18080)
    at _emscripten_asm_const_i (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18163)
    at wasm-function[64]:24
    at Object.Module._main (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:96591)
    at Object.callMain (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97682)
    at doRun (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98425)
    at run (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98593)
    at runCaller (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97301)
    at removeRunDependency (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:12554)
    at receiveInstance (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:15289)
failed to asynchronously prepare wasm: TypeError: Module._other_function is not a function
TypeError: Module._other_function is not a function
    at Array.ASM_CONSTS (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18080)
    at _emscripten_asm_const_i (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18163)
    at wasm-function[64]:24
    at Object.Module._main (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:96591)
    at Object.callMain (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97682)
    at doRun (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98425)
    at run (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98593)
    at runCaller (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97301)
    at removeRunDependency (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:12554)
    at receiveInstance (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:15289)
', diff:

--- expected
+++ actual
@@ -1 +1,35 @@
-waka 5!
+TypeError: Module._other_function is not a function
+    at Array.ASM_CONSTS (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18080)
+    at _emscripten_asm_const_i (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18163)
+    at wasm-function[64]:24
+    at Object.Module._main (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:96591)
+    at Object.callMain (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97682)
+    at doRun (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98425)
+    at run (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98593)
+    at runCaller (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97301)
+    at removeRunDependency (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:12554)
+    at receiveInstance (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:15289)
+exception thrown: TypeError: Module._other_function is not a function,TypeError: Module._other_function is not a function
+    at Array.ASM_CONSTS (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18080)
+    at _emscripten_asm_const_i (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18163)
+    at wasm-function[64]:24
+    at Object.Module._main (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:96591)
+    at Object.callMain (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97682)
+    at doRun (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98425)
+    at run (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98593)
+    at runCaller (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97301)
+    at removeRunDependency (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:12554)
+    at receiveInstance (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:15289)
+failed to asynchronously prepare wasm: TypeError: Module._other_function is not a function
+TypeError: Module._other_function is not a function
+    at Array.ASM_CONSTS (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18080)
+    at _emscripten_asm_const_i (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:18163)
+    at wasm-function[64]:24
+    at Object.Module._main (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:96591)
+    at Object.callMain (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97682)
+    at doRun (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98425)
+    at run (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:98593)
+    at runCaller (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:97301)
+    at removeRunDependency (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:12554)
+    at receiveInstance (/tmp/emscripten_test_default_SUolmM/src.cpp.o.js:1:15289)
+



----------------------------------------------------------------------
Ran 1 test in 2.281s

FAILED (errors=1)
```

**Comment by kripken** [comment]
Thanks, now I see. I believe that is an `-O3` specific bug, which by coincidence should have just been fixed on `incoming` with #6154 Does it work for you with that?

**Comment by Kagami** [comment]
Now it works, thanks.
Though I'm a bit worried that WebAssembly backend uses different prefix scheme. It creates incompatibility if you have your own JavaScript loader. Is there any particular reason for that?

**Comment by kripken** [comment]
Great, thanks for confirming.

Yeah, the difference between the backends worries me too. The reason it exists is that the people writing the new one thought it was better/nicer to prefix their way. Which it sort of is, so maybe in the long term it's worth the hassle.
