### ISSUE TITLE
__init__() takes at least 3 arguments (1 given)

### ISSUE THREAD

**Issue by WolverinDEV** [kripken/emscripten#6256]
Hello,
when i try to build a lib called "libopus.js" emscripten fails on building.
```
emcc -o build/libopus.js -O3 --memory-init-file 0 --closure 1 -s NO_FILESYSTEM=1 -s MODULARIZE=1 -s EXPORTED_FUNCTIONS="['_free','_malloc','_opus_strerror','_opus_get_version_string','_opus_encoder_get_size','_opus_encoder_init','_opus_encode','_opus_encode_float','_opus_encoder_ctl','_opus_decoder_get_size','_opus_decoder_init','_opus_decode','_opus_decode_float','_opus_decoder_ctl','_opus_packet_get_nb_samples']" ./opus/.libs/libopus.a
WARNING  root: Assigning a non-existent settings attribute "NO_FILESYSTEM"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())
```

**Comment by kripken** [comment]
Is there no more in the error message? I'd expect the stack trace to show where in emscripten code we called into that crashing python library code. Perhaps `EMCC_DEBUG=1` in the env can help.

Very odd it warns about `MODULARIZE` since that setting should exist. Unless this is on a quite old version of emscripten?

**Comment by WolverinDEV** [comment]
Hey,
when i enable the debug mode i get this output (Full output of my attemp to build libopus.js)
```
wolverindev@WolverinDEV:~/wgit/libopus.js$ export EMCC_DEBUG=1
wolverindev@WolverinDEV:~/wgit/libopus.js$ make
cd ./opus; ./autogen.sh
Updating build configuration files, please wait....
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:38: installing './compile'
configure.ac:33: installing './missing'
Makefile.am:269: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:272: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './depcomp'
cd ./opus; emconfigure ./configure --disable-extra-programs --disable-doc
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /usr/share/emscripten/emcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/share/emscripten/emcc accepts -g... yes
checking for /usr/share/emscripten/emcc option to accept ISO C89... none needed
checking whether /usr/share/emscripten/emcc understands -c and -o together... yes
checking dependency style of /usr/share/emscripten/emcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /usr/share/emscripten/emcc... /usr/share/emscripten/emcc
checking if the linker (/usr/share/emscripten/emcc) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/share/emscripten/emcc option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... /usr/share/emscripten/emranlib
checking command to parse /usr/bin/nm -B output from /usr/share/emscripten/emcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /usr/share/emscripten/emcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/share/emscripten/emcc supports -fno-rtti -fno-exceptions... no
checking for /usr/share/emscripten/emcc option to produce PIC... -fPIC -DPIC
checking if /usr/share/emscripten/emcc PIC flag -fPIC -DPIC works... no
checking if /usr/share/emscripten/emcc static flag -static works... no
checking if /usr/share/emscripten/emcc supports -c -o file.o... no
checking if /usr/share/emscripten/emcc supports -c -o file.o... (cached) no
checking if we can lock with hard links... yes
checking whether the /usr/share/emscripten/emcc linker (/usr/share/emscripten/emcc -m elf_x86_64) supports shared libraries... WARNING  root: invocation: /usr/share/emscripten/emcc -m elf_x86_64 -v  (in /home/wolverindev/wgit/libopus.js/opus)
WARNING  root: LLVM version appears incorrect (seeing "(tags/RELEASE_380/final)", expected "3.4")
INFO     root: (Emscripten: Running sanity checks)
DEBUG    root: just configuring: /usr/bin/clang -m elf_x86_64 -v -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/usr/share/emscripten/system/local/include -Xclang -isystem/usr/share/emscripten/system/include/compat -Xclang -isystem/usr/share/emscripten/system/include -Xclang -isystem/usr/share/emscripten/system/include/emscripten -Xclang -isystem/usr/share/emscripten/system/include/libc -Xclang -isystem/usr/share/emscripten/system/lib/libc/musl/arch/js -Xclang -isystem/usr/share/emscripten/system/include/gfx -Xclang -isystem/usr/share/emscripten/system/include/SDL -Xclang -isystem/usr/share/emscripten/system/include/libcxx -D__IEEE_LITTLE_ENDIAN -D__EMSCRIPTEN__ -DEMSCRIPTEN
clang: error: unknown argument: '-m'
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7.2.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.2.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.2.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
clang: error: no such file or directory: 'elf_x86_64'
yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... WARNING  root: invocation: /usr/share/emscripten/emcc -print-search-dirs  (in /home/wolverindev/wgit/libopus.js/opus)
WARNING  root: LLVM version appears incorrect (seeing "(tags/RELEASE_380/final)", expected "3.4")
INFO     root: (Emscripten: Running sanity checks)
DEBUG    root: just configuring: /usr/bin/clang -print-search-dirs -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/usr/share/emscripten/system/local/include -Xclang -isystem/usr/share/emscripten/system/include/compat -Xclang -isystem/usr/share/emscripten/system/include -Xclang -isystem/usr/share/emscripten/system/include/emscripten -Xclang -isystem/usr/share/emscripten/system/include/libc -Xclang -isystem/usr/share/emscripten/system/lib/libc/musl/arch/js -Xclang -isystem/usr/share/emscripten/system/include/gfx -Xclang -isystem/usr/share/emscripten/system/include/SDL -Xclang -isystem/usr/share/emscripten/system/include/libcxx -D__IEEE_LITTLE_ENDIAN -D__EMSCRIPTEN__ -DEMSCRIPTEN
GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for /usr/share/emscripten/emcc option to accept ISO C99... none needed
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking dependency style of /usr/share/emscripten/emcc... gcc3
checking for C/C++ restrict keyword... __restrict
checking for C99 variable-size arrays... yes
checking for cos in -lm... yes
checking if /usr/share/emscripten/emcc supports -fvisibility=hidden... yes
checking if /usr/share/emscripten/emcc supports -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes... yes
checking for lrintf... yes
checking for lrint... yes
checking for __malloc_hook... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating opus.pc
config.status: creating opus-uninstalled.pc
config.status: creating celt/arm/armopts.s
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
configure:
------------------------------------------------------------------------
  opus 1.1.2:  Automatic configuration OK.

    Compiler support:

      C99 var arrays: ................ yes
      C99 lrintf: .................... yes
      Use alloca: .................... no (using var arrays)

    General configuration:

      Floating point support: ........ yes
      Fast float approximations: ..... no
      Fixed point debugging: ......... no
      Inline Assembly Optimizations: . No inline ASM for your platform, please send patches
      External Assembly Optimizations: 
      Intrinsics Optimizations.......: no
      Run-time CPU detection: ........ no
      Custom modes: .................. no
      Assertion checking: ............ no
      Fuzzing: ....................... no

      API documentation: ............. no
      Extra programs: ................ no
------------------------------------------------------------------------

 Type "make; make install" to compile and install
 Type "make check" to run the test suite

cd ./opus; emmake make
make[1]: Entering directory '/home/wolverindev/wgit/libopus.js/opus'
make  all-recursive
make[2]: Entering directory '/home/wolverindev/wgit/libopus.js/opus'
make[3]: Entering directory '/home/wolverindev/wgit/libopus.js/opus'
make[4]: Entering directory '/home/wolverindev/wgit/libopus.js/opus/doc'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/wolverindev/wgit/libopus.js/opus/doc'
make[3]: Leaving directory '/home/wolverindev/wgit/libopus.js/opus'
make[2]: Leaving directory '/home/wolverindev/wgit/libopus.js/opus'
make[1]: Leaving directory '/home/wolverindev/wgit/libopus.js/opus'
emcc -o build/libopus.js -O3 --memory-init-file 0 --closure 1 -s NO_FILESYSTEM=1 -s MODULARIZE=1 -s EXPORTED_FUNCTIONS="['_free','_malloc','_opus_strerror','_opus_get_version_string','_opus_encoder_get_size','_opus_encoder_init','_opus_encode','_opus_encode_float','_opus_encoder_ctl','_opus_decoder_get_size','_opus_decoder_init','_opus_decode','_opus_decode_float','_opus_decoder_ctl','_opus_packet_get_nb_samples']" ./opus/.libs/libopus.a
WARNING  root: invocation: /usr/bin/emcc -o build/libopus.js -O3 --memory-init-file 0 --closure 1 -s NO_FILESYSTEM=1 -s MODULARIZE=1 -s EXPORTED_FUNCTIONS=['_free','_malloc','_opus_strerror','_opus_get_version_string','_opus_encoder_get_size','_opus_encoder_init','_opus_encode','_opus_encode_float','_opus_encoder_ctl','_opus_decoder_get_size','_opus_decoder_init','_opus_decode','_opus_decode_float','_opus_decoder_ctl','_opus_packet_get_nb_samples'] ./opus/.libs/libopus.a  (in /home/wolverindev/wgit/libopus.js)
WARNING  root: LLVM version appears incorrect (seeing "(tags/RELEASE_380/final)", expected "3.4")
INFO     root: (Emscripten: Running sanity checks)
WARNING  root: Assigning a non-existent settings attribute "NO_FILESYSTEM"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "MODULARIZE"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
DEBUG    root: compiling to bitcode
DEBUG    root: emcc step "parse arguments and setup" took 0.01 seconds
DEBUG    root: copying library file: ./opus/.libs/libopus.a
DEBUG    root: emcc step "bitcodeize inputs" took 0.00 seconds
DEBUG    root: emcc step "process inputs" took 0.00 seconds
DEBUG    root: will generate JavaScript
DEBUG    root: including libc
DEBUG    root:  building libc for cache
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
      ^
SyntaxError: invalid syntax
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
  File "/usr/share/emscripten/emcc", line 578
  File "/usr/share/emscripten/emcc", line 578
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
    ''' % (this, this, this)
    ''' % (this, this, this)
      ^
      ^
SyntaxError: invalid syntax
SyntaxError: invalid syntax
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^
SyntaxError: invalid syntax
  File "/usr/share/emscripten/emcc", line 578
    ''' % (this, this, this)
      ^

```

I dont know, how i could get the version of `emscripten` (Im verry new to js and web development :D)

**Comment by kripken** [comment]
That does seem like an old version - there's nothing like `this, this, this` in that file that I can see. Or perhaps the files were modified locally?

To see the version number you can do `emcc -v`, the first line will have the emscripten version number.

**Comment by WolverinDEV** [comment]
Resolved the issue (The emscripten compiler from the ubuntu repro is too old :) (10 minor versions behind))
Everything works now, and btw amazing project!

**Comment by akshatbhargava123** [comment]
@WolverinDEV Where do I download the latest version?

**Comment by WolverinDEV** [comment]
Directly from github :)
I just cloned it and linked the scripts to my `/bin/` directory.
You could verify your installation via emcc -v

**Comment by kripken** [comment]
Or you can use the emsdk, which will download a pre-built llvm for you, https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html
