### ISSUE TITLE
Error downloading Binaryen with 1.37.35

### ISSUE THREAD

**Issue by mischnic** [kripken/emscripten#6276]
Should be self-explanatory (I have deleted .emscripten_ports and .emscripten_cache):

```sh
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.35
clang version 5.0.0  (emscripten 1.37.35 : 1.37.35)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
INFO:root:(Emscripten: Running sanity checks)
$ emcc -s WASM=1 main.c -o main.js
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/Users/niklas/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
WARNING:root:retrieving port: binaryen from https://github.com/WebAssembly/binaryen/archive/version_44.zip
ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/tools/python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/emcc.py", line 1483, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/tools/system_libs.py", line 749, in get_ports
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/tools/ports/binaryen.py", line 21, in get
    ports.fetch_project('binaryen', 'https://github.com/WebAssembly/binaryen/archive/' + TAG + '.zip', 'binaryen-' + TAG)
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/tools/system_libs.py", line 676, in fetch_project
    retrieve()
  File "/usr/local/Cellar/emscripten/1.37.35/libexec/tools/system_libs.py", line 639, in retrieve
    f = urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```

**Comment by niklasf** [comment]
Probably because of https://github.com/blog/2507-weak-cryptographic-standards-removed

**Comment by mischnic** [comment]
Same issue as #6275

**Comment by kripken** [comment]
Closing in favor of the previously-filed issue, let's focus discussion there.
