### ISSUE TITLE
O2 and above optimization cause a compilation errors

### ISSUE THREAD

**Issue by vadlis** [kripken/emscripten#6475]
I met a problem when compiled sources with -O2 optimization. The first thing I tried is do the same for simple code. So, for simple program:
```
#include <cstdio>

int main() {
	printf("Hello world!");
}
```

it gave next results:

```
D:\innovation\flow\tools\flowc\tests\cpp>call emcc out/test_a.cpp -I "../../../../" -std=c++1z --pre-js out/WASMtest/js/pixi.min.js --pre-js out/WASMtest/dfontjs/pixi-dfont.js --pre-js out/WASMtest/test405_a.js --pre-js out/WASMtest/test_ad.js -s EXTRA_EXPORTED_RUNTIME_METHODS=['stringToUTF16'] -s WASM=1 -O2 -w -o out/WASMtest/test_a.html 
DEBUG:root:Cache: PID 9048 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 9048 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
WARNING:root:invocation: D:\innovation\emsdk\emscripten\incoming\\emcc out/test_a.cpp -I ../../../../ -std=c++1z --pre-js out/WASMtest/js/pixi.min.js --pre-js out/WASMtest/dfontjs/pixi-dfont.js --pre-js out/WASMtest/test405_a.js --pre-js out/WASMtest/test_ad.js -s EXTRA_EXPORTED_RUNTIME_METHODS=['stringToUTF16'] -s WASM=1 -O2 -w -o out/WASMtest/test_a.html  (in D:\innovation\flow\tools\flowc\tests\cpp)
DEBUG:root:Checking JS engine ['D:/innovation/emsdk/node/8.9.1_64bit/bin/node.exe']
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.37.36, 1.37.35, 1.37.35)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
DEBUG:root:asm.js opts not forced by user or an option that depends them, and we do not intend to run the asm.js, so disabling and leaving opts to the binaryen optimizer
DEBUG:root:compiling to bitcode
DEBUG:root:emcc step "parse arguments and setup" took 2.04 seconds
DEBUG:root:compiling source file: out/test_a.cpp
DEBUG:root:running: D:/innovation/emsdk/clang/e1.37.35_64bit\clang++.exe -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=37 -D__EMSCRIPTEN_tiny__=36 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\include\libcxx -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\lib\libcxxabi\include -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\include\compat -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\include -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\include\SSE -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\include\libc -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\lib\libc\musl\arch\emscripten -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\local\include -I../../../../ -std=c++1z -O2 -w -mllvm -disable-llvm-optzns out/test_a.cpp -Xclang -disable-O0-optnone -Xclang -isystemD:\innovation\emsdk\emscripten\incoming\system\include\SDL -emit-llvm -c -o C:\Users\Vadim\AppData\Local\Temp\tmpthqv71\test_a_0.o
DEBUG:root:emcc step "bitcodeize inputs" took 0.86 seconds
DEBUG:root:optimizing out/test_a.cpp
DEBUG:root:emcc: LLVM opts: -O3 -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 1]
DEBUG:root:emcc step "process inputs" took 0.34 seconds
DEBUG:root:will generate JavaScript
DEBUG:root:binaryen root already set to D:/innovation/emsdk/clang/e1.37.35_64bit/binaryen
DEBUG:root:Cache: PID 19252 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 19252 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: PID 19748 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 19748 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: PID 7188 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: PID 14824 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: PID 5444 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 7188 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: PID 11644 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: PID 20520 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 11644 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: PID 20520 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: PID 11980 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 11980 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 14824 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 5444 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:including dlmalloc.bc
DEBUG:root:Cache: PID 9048 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache\asmjs
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 9048 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache\asmjs
DEBUG:root:including libc.bc
DEBUG:root:Cache: PID 9048 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache\asmjs
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 9048 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache\asmjs
DEBUG:root:including wasm-libc.bc
DEBUG:root:Cache: PID 9048 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache\asmjs
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 9048 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache\asmjs
DEBUG:root:emcc step "calculate system libraries" took 0.69 seconds
DEBUG:root:linking: ['C:\\Users\\Vadim\\AppData\\Local\\Temp\\tmpthqv71\\test_a_0_1.o', 'C:\\Users\\Vadim\\.emscripten_cache\\asmjs\\dlmalloc.bc', 'C:\\Users\\Vadim\\.emscripten_cache\\asmjs\\libc.bc', 'C:\\Users\\Vadim\\.emscripten_cache\\asmjs\\wasm-libc.bc']
DEBUG:root:emcc step "link" took 0.45 seconds
DEBUG:root:saving intermediate processing steps to C:\Users\Vadim\AppData\Local\Temp\emscripten_temp
DEBUG:root:(not saving intermediate C:\Users\Vadim\AppData\Local\Temp\emscripten_temp\emcc-0-basebc.bc because deferring linking)
DEBUG:root:emcc: LLVM opts: -strip-debug -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 4]
DEBUG:root:emcc step "post-link" took 0.43 seconds
DEBUG:root:LLVM => JS
DEBUG:root:TEMP_DIR not defined in C:\Users\Vadim/.emscripten, using C:\Users\Vadim\AppData\Local\Temp
DEBUG:root:emscript: llvm backend: D:/innovation/emsdk/clang/e1.37.35_64bit\llc C:\Users\Vadim\AppData\Local\Temp\tmpthqv71\test_a.bc -march=js -filetype=asm -o C:\Users\Vadim\AppData\Local\Temp\emscripten_temp\tmpk4tjw2.4.js -emscripten-stack-size=5242880 -O2 -emscripten-precise-f32 -emscripten-global-base=1024 -emscripten-no-exit-runtime -emscripten-wasm -emscripten-only-wasm
DEBUG:root:  emscript: llvm backend took 0.346999883652 seconds
DEBUG:root:emscript: js compiler glue
DEBUG:root:very limited syscalls (140, 146, 6, 54) so disabling full filesystem support
DEBUG:root:  emscript: glue took 0.59500002861 seconds
DEBUG:root:emscript: python processing: function tables and exports
DEBUG:root:asm text sizes[[167449, 5421], 465, 173, 1184, 0, 259, 292, 436, 2, 578, 2094]
DEBUG:root:  emscript: python processing: function tables and exports took 0.000999927520752 seconds
DEBUG:root:emscript: python processing: finalize
DEBUG:root:  emscript: python processing: finalize took 0.000999927520752 seconds
DEBUG:root:emcc step "emscript (llvm => executable code)" took 1.04 seconds
DEBUG:root:applying pre/postjses
DEBUG:root:emcc step "source transforms" took 0.25 seconds
DEBUG:root:wrote memory initialization to out/WASMtest/test_a.html.mem
DEBUG:root:emcc step "memory initializer" took 0.37 seconds
DEBUG:root:emcc step "js opts" took 0.00 seconds
DEBUG:root:separating asm
DEBUG:root:Cache: PID 22440 acquiring multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 22440 released multiprocess file lock to Emscripten cache at C:\Users\Vadim\.emscripten_cache
DEBUG:root:check tells us to use asm.js backend
DEBUG:root:using binaryen, with method: native-wasm
DEBUG:root:binaryen root already set to D:/innovation/emsdk/clang/e1.37.35_64bit/binaryen
DEBUG:root:asm2wasm (asm.js => WebAssembly): D:/innovation/emsdk/clang/e1.37.35_64bit/binaryen\bin\asm2wasm out/WASMtest/test_a.temp.asm.js --total-memory=16777216 --trap-mode=allow -O2 --mem-init=out/WASMtest/test_a.html.mem --mem-base=1024 --wasm-only -o out/WASMtest/test_a.wasm
DEBUG:root:emcc step "asm2wasm" took 0.59 seconds
DEBUG:root:running cleanup on shell code: noPrintMetadata JSDCE minifyWhitespace

D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:271
    throw new JS_Parse_Error(message, line, col, pos);
    ^
Error
    at new JS_Parse_Error (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:263:18)
    at js_error (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:271:11)
    at croak (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:733:9)
    at token_error (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:740:9)
    at unexpected (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:746:9)
    at D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:1124:9
    at maybe_unary (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:1209:19)
    at expr_ops (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:1236:24)
    at maybe_conditional (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:1240:20)
    at maybe_assign (D:\innovation\emsdk\emscripten\incoming\tools\eliminator\node_modules\uglify-js\lib\parse-js.js:1264:20)
Traceback (most recent call last):
  File "D:\innovation\emsdk\emscripten\incoming\\emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "D:\innovation\emsdk\emscripten\incoming\tools\python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "D:\innovation\emsdk\emscripten\incoming\tools\python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "D:\innovation\emsdk\emscripten\incoming\emcc.py", line 1886, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "D:\innovation\emsdk\emscripten\incoming\emcc.py", line 2426, in do_binaryen
    emit_symbol_map=emit_symbol_map)
  File "D:\innovation\emsdk\emscripten\incoming\tools\shared.py", line 2220, in minify_wasm_js
    js_file = Building.js_optimizer_no_asmjs(js_file, passes)
  File "D:\innovation\emsdk\emscripten\incoming\tools\shared.py", line 2093, in js_optimizer_no_asmjs
    subprocess.check_call(NODE_JS + [js_optimizer.JS_OPTIMIZER, filename] + passes, stdout=open(next, 'w'))
  File "D:\innovation\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:/innovation/emsdk/node/8.9.1_64bit/bin/node.exe', 'D:\\innovation\\emsdk\\emscripten\\incoming\\tools\\js-optimizer.js', 'C:\\Users\\Vadim\\AppData\\Local\\Temp\\tmpthqv71\\test_a.bc.o.js.pp.js.mem.js', 'noPrintMetadata', 'JSDCE', 'minifyWhitespace']' returned non-zero exit status 1
```

Can you advice how to solve such issue?
Thanks

**Comment by kripken** [comment]
Looks like it's failing to parse the intermediate JS. That can happen if one of your --pre-jses has a syntax error, or uses JS that Ugilify1 (which we use to parse it) can't handle.

Seems like we have an issue for this, #5700 - more discussion there.

**Comment by vadlis** [comment]
Ok, thanks. I found where problem was (as you suggested it was in one of the pre-js). But now next question appeared:
When test it in browser (Chrome with localhost) i got next:
```
Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 Loading dfield fonts...
test405.js:1 WebFont is not defined
Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
test405.js:1 falling back to ArrayBuffer instantiation

Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 Loading dfield fonts...
test405.js:1 WebFont is not defined
Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
test405.js:1 falling back to ArrayBuffer instantiation

Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 Loading dfield fonts...
test405.js:1 WebFont is not defined
Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
test405.js:1 falling back to ArrayBuffer instantiation

Navigated to http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405simple.html
test405.js:1 Loading dfield fonts...
test405.js:1 WebFont is not defined
test405.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
test405.js:1 falling back to ArrayBuffer instantiation
test405.js:1 on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
	abort @ test405.js:1
	getBinary @ test405.js:1
	(anonymous) @ test405.js:1
	Promise.catch (async)
	getBinaryPromise @ test405.js:1
	instantiateArrayBuffer @ test405.js:1
	(anonymous) @ test405.js:1
	Promise.catch (async)
	doNativeWasm @ test405.js:formatted:31552
	Module.asm @ test405.js:formatted:31624
	(anonymous) @ test405.js:formatted:36456
test405.js:1 failed to asynchronously prepare wasm: abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)") at Error
		at jsStackTrace (http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405.js:1:697943)
		at stackTrace (http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405.js:1:698114)
		at abort (http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405.js:1:860779)
		at getBinary (http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405.js:1:706872)
		at http://localhost/flow/tools/flowc/tests/cpp/out/WASMtest/test405.js:1:707233
	(anonymous) @ test405.js:1
	Promise.catch (async)
	instantiateArrayBuffer @ test405.js:1
	(anonymous) @ test405.js:1
	Promise.catch (async)
	doNativeWasm @ test405.js:1
	Module.asm @ test405.js:1
	(anonymous) @ test405.js:1
```
Few notices:
- 'Navigated to ...' loop can be various but ends with exception
- sources was build with '-s ASSERTIONS=1'
- sources compiled with the same settings but with -O1 and lower - works fine

**Comment by kripken** [comment]
What is `WebFont`? Figuring out that error should be done first.

The streaming compilation thing is a warning (but if you configure the webserver for the MIME type if mentions, it will be faster).

**Comment by vadlis** [comment]
Thanks for assistance @kripken. Found a problem at my side. Sorry for disturbing. 
BTW: Is there other place where question may be asked - issues list appears to be not a quite good place

**Comment by kripken** [comment]
No problem, glad you figured it out.

You can also use irc (#emscripten on mozilla), if you prefer that. But it's fine to use issues for questions in my opinion at least.
