### ISSUE TITLE
AttributeError: 'list' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by seedix-net** [kripken/emscripten#649]
Hello @kripken, 
i was compiled speak.js with option [-Ox] on emscripten and this error happened but if i removed that option, its fine.
error message -->
Traceback (most recent call last):
  File "/home/seedix/Downloads/ema/emscripten/emcc", line 1041, in <module>
    flush_js_optimizer_queue()
  File "/home/seedix/Downloads/ema/emscripten/emcc", line 1022, in flush_js_optimizer_queue
    final = shared.Building.js_optimizer(final, js_optimizer_queue)
  File "/home/seedix/Downloads/ema/emscripten/tools/shared.py", line 923, in js_optimizer
    output = Popen([NODE_JS, '--nocrankshaft', JS_OPTIMIZER, filename] + passes, stdout=PIPE).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
<---
Then the speak js doesn't running well.
how to fix that error?
thank you

**Comment by juj** [comment]
Closing as old/stale, the JS optimizer is superseded by the C++11 implemented optimizer. Feel free to post a new issue if stuff doesn't work in the latest compiler version!
