### ISSUE TITLE
KeyError: u'dd' with ASSERTIONS=2

### ISSUE THREAD

**Issue by Beuc** [kripken/emscripten#6554]
Hi,

Compiling:
https://github.com/PeachPy/EmCPython
emcc crashed:
```
EmCPython/test$ ninja
[1/1] CCLD python.asm.js
FAILED: python.asm.js python.asm.js.mem 
emcc -o python.asm.js -L -L../emscripten/lib -O2 -Wno-warn-absolute-paths -s TOTAL_MEMORY=268435456 -s ASSERTIONS=2 -s EMULATE_FUNCTION_POINTER_CASTS=1 --memory-init-file 0 --embed-file ../pydata.tar@/pydata.tar main.bc ../emscripten/lib/libpython2.7.a ../emscripten/lib/libtar.a
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
emcc: warning: cannot represent a NaN literal '0x55a788ea7ea0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %. = select i1 %60, double 0xFFF8000000000000, double 0x7FF8000000000000 in _Py_parse_inf_or_nan() 
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: posix_spawn_file_actions_init
Traceback (most recent call last):
  File "/home/em/emsource/emscripten/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/home/em/emsource/emscripten/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/em/emsource/emscripten/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/em/emsource/emscripten/emcc.py", line 1669, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/em/emsource/emscripten/tools/shared.py", line 2030, in emscripten
    emscripten._main(cmdline)
  File "/home/em/emsource/emscripten/emscripten.py", line 2353, in _main
    temp_files.run_and_clean(lambda: main(
  File "/home/em/emsource/emscripten/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/home/em/emsource/emscripten/emscripten.py", line 2358, in <lambda>
    DEBUG=DEBUG,
  File "/home/em/emsource/emscripten/emscripten.py", line 2266, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/home/em/emsource/emscripten/emscripten.py", line 99, in emscript
    function_tables_and_exports(funcs, metadata, mem_init, glue, forwarded_data, settings, outfile, DEBUG))
  File "/home/em/emsource/emscripten/emscripten.py", line 288, in function_tables_and_exports
    asm_setup = create_asm_setup(debug_tables, function_table_data, metadata, settings)
  File "/home/em/emsource/emscripten/emscripten.py", line 1153, in create_asm_setup
    asm_setup += '\nvar debug_table_' + sig + ' = ' + json.dumps(debug_tables[sig]) + ';'
KeyError: u'dd'
ninja: build stopped: subcommand failed.
```

With either WASM=0 or ASSERTIONS=1 the issue goes away.

This is 1.38.1.
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.1
clang version 5.0.0 (https://github.com/kripken/emscripten-fastcomp-clang 9eed11198884849dd69eb4a3b64a5e1aa8d01758) (https://github.com/kripken/emscripten-fastcomp ae6ba180f4d38b0709c610f5ee12dc97537003e1) (emscripten 1.38.1 : 1.38.1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/em/emsource/myfastcomp/emscripten-fastcomp/build/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```

Thanks and keep up the good work ^_^

**Comment by kripken** [comment]
That doesn't sound like a known bug. Can you maybe provide the bitcode + emcc command so I can reproduce? I can take a look at that.

**Comment by Beuc** [comment]
I tracked it to using ASSERTIONS=2 and EMULATE_FUNCTION_POINTER_CASTS=1:
```
$ echo "int main(void) {}" > test.c
$ emcc -s ASSERTIONS=2 -s EMULATE_FUNCTION_POINTER_CASTS=1 -o test.html test.c
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
Traceback (most recent call last):
  File "/home/me/workdir/emsource/emscripten/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/home/me/workdir/emsource/emscripten/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/me/workdir/emsource/emscripten/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/me/workdir/emsource/emscripten/emcc.py", line 1669, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/me/workdir/emsource/emscripten/tools/shared.py", line 2030, in emscripten
    emscripten._main(cmdline)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 2353, in _main
    temp_files.run_and_clean(lambda: main(
  File "/home/me/workdir/emsource/emscripten/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 2358, in <lambda>
    DEBUG=DEBUG,
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 2266, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 99, in emscript
    function_tables_and_exports(funcs, metadata, mem_init, glue, forwarded_data, settings, outfile, DEBUG))
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 288, in function_tables_and_exports
    asm_setup = create_asm_setup(debug_tables, function_table_data, metadata, settings)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 1153, in create_asm_setup
    asm_setup += '\nvar debug_table_' + sig + ' = ' + json.dumps(debug_tables[sig]) + ';'
KeyError: u'ii'
```

**Comment by kripken** [comment]
Hmm, not sure how that could happen, `debug_tables` should exist for all signatures. Hard to know what's going on here without a testcase, I'm afraid.

**Comment by kripken** [comment]
Oh sorry, I missed that line :) my brain automatically skips to the end of stack traces like that, it seems...

I confirm I can see the problem with the testcase, thanks. Investigating now.

**Comment by kripken** [comment]
Fix in #6575.

**Comment by kripken** [comment]
Great, closing.

**Comment by Beuc** [comment]
(#6575 is not merged though)

**Comment by kripken** [comment]
Thanks, that PR got forgotten somehow, updating it now.
