### ISSUE TITLE
binaryen2.test_source_map failes under LLD

### ISSUE THREAD

**Issue by sbc100** [kripken/emscripten#6680]
```
EMCC_EXPERIMENTAL_USE_LLD=1 ./tests/runner.py binaryen2.test_source_map
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/usr/local/google/home/sbc/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_core']
Running test_core: (1 tests)
test_source_map (test_core.binaryen2) ... (checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:Wasm source map won't be usable in a browser without --source-map-base
Reading DWARF information from /tmp/tmpvUSZpv/a.out.bc.o.lld.wasm
Read sections index
Saving to /tmp/tmpvUSZpv/a.out.bc.o.lld.wasm.map
Done.
[map parse exception: Unexpected char]
Fatal: error in parsing wasm source map
ERROR:root:'/usr/local/google/home/sbc/dev/wasm/binaryen-out/install/bin/wasm-emscripten-finalize /tmp/tmpvUSZpv/a.out.bc.o.lld.wasm -o /tmp/tmpvUSZpv/a.out.bc.o.wasm --global-base=1024 --emscripten-reserved-function-pointers=0 -g --input-source-map=/tmp/tmpvUSZpv/a.out.bc.o.lld.wasm.map --output-source-map=/tmp/tmpvUSZpv/a.out.bc.o.wasm.map' failed
Traceback (most recent call last):
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emcc.py", line 2915, in <module>
    sys.exit(run())
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emcc.py", line 1673, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/shared.py", line 2035, in emscripten
    emscripten._main(cmdline)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 2377, in _main
    temp_files.run_and_clean(lambda: main(
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 2382, in <lambda>
    DEBUG=DEBUG,
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 2290, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 1738, in emscript_wasm_backend
    wasm, metadata = build_wasm_lld(temp_files, infile, outfile, settings, DEBUG)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 1934, in build_wasm_lld
    shared.check_call(cmd, stdout=open(metadata_file, 'w'))
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/shared.py", line 155, in check_call
    subprocess.check_call(cmd, *args, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/google/home/sbc/dev/wasm/binaryen-out/install/bin/wasm-emscripten-finalize', '/tmp/tmpvUSZpv/a.out.bc.o.lld.wasm', '-o', '/tmp/tmpvUSZpv/a.out.bc.o.wasm', '--global-base=1024', '--emscripten-reserved-function-pointers=0', '-g', '--input-source-map=/tmp/tmpvUSZpv/a.out.bc.o.lld.wasm.map', '--output-source-map=/tmp/tmpvUSZpv/a.out.bc.o.wasm.map']' returned non-zero exit status 1
FAIL

======================================================================
FAIL: test_source_map (test_core.binaryen2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 28, in decorated
    return func(self)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 6999, in test_source_map
    Building.COMPILER_TEST_OPTS, out_filename)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/shared.py", line 2011, in emcc
    assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
AssertionError: emcc could not create output file: /tmp/emscripten_test_binaryen2_LgReDi/a.out.js

----------------------------------------------------------------------
Ran 1 test in 2.067s

FAILED (failures=1)
```

**Comment by sbc100** [comment]
@yurydelendik maybe you can help with this.  You need to set your LLVM to point to upstream LLVM build.
