### ISSUE TITLE
EMTERPRETIFY + SDL2 + emscripten_sleep = abort

### ISSUE THREAD

**Issue by Beuc** [kripken/emscripten#6727]
I'm trying to port an application without touching the main loop.

I'm adding emscripten_wait support to the SDL2 port this way:
```
diff --git a/src/timer/unix/SDL_systimer.c b/src/timer/unix/SDL_systimer.c
index 217fe327f..5d0337d0a 100644
--- a/src/timer/unix/SDL_systimer.c
+++ b/src/timer/unix/SDL_systimer.c
@@ -30,6 +30,8 @@
 #include "SDL_timer.h"
 #include "SDL_assert.h"
 
+#include <emscripten.h>
+
 /* The clock_gettime provides monotonous time, so we should use it if
    it's available. The clock_gettime function is behind ifdef
    for __USE_POSIX199309
@@ -186,6 +188,9 @@ SDL_GetPerformanceFrequency(void)
 void
 SDL_Delay(Uint32 ms)
 {
+#ifdef __EMSCRIPTEN__
+    emscripten_sleep(ms);
+#else
     int was_error;
 
 #if HAVE_NANOSLEEP
@@ -224,6 +229,7 @@ SDL_Delay(Uint32 ms)
         was_error = select(0, NULL, NULL, NULL, &tv);
 #endif /* HAVE_NANOSLEEP */
     } while (was_error && (errno == EINTR));
+#endif /* __EMSCRIPTEN__ */
 }
 
 #endif /* SDL_TIMER_UNIX */
```

and I'm compiling the "cube" example from the tutorial, modified for SDL2:
```
#include <stdio.h>
#include <SDL2/SDL.h>

void dummy(void) { printf("testing EMTERPRETIFY_BLACKLIST\n"); }

int main(int argc, char** argv) {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *sdlWindow = SDL_CreateWindow("test",
					   SDL_WINDOWPOS_UNDEFINED,
					   SDL_WINDOWPOS_UNDEFINED,
					   256, 256,
					   0);
  SDL_Renderer *sdlRenderer = SDL_CreateRenderer(sdlWindow, -1, 0);
  SDL_SetRenderDrawColor(sdlRenderer, 0, 0, 0, 255);
  SDL_RenderClear(sdlRenderer);
  SDL_RenderPresent(sdlRenderer);

  SDL_Surface* screen = SDL_CreateRGBSurface(0, 256,256, 32,
					    0x000000ff, 0x0000ff00, 0x00ff0000, 0xff000000);
  SDL_Texture* sdlTexture = SDL_CreateTexture(sdlRenderer,
					      SDL_PIXELFORMAT_ARGB8888,
					      SDL_TEXTUREACCESS_STREAMING,
					      256, 256);
  
  int count = 0;
  while (1) {
    count++;
    if (SDL_MUSTLOCK(screen)) SDL_LockSurface(screen);
    for (int i = 0; i < 256; i++) {
      for (int j = 0; j < 256; j++) {
	int alpha = 255;
	*((Uint32*)screen->pixels + i * 256 + j) = SDL_MapRGBA(screen->format, i, j, 255-i+count, alpha);
      }
    }
    if (SDL_MUSTLOCK(screen)) SDL_UnlockSurface(screen);
    
    SDL_UpdateTexture(sdlTexture, NULL, screen->pixels, 256 * sizeof (Uint32));
    SDL_RenderCopy(sdlRenderer, sdlTexture, NULL, NULL);
    SDL_RenderPresent(sdlRenderer);
    
    SDL_Event ev;
    SDL_WaitEvent(&ev);
    printf("got event\n");
    if (ev.type == SDL_QUIT)
      break;
  }

  printf("you should see a smoothly-colored square - no sharp lines but the square borders!\n");
  printf("and here is some text that should be HTML-friendly: amp: |&| double-quote: |\"| quote: |'| less-than, greater-than, html-like tags: |<cheez></cheez>|\nanother line.\n");

  SDL_Quit();

  dummy();

  return 0;
}
```

Normally -s EMTERPRETIFY should emterpret everything by default. Just to be sure of it, I'm adding a single "dummy" function to add to EMTERPRETIFY_BLACKLIST, though I tested with and without blacklist.

Compilation:
```
$ emcc cube2.c -o cube2.bc -s USE_SDL=2
$ EMCC_LOCAL_PORTS="sdl2=$HOME/workdir/emsource/ports/SDL2-version_13|SDL2-version_13" emcc cube2.bc -o t/index.html -s USE_SDL=2 -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 -s EMTERPRETIFY_FILE=t/index.em -s EMTERPRETIFY_BLACKLIST='["_dummy"]'
```

When running, mouse over and keyboard events work OK, but as soon as I click:
```
-12
localhost:8000:1249:13
uncaught exception: abort(-12) at jsStackTrace@http://localhost:8000/index.js:1016:13
stackTrace@http://localhost:8000/index.js:1033:12
abort@http://localhost:8000/index.js:10988:44
wasm-function[291]@http://localhost:8000/index.js:106366:1
wasm-function[290]@http://localhost:8000/index.js:75503:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
wasm-function[407]@http://localhost:8000/index.js:136944:1
wasm-function[766]@http://localhost:8000/index.js:153967:1
Module.dynCall_iiii@http://localhost:8000/index.js:10565:10
handlerFunc@http://localhost:8000/index.js:7112:30
jsEventHandler@http://localhost:8000/index.js:7010:11

This error happened during an emterpreter-async save or load of the stack. Was there non-emterpreted code on the stack during save (which is unallowed)? You may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST.
This is what the stack looked like when we tried to save it: 1,handle@http://localhost:8000/index.js:9678:40
_emscripten_sleep@http://localhost:8000/index.js:9703:7
wasm-function[290]@http://localhost:8000/index.js:104596:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
wasm-function[290]@http://localhost:8000/index.js:74035:1
Module.emterpret@http://localhost:8000/index.js:10505:10
resume@http://localhost:8000/index.js:9662:13
_emscripten_sleep/</<@http://localhost:8000/index.js:9706:11
```
or with WASM=0:
```
-12
localhost:8000:1249:13
uncaught exception: abort(-12) at jsStackTrace@http://localhost:8000/index.js:622:12
stackTrace@http://localhost:8000/index.js:636:11
abort@http://localhost:8000/index.js:27105:43
_malloc@http://localhost:8000/index.js:14448:15
emterpret@http://localhost:8000/index.js:10884:11
emterpret@http://localhost:8000/index.js:10848:4
emterpret@http://localhost:8000/index.js:10848:4
emterpret@http://localhost:8000/index.js:10848:4
emterpret@http://localhost:8000/index.js:10848:4
_Emscripten_HandleMouseButton@http://localhost:8000/index.js:20370:2
dynCall_iiii@http://localhost:8000/index.js:25234:9
handlerFunc@http://localhost:8000/index.js:6718:23
jsEventHandler@http://localhost:8000/index.js:6618:4

This error happened during an emterpreter-async save or load of the stack. Was there non-emterpreted code on the stack during save (which is unallowed)? You may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST.
This is what the stack looked like when we tried to save it: 1,handle@http://localhost:8000/index.js:9013:34
_emscripten_sleep@http://localhost:8000/index.js:9036:2
emterpret@http://localhost:8000/index.js:13317:6
emterpret@http://localhost:8000/index.js:10848:4
emterpret@http://localhost:8000/index.js:10848:4
emterpret@http://localhost:8000/index.js:10848:4
asm.emterpret@http://localhost:8000/index.js:26549:9
resume@http://localhost:8000/index.js:9000:5
_emscripten_sleep/</<@http://localhost:8000/index.js:9038:4
```
We ensured that all the code was emterpreted, but we get this error.
Any idea how to investigate further?

**Comment by kripken** [comment]
Build with `-profiling` to get more info in the stack trace (all calls should go through the function name, instead of just `emterpret`). Aside from that, I think `-12` might mean more than one thing (maybe we should use `-13` etc. too...) so I'd look at the code throwing the -12 to see what specifically it is complaining about.

**Comment by kripken** [comment]
Ah, actually I think it's just that malloc call. We don't emterpret malloc because we don't need to, it's in the default blacklist.

One option is to add malloc to `OK_TO_CALL_WHILE_ASYNC` in `tools/js-optimizer.js`. But I'm not sure offhand if that is ok to do. In general, it's ok to call say `memset` while async, as it just does some pure computation and is guaranteed to complete synchronously. That's generally true of malloc, except it does call `sbrk` when it needs to. Maybe just try adding malloc there, and see what happens, to start figuring this out?

**Comment by Beuc** [comment]
Thanks!
The abort is added by this part of js-optimizer.js:
```
        // add an assert in the prelude of the function
        var stats = getStatements(func);
        for (var i = 0; i < stats.length; i++) {
          var node = stats[i];
          if (node[0] == 'stat') node = node[1];
          if (node[0] !== 'var' && node[0] !== 'assign') {
            stats.splice(i, 0, ['stat',
              ['conditional', ['name', 'asyncState'], makeAsmCoercion(['call', ['name', 'abort'], [['num', '-12']]], ASM_INT), ['num', 0]]
            ]);
            break;
          }
        }
```

I tried adding `_malloc` to `OK_TO_CALL_WHILE_ASYNC` and the program behaves correctly.
I don't know why SDL2's mousebutton handle triggered this and not the other events (which are similarly implemented AFAICS).

More importantly I didn't realize there were limitations on calling the main program during the emscripten_sleep(), typically during registered event callbacks (html5.h). I'm not sure what's the worst case scenario if sbrk() is called async.
Do I need to e.g. I ditch all the SDL2 DOM even callbacks, have the DOM events temporarily stored in a JS array, and process them when going back from emscripten_sleep() ?

**Comment by kripken** [comment]
I'm not sure - this is complicated. Been a while since I worked on this, so I may not remember all the details.

Overall, the "simple" case is you do an `emscripten_sleep` and wait for some XHR or other browser async event, and then you resume the compiled code. In that case, no compiled code runs during the sleep.

Now imagine that someone calls some compiled code (from JS) during that sleep. It's violating the program's assumptions of how code should execute - that sleep should behave like a synchronous operation, with nothing happening in the middle. For example
```
int global = 0;

int func() {
  global = 1;
  emscripten_sleep();
  return global;
}

int confuse() {
  global = 2;
}
```
Here `func` should return 1 (unless the program is multithreaded, which it is not). But if JS calls `confuse` during the sleep, that changes.

On the other hand, if you have an event handler like here, then you do want other code to run. Another example is coroutines.

Overall, I think we may want to add an option, `EMTERPRETIFY_ALLOW_EXEC_DURING_ASYNC` (or a better name). That -12 error could point to it, and it would make sense to enable it for event handlers and coroutines, but not by default. But, this needs more thought - not sure I have the time to get into it myself.

**Comment by curiousdannii** [comment]
Is the problem that the handler is also calling Emterpreter code? I've been able to call from JS exposed functions which call malloc while the Emterpreter is paused.

**Comment by kripken** [comment]
@curiousdannii I think we actually just let it run emterpreter code, although I'm not sure that's the right behavior. But calling un-emterpreted malloc should fail currently, unless assertions are off.

I suspect we may want to just remove those assertions and document this more.

**Comment by curiousdannii** [comment]
Ah, yes I've been doing it assertions off.

**Comment by kripken** [comment]
I opened #6749 to improve that -12 error: we really should just check it during a pause/resume, and not during a sleep. Please check if that PR resolves this issue for you.

**Comment by Beuc** [comment]
The "cube" example works with "minus_12".
In addition the error message is now more accurate, since it is really only used when saving/restoring the stack and not when running async code (that was confusing before).

Note: when trying to save a stack containing some non-emtrepreter functions, I got a cryptic `abort("Assertion failed: undefined") at jsStackTrace` (should be "Assertion failed: EmterpreterAsync.state === 2") but I believe something is unrelatedly broken with assert messages right now.

**Comment by kripken** [comment]
@Beuc thanks for checking! And yeah, it would be good to improve those assertion messages, PR would be very welcome.

**Comment by TrevorSundberg** [comment]
We're having this happen too. I added `_malloc` to the `OK_TO_CALL_WHILE_ASYNC ` and it changed into getting an abort -12 on _HandleAudioProcess. From your conversations, I just want to check if it's currently feasible to use SDL + EMTERPRETIFY. If not, it just means we need to do a few major refactors. Thanks for any help. If there's anything else I can grab that would be helpful (like wasm text) let me know.

Firefox on Windows prints:
```
-12
ZeroEditor.html:192:11
printErr
http://127.0.0.1:8080/ZeroEditor.html:192:11
abort
http://127.0.0.1:8080/ZeroEditor.js:24598:5
_HandleAudioProcess
http://127.0.0.1:8080/ZeroEditor.js:25513384:1
dynCall_vi
http://127.0.0.1:8080/ZeroEditor.js:41938071:1
Module.dynCall_vi
http://127.0.0.1:8080/ZeroEditor.js:24166:10
dynCall
http://127.0.0.1:8080/ZeroEditor.js:523:12
ASM_CONSTS</SDL2.audio.scriptProcessorNode.onaudioprocess
http://127.0.0.1:8080/ZeroEditor.js:2002:303
window.onerror

uncaught exception: abort(-12) at jsStackTrace@http://127.0.0.1:8080/ZeroEditor.js:1208:13 stackTrace@http://127.0.0.1:8080/ZeroEditor.js:1225:12 abort@http://127.0.0.1:8080/ZeroEditor.js:24608:44 _HandleAudioProcess@http://127.0.0.1:8080/ZeroEditor.js:25513384:1 dynCall_vi@http://127.0.0.1:8080/ZeroEditor.js:41938071:1 Module.dynCall_vi@http://127.0.0.1:8080/ZeroEditor.js:24166:10 dynCall@http://127.0.0.1:8080/ZeroEditor.js:523:12 ASM_CONSTS</SDL2.audio.scriptProcessorNode.onaudioprocess@http://127.0.0.1:8080/ZeroEditor.js:2002:303 window.onerror@http://127.0.0.1:8080/ZeroEditor.html:289:9 This error happened during an emterpreter-async save or load of the stack. Was there non-emterpreted code on the stack during save (which is unallowed)? You may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST. This is what the stack looked like when we tried to save it: 1,handle@http://127.0.0.1:8080/ZeroEditor.js:10740:40 _emscripten_sleep@http://127.0.0.1:8080/ZeroEditor.js:10765:7 emterpret@http://127.0.0.1:8080/ZeroEditor.js:990527:1 emterpret@http://127.0.0.1:8080/ZeroEditor.js:973253:1 emterpret@http://127.0.0.1:8080/ZeroEditor.js:973253:1 emterpret@http://127.0.0.1:8080/ZeroEditor.js:973253:1 emterpret@http://127.0.0.1:8080/ZeroEditor.js:973253:1 emterpret@http://127.0.0.1:8080/ZeroEditor.js:973253:1 emterpret@http://127.0.0.1:8080/ZeroEditor.js:973253:1 Module.emterpret@http://127.0.0.1:8080/ZeroEditor.js:23910:10 resume@http://127.0.0.1:8080/ZeroEditor.js:10724:13 _emscripten_sleep/</<@http://127.0.0.1:8080/ZeroEditor.js:10768:11
```
And Chrome prints:
```
ZeroEditor.js:24614 Uncaught abort(-12) at Error
    at jsStackTrace (http://127.0.0.1:8080/ZeroEditor.js:1208:13)
    at stackTrace (http://127.0.0.1:8080/ZeroEditor.js:1225:12)
    at abort (http://127.0.0.1:8080/ZeroEditor.js:24608:44)
    at _SDL_AtomicGet (wasm-function[49083]:9)
    at emterpret (wasm-function[518]:20021)
    at _HandleCaptureProcess (wasm-function[52956]:35)
    at dynCall_vi (wasm-function[54582]:15)
    at Module.dynCall_vi (http://127.0.0.1:8080/ZeroEditor.js:24166:38)
    at Object.dynCall (http://127.0.0.1:8080/ZeroEditor.js:523:37)
    at silence_callback (http://127.0.0.1:8080/ZeroEditor.js:2001:1172)
This error happened during an emterpreter-async save or load of the stack. Was there non-emterpreted code on the stack during save (which is unallowed)? You may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST.
This is what the stack looked like when we tried to save it: 1,Error
    at Object.handle (http://127.0.0.1:8080/ZeroEditor.js:10740:40)
    at _emscripten_sleep (http://127.0.0.1:8080/ZeroEditor.js:10765:24)
    at emterpret (wasm-function[518]:20421)
    at emterpret (wasm-function[518]:3147)
    at emterpret (wasm-function[518]:3147)
    at emterpret (wasm-function[518]:3147)
    at emterpret (wasm-function[518]:3147)
    at emterpret (wasm-function[518]:3147)
    at emterpret (wasm-function[518]:3147)
    at Object.Module.emterpret (http://127.0.0.1:8080/ZeroEditor.js:23910:37)
    at resume (http://127.0.0.1:8080/ZeroEditor.js:10724:32)
    at http://127.0.0.1:8080/ZeroEditor.js:10768:11

abort	@	ZeroEditor.js:24614
_SDL_AtomicGet	@	wasm-0b79b9f6-49083:6
emterpret	@	wasm-0b79b9f6-518:9965
_HandleCaptureProcess	@	wasm-0b79b9f6-52956:20
dynCall_vi	@	wasm-0b79b9f6-54582:8
Module.dynCall_vi	@	ZeroEditor.js:24166
dynCall	@	ZeroEditor.js:523
silence_callback	@	ZeroEditor.js:2001
setTimeout (async)		
ASM_CONSTS	@	ZeroEditor.js:2001
_emscripten_asm_const_iiiii	@	ZeroEditor.js:2013
emterpret	@	wasm-0b79b9f6-518:9443
_EMSCRIPTENAUDIO_OpenDevice	@	wasm-0b79b9f6-45376:29
emterpret	@	wasm-0b79b9f6-518:6766
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
__ZN4Zero11SoundSystem10InitializeERNS_17SystemInitializerE	@	wasm-0b79b9f6-48748:23
emterpret	@	wasm-0b79b9f6-518:4293
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
Module.emterpret	@	ZeroEditor.js:23910
resume	@	ZeroEditor.js:10724
(anonymous)	@	ZeroEditor.js:10768
setTimeout (async)		
(anonymous)	@	ZeroEditor.js:10766
handle	@	ZeroEditor.js:10696
_emscripten_sleep	@	ZeroEditor.js:10765
emterpret	@	wasm-0b79b9f6-518:10171
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
emterpret	@	wasm-0b79b9f6-518:1671
_main	@	wasm-0b79b9f6-49624:23
Module._main	@	ZeroEditor.js:23850
callMain	@	ZeroEditor.js:24428
doRun	@	ZeroEditor.js:24492
(anonymous)	@	ZeroEditor.js:24503
setTimeout (async)		
run	@	ZeroEditor.js:24499
runCaller	@	ZeroEditor.js:24404
removeRunDependency	@	ZeroEditor.js:1675
receiveInstance	@	ZeroEditor.js:1845
receiveInstantiatedSource	@	ZeroEditor.js:1870
Promise.then (async)		
instantiateArrayBuffer	@	ZeroEditor.js:1875
(anonymous)	@	ZeroEditor.js:1892
Promise.catch (async)		
doNativeWasm	@	ZeroEditor.js:1887
Module.asm	@	ZeroEditor.js:1975
(anonymous)	@	ZeroEditor.js:13567
```

**Comment by kripken** [comment]
This should have been fixed by #6749, so it should work now (and I think we can close the issue). However, we haven't tagged a new version since then, so unless you are using latest incoming, you still get the old behavior.

You can use incoming in emscripten with binaries for the latest tag. However, we should probably just create a new tag anyhow, I'll do that later today after CI is green.

**Comment by TrevorSundberg** [comment]
Thanks for the quick reply as always. I didn't realize "minus_12" was a branch name haha.

**Comment by kripken** [comment]
Ok, 1.38.8 contains this fix, and after a temporary issue with 1.38.7, looks like we're back to normal. Closing this issue.

**Comment by TrevorSundberg** [comment]
Not sure if this should be re-opened, I just built with 1.38.8 and I'm getting this still:

Chrome on Windows:
```
-12
ZeroEditor.html:192 -12
printErr @ ZeroEditor.html:192
abort @ ZeroEditor.js:25184
_HandleCaptureProcess @ wasm-0d9853aa-26469:12
dynCall_vi @ wasm-0d9853aa-54728:8
Module.dynCall_vi @ ZeroEditor.js:24753
dynCall @ ZeroEditor.js:531
silence_callback @ ZeroEditor.js:2003
setTimeout (async)
ASM_CONSTS @ ZeroEditor.js:2003
_emscripten_asm_const_iiiii @ ZeroEditor.js:2015
_EMSCRIPTENAUDIO_OpenDevice @ wasm-0d9853aa-10154:405
_open_audio_device @ wasm-0d9853aa-1839:1771
_SDL_OpenAudioDevice @ wasm-0d9853aa-50169:21
__ZN4Zero16AudioInputOutput16InitializeStreamENS_11StreamTypes4EnumEPNS_6StringE @ wasm-0d9853aa-5123:461
__ZN5Audio16AudioIOInterface10InitializeEv @ wasm-0d9853aa-23509:142
__ZN5Audio19AudioSystemInternal11StartSystemERN4Zero13StatusContextIjEE @ wasm-0d9853aa-5800:52
__ZN5Audio20AudioSystemInterface11StartSystemERN4Zero13StatusContextIjEE @ wasm-0d9853aa-48827:18
__ZN4Zero11SoundSystem10InitializeERNS_17SystemInitializerE @ wasm-0d9853aa-10683:126
__ZN4Zero6Engine10InitializeERNS_17SystemInitializerE @ wasm-0d9853aa-6924:223
emterpret @ wasm-0d9853aa-1302:6164
emterpret @ wasm-0d9853aa-1302:1190
emterpret @ wasm-0d9853aa-1302:1190
Module.emterpret @ ZeroEditor.js:24497
resume @ ZeroEditor.js:11106
(anonymous) @ ZeroEditor.js:11160
setTimeout (async)
(anonymous) @ ZeroEditor.js:11158
handle @ ZeroEditor.js:11075
_emscripten_sleep @ ZeroEditor.js:11157
emterpret @ wasm-0d9853aa-1302:7595
emterpret @ wasm-0d9853aa-1302:1190
emterpret @ wasm-0d9853aa-1302:1190
emterpret @ wasm-0d9853aa-1302:1190
_main @ wasm-0d9853aa-52503:23
Module._main @ ZeroEditor.js:24437
callMain @ ZeroEditor.js:25018
doRun @ ZeroEditor.js:25082
(anonymous) @ ZeroEditor.js:25093
setTimeout (async)
run @ ZeroEditor.js:25089
runCaller @ ZeroEditor.js:24994
removeRunDependency @ ZeroEditor.js:1684
receiveInstance @ ZeroEditor.js:1847
receiveInstantiatedSource @ ZeroEditor.js:1872
```

Is this the same issue?

**Comment by kripken** [comment]
I suspect that's the same as #6818 and/or #6820
