### ISSUE TITLE
SDL touch event generate abort.

### ISSUE THREAD

**Issue by cingelmarekmt** [kripken/emscripten#6925]
Hi, my WebApp generate abort in touch mode.

Actual settings:
CXX FLAGS:  -O0 -s WASM=0 -g4  -s ASSERTIONS=1 -s SAFE_HEAP=1 -s DETERMINISTIC=1 -s ALIASING_FUNCTION_POINTERS=0 -fdiagnostics-format=msvc -Wno-almost-asm -Wno-unused-value -Wno-ignored-attributes --memory-init-file 1 -std=c++14 -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 --bind -s USE_SDL=2 -s USE_SDL_IMAGE=2  -s USE_SDL_TTF=2 -s USE_ZLIB=1 --no-heap-copy --preload-file ../../Assets/@/Assets/ --preload-file ../..//Platform/@/Platform/ --preload-file ../../Shaders/@/Shaders/  --use-preload-plugins 

LINKER FLAGS: --bind -O0 -s WASM=0 -g4 -s ASSERTIONS=1 -s SAFE_HEAP=1 -s DETERMINISTIC=1 -s ALIASING_FUNCTION_POINTERS=0 -s NO_EXIT_RUNTIME=1 -s SDL2_IMAGE_FORMATS=['png'] --shell-file shell_minimal.html --llvm-lto 0 

Console output: 

[post-exception status] Exception thrown, see JavaScript console
printErr @ index.html:146
Module.setStatus @ index.html:192
window.onerror @ index.html:189
error (async)
(anonymous) @ index.html:186

Uncaught abort() at Error
    at jsStackTrace (http://192.168.33.104/index.js:1339:13)
    at stackTrace (http://192.168.33.104/index.js:1356:12)
    at Object.abort (http://192.168.33.104/index.js:1641160:44)
    at _abort (http://192.168.33.104/index.js:7949:22)
    at _malloc (http://192.168.33.104/index.js:168624:11)
    at _SDL_malloc (http://192.168.33.104/index.js:1621959:7)
    at _SDL_PeepEvents (http://192.168.33.104/index.js:834289:15)
    at _SDL_PushEvent (http://192.168.33.104/index.js:1489251:7)
    at _SDL_SendTouchMotion (http://192.168.33.104/index.js:1138580:14)
    at Array._Emscripten_HandleTouch (http://192.168.33.104/index.js:1136575:6)http://192.168.33.104/index.js16411663abort() at Error
    at jsStackTrace (http://192.168.33.104/index.js:1339:13)
    at stackTrace (http://192.168.33.104/index.js:1356:12)
    at Object.abort (http://192.168.33.104/index.js:1641160:44)
    at _abort (http://192.168.33.104/index.js:7949:22)
    at _malloc (http://192.168.33.104/index.js:168624:11)
    at _SDL_malloc (http://192.168.33.104/index.js:1621959:7)
    at _SDL_PeepEvents (http://192.168.33.104/index.js:834289:15)
    at _SDL_PushEvent (http://192.168.33.104/index.js:1489251:7)
    at _SDL_SendTouchMotion (http://192.168.33.104/index.js:1138580:14)
    at Array._Emscripten_HandleTouch (http://192.168.33.104/index.js:1136575:6)

Thank you so much for the speedy reply.

**Comment by cingelmarekmt** [comment]
My mistake in code.
