### ISSUE TITLE
Building OpenSSL Windows

### ISSUE THREAD

**Issue by treytencarey** [kripken/emscripten#6970]
I can't seem to build OpenSSL on Windows for Emscripten.

**FIrst I need to do ./config**:

In Command Prompt, I am unable to run emconfigure:

> C:\Users\Admin\Desktop\Proj\libs\openssl>emconfigure ./config
> 
>   emconfigure is a helper for configure, setting various environment
>   variables so that emcc etc. are used. Typical usage:
> 
>     emconfigure ./configure [FLAGS]
> 
>   (but you can run any command instead of configure)
> 
> 
> ERROR:root:Error running configure: "./config"
> Traceback (most recent call last):
>   File "c:\emsdk\emscripten\1.38.10\emconfigure.py", line 52, in <module>
>     run()
>   File "c:\emsdk\emscripten\1.38.10\emconfigure.py", line 47, in run
>     shared.Building.configure(sys.argv[1:])
>   File "c:\emsdk\emscripten\1.38.10\tools\shared.py", line 1689, in configure
>     res = run_process(args, check=False, stdout=stdout, stderr=stderr, env=env)
>   File "c:\emsdk\emscripten\1.38.10\tools\shared.py", line 167, in run_process
>     return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
>   File "c:\emsdk\emscripten\1.38.10\tools\shared.py", line 158, in run_base
>     proc = Popen(cmd, *args, **kw)
>   File "c:\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "c:\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
>     startupinfo)
> WindowsError: [Error 193] %1 is not a valid Win32 application

Running in Cygwin, as suggested [here](https://github.com/kripken/emscripten/issues/4354) works great.

After running "./emconfigure ./config" in Cygwin, I need to do make.
**Running "emmake make" in Command Prompt results in error**:

> C:\Users\Admin\Desktop\Proj\libs\openssl>emmake make
> C:/MinGW/bin/mingw32-make depend && C:/MinGW/bin/mingw32-make _all
> mingw32-make[1]: Entering directory 'C:/Users/Admin/Desktop/Proj/libs/openssl'
> process_begin: CreateProcess(NULL, /perl64 ./util/add-depends.pl makedepend, ...) failed.
> make (e=5): Access is denied.
> Makefile:264: recipe for target 'depend' failed
> mingw32-make[1]: *** [depend] Error 5
> mingw32-make[1]: Leaving directory 'C:/Users/Admin/Desktop/Proj/libs/openssl'
> Makefile:171: recipe for target 'all' failed
> mingw32-make: *** [all] Error 2

I have modified the OpenSSL Makefile to run different locations of perl as well as checked my permissions and ran from an Administrative Command Prompt, which only results in errors.

**Running "emmake make" with Cygwin results in error**:

> module.js:538
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\cygdrive\c\emsdk\emscripten\1.38.10\src\hello_world.js'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
> INFO:root:Checking JS engine ['c:/emsdk/node/8.9.1_64bit/bin/node.exe'] failed. Check your config file. Details: Expected the command ['c:/emsdk/node/8.9.1_64bit/bin/node.exe', '/cygdrive/c/emsdk/emscripten/1.38.10/src/hello_world.js'] to finish with return code 0, but it returned with code 1 instead! Output:
> WARNING:root:did not see a source tree above or next to the LLVM root directory (guessing based on directory of c:/emsdk/clang/e1.38.10_64bit/llc), could not verify version numbers match
> INFO:root:(Emscripten: Running sanity checks)
> ERROR:root:The JavaScript shell used for compiling (['c:/emsdk/node/8.9.1_64bit/bin/node.exe']) does not seem to work, check the paths in C:\Users\Admin\.emscripten
> make[1]: *** [Makefile:1611: crypto/cversion.o] Error 1
> make[1]: Leaving directory '/cygdrive/c/Users/Admin/Desktop/Proj/libs/openssl'
> make: *** [Makefile:171: all] Error 2

The suggested solutions from [here](https://github.com/kripken/emscripten/issues/800) and [here](https://github.com/kripken/emscripten/issues/3947) did not solve my issues.

Similar to Command Prompt, running emconfigure and emmake on MSYS also failed.

**Comment by treytencarey** [comment]
Note that I am able to build OpenSSL without Emscripten using Cygwin, but then I cannot link OpenSSL to my Emscripten project due to different architectures.
