### ISSUE TITLE
consider changing function print order when DEMANGLE_SUPPORT=1

### ISSUE THREAD

**Issue by vvuk** [kripken/emscripten#7104]
Right now, when there are mangled names, in the stack, the demangled name is printed after the mangled one:

```
      at jsStackTrace (../build/webgl/Debug/runtime/RuntimeTesting.js:1053:13)
      at stackTrace (../build/webgl/Debug/runtime/RuntimeTesting.js:1070:12)
      at abort (../build/webgl/Debug/runtime/RuntimeTesting.js:194393:44)
      at ___assert_fail (../build/webgl/Debug/runtime/RuntimeTesting.js:1689:7)
      at __ZN2ut12assertFailedEPKcS1_S1_j [ut::assertFailed(char const*, char const*, char const*, unsigned int)] (../build/webgl/Debug/runtime/RuntimeTesting.js:135133:2)
      at __ZN2ut10TestHelper17TestHelperService21addVectorsInComponentEPNS_12ManagerWorldENS_6EntityE [ut::TestHelper::TestHelperService::addVectorsInComponent(ut::ManagerWorld*, ut::Entity)] (../build/webgl/Debug/runtime/RuntimeTesting.js:56855:2)
      at _ut_TestHelper_TestHelperService_addVectorsInComponent (../build/webgl/Debug/runtime/RuntimeTesting.js:55442:2)
      at Object.<anonymous>.asm._ut_TestHelper_TestHelperService_addVectorsInComponent (../build/webgl/Debug/runtime/RuntimeTesting.js:193051:70)
      at Function.Object.<anonymous>.ut.TestHelper.TestHelperService.addVectorsInComponent (../build/webgl/Debug/runtime/RuntimeTesting.js:204278:10)
```

This is not super useful -- mangled names are often quite long (as are the demangled ones), and when scanning a stack trace you want to quickly see what the functions are in the stack.  I'd suggest changing the order around to make it easier to scan down the list to see what the functions are (even more apparent when there's more functions ni the stack):

```
      at jsStackTrace (../build/webgl/Debug/runtime/RuntimeTesting.js:1053:13)
      at stackTrace (../build/webgl/Debug/runtime/RuntimeTesting.js:1070:12)
      at abort (../build/webgl/Debug/runtime/RuntimeTesting.js:194393:44)
      at ___assert_fail (../build/webgl/Debug/runtime/RuntimeTesting.js:1689:7)
      at ut::assertFailed(char const*, char const*, char const*, unsigned int) [__ZN2ut12assertFailedEPKcS1_S1_j]  (../build/webgl/Debug/runtime/RuntimeTesting.js:135133:2)
      at ut::TestHelper::TestHelperService::addVectorsInComponent(ut::ManagerWorld*, ut::Entity) [__ZN2ut10TestHelper17TestHelperService21addVectorsInComponentEPNS_12ManagerWorldENS_6EntityE] (../build/webgl/Debug/runtime/RuntimeTesting.js:56855:2)
      at _ut_TestHelper_TestHelperService_addVectorsInComponent (../build/webgl/Debug/runtime/RuntimeTesting.js:55442:2)
      at Object.<anonymous>.asm._ut_TestHelper_TestHelperService_addVectorsInComponent (../build/webgl/Debug/runtime/RuntimeTesting.js:193051:70)
      at Function.Object.<anonymous>.ut.TestHelper.TestHelperService.addVectorsInComponent (../build/webgl/Debug/runtime/RuntimeTesting.js:204278:10)
```

**Comment by kripken** [comment]
Good idea, I opened #7114
