### ISSUE TITLE
SDL1 implementation does not setCanvasSize, leading to oddities when resizing

### ISSUE THREAD

**Issue by Sgeo** [kripken/emscripten#7212]
While trying to port VICE, I encountered an issue where, if the `<canvas>` element had a `width` and `height`, `SDL_SetVideoMode` would not call `Browser.setCanvasSize()`, which resulted in there being no `widthNative` and `heightNative`, which broke fullscreen mode.

https://github.com/kripken/emscripten/blob/41087cf702e4d3347c968d83df43fb97b5b109f4/src/library_sdl.js#L1471

**Comment by FMFluke** [comment]
Hi, I am new here. Am I allowed to work on this as my first contribution?

**Comment by kripken** [comment]
Hi @FMFluke, yes! Feel free to work on any open issues not marked as being worked on by someone else, including this one.

**Comment by FMFluke** [comment]
@kripken Hi! Ok I will do, do you have any hint or suggestion where to look? I am still new to this project.

**Comment by kripken** [comment]
A good starting point might be to search for `setCanvasSize` in `src/*`, to see where it is defined and how it is used. Then I'd try to create a testcase that shows the problem described here. And then try to fix it (as mentioned above, maybe adding a call to that method in `SDL_SetVideoMode` is enough?).

**Comment by FMFluke** [comment]
@kripken I looked the definition and figured that this problem can be solved by removing the conditions so that `setCanvasSize` is always called even if setting to the same size. What I got stuck with is how to actually test it. I tried to run `test_sdl_canvas_size` in `test_browser` but somehow it fails even without editing anything yet.

**Comment by kripken** [comment]
What specific error do you get when you run `browser.test_sdl1`?

**Comment by FMFluke** [comment]
These are exact output from terminal after trying to run the test with `python tests/runner.py browser.test_sdl1`

`======================================================================
ERROR: test_sdl1 (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fluke/emsdk/emscripten/incoming/tests/test_browser.py", line 120, in test_sdl1
    self.btest('hello_world_sdl.cpp', reference='htmltest.png', args=['-lSDL', '-lGL'])
  File "/Users/fluke/emsdk/emscripten/incoming/tests/runner.py", line 1117, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "/Users/fluke/emsdk/emscripten/incoming/tests/runner.py", line 980, in run_browser
    self.assertIdentical(expectedResult, output)
  File "/Users/fluke/emsdk/emscripten/incoming/tests/runner.py", line 635, in assertIdentical
    limit_size(''.join([a.rstrip() + '\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected', tofile='actual')]))
Exception: Expected to have '/report_result?0' == '[no http server activity]', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+[no http server activity]`

**Comment by FMFluke** [comment]
Nothing there except 404 `localhost:9999/check` not found, which happens recursively after the test has failed until I close the browser tab (and the text running test xx in `/run_harness` also starting running on and on too).

**Comment by FMFluke** [comment]
Update: I am able to reproduce the bug and also implement fix, and tested that it works by compiling and running the test case manually like in tutorial. Since this will be interactive test anyway (requires clicking to enter full screen) I believed this is already completed. The normal random test cases has been run without any problems. Can I create a pull request?

**Comment by kripken** [comment]
@FMFluke yes, please go ahead and create a PR, thanks! And we'll discuss the details in there.

**Comment by FMFluke** [comment]
Ok, I have done that.
