### ISSUE TITLE
Compiler crash in emscripten.py when EXPORT_FUNCTION_TABLES=1

### ISSUE THREAD

**Issue by yyamdev** [kripken/emscripten#7532]
Hello, I'm having some trouble trying to get emscripten to export function tables in a "side module". Perhaps what I'm trying to do doesn't make sense? Either way, it probably shouldn't crash the compiler. Here's a minimal example I found:

test.cpp:
```
int add(int a, int b)
{
    return a + b;
}
```
Build command:
`em++ test.cpp -s SIDE_MODULE=1 -s EXPORT_FUNCTION_TABLES=1`

Result:
```
WARNING:root:output suffix .js requested, but wasm side modules are just wasm files; emitting only a .wasm, no .js
Traceback (most recent call last):
  File "C:\dev\emsdk\emscripten\1.38.13\emcc.py", line 3092, in <module>
    sys.exit(run())
  File "C:\dev\emsdk\emscripten\1.38.13\emcc.py", line 1808, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\dev\emsdk\emscripten\1.38.13\tools\shared.py", line 2253, in emscripten
    emscripten._main(cmdline)
  File "C:\dev\emsdk\emscripten\1.38.13\emscripten.py", line 2328, in _main
    return temp_files.run_and_clean(lambda: main(
  File "C:\dev\emsdk\emscripten\1.38.13\tools\tempfiles.py", line 98, in run_and_clean
    return func()
  File "C:\dev\emsdk\emscripten\1.38.13\emscripten.py", line 2333, in <lambda>
    DEBUG=DEBUG,
  File "C:\dev\emsdk\emscripten\1.38.13\emscripten.py", line 2259, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "C:\dev\emsdk\emscripten\1.38.13\emscripten.py", line 105, in emscript
    function_tables_and_exports(funcs, metadata, mem_init, glue, forwarded_data, outfile, DEBUG))
  File "C:\dev\emsdk\emscripten\1.38.13\emscripten.py", line 260, in function_tables_and_exports
    all_exported_functions = get_all_exported_functions(function_table_data)
  File "C:\dev\emsdk\emscripten\1.38.13\emscripten.py", line 608, in get_all_exported_functions
    if func[0] == '_':
IndexError: string index out of range
```

If I set either SIDE_MODULE or EXPORT_FUNCTION_TABLES to 0, then the problem goes away.

em++ -v:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.13
clang version 6.0.1  (emscripten 1.38.13 : 1.38.13)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\dev\emsdk\clang\e1.38.13_64bit
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by kripken** [comment]
I think the EXPORT_FUNCTION_TABLES option does not make sense for wasm - we should show a clear error in that case, I agree.
