### ISSUE TITLE
test_binaryen_methods failing on wasm waterfall

### ISSUE THREAD

**Issue by sbc100** [kripken/emscripten#7652]
Not really sure whats going on there but the exception is:

```
exception thrown: TypeError: Cannot read property 'apply' of undefined,TypeError: Cannot read property 'apply' of undefined
    at Array.<anonymous> (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:25:279)
    at am (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:62:436)
    at Array.Iv (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:74:58029)
    at Object.RPa [as dynCall_viiiiii] (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:77:158449)
    at z (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:56:394)
    at Fo (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:70:41288)
    at wg (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:75:139539)
    at _u (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:74:36738)
    at Ot (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:70:256510)
    at wg (/tmp/tmpaz3YZh/emscripten_test_other_Mw1Oh4/a.wasm.js:75:139613)
test_binaryen_methods (test_other.other) ... ERROR
```

**Comment by kripken** [comment]
Strange, I can't reproduce this on a local build (latest llvm, lld, emscripten, binaryen, v8).

Note that that test is not highly important - it checks the binaryen interpreter. If this is hard to debug we may want to just remove that feature.

**Comment by sbc100** [comment]
I can't repro yet either.

**Comment by sbc100** [comment]
https://logs.chromium.org/logs/chromium/bb/client.wasm.llvm/linux/37898/+/recipes/steps/Execute_emscripten_testsuite__emwasm_/0/stdout

**Comment by sbc100** [comment]
Looks like its fixed itself :)
