### ISSUE TITLE
"fatal error: 'xlocinfo.h' file not found" when trying to compile code to WebAssembly

### ISSUE THREAD

**Issue by DragonOsman** [kripken/emscripten#7685]
I tried to compile this code:
```cpp
// Osman Zakir
// 12 / 19 / 2017
// Bjarne Stroustrup: Programming: Principles and Practice Using C++ 2nd Edition
// Chapter 21 Exercise 3
// This program implements a custom count algorithm and tests it
// Exercise Specifications:
/**
 * Implement count() yourself. Test it.
 */

#include <iostream>
#include <iterator>
#include <algorithm>
#include <string>
#include <vector>
#include <list>
#include <stdexcept>
#include "../../cust_std_lib_facilities.h"

namespace my
{
	template<typename Input_Iter, typename T>
	std::ptrdiff_t count(Input_Iter first, Input_Iter last, const T &val);
}

int main()
{
	std::vector<int> myvec{1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 6, 6, 7, 7, 7, 7, 8, 9, 9, 10, 10, 10};
	constexpr int key = 3;
	auto num_occur = std::count(myvec.begin(), myvec.end(), key);
	auto num_occur2 = my::count(myvec.begin(), myvec.end(), key);
	std::cout << "Number of occurrences of " << key << " in myvec using std::count is " << num_occur
		<< " and is " << num_occur2 << " using my::count\n";
	keep_window_open();
}

template<typename Input_Iter, typename T>
std::ptrdiff_t my::count(Input_Iter first, Input_Iter last, const T &val)
// Requires Input_Iterable<C> 
            // && Container<C>
	        // && Equality_comparable<T>
/**
 * pre: first and last must point to an iterable, non-empty container
 * post: return a number of occurrences of given value
 */
{
	std::ptrdiff_t res{};
	while (first != last)
	{
		if (val == *first)
		{
			++res;
		}
		++first;
	}
	return res;
}
```
using `em++` with this command: 
```
em++ -Wall -pedantic -D_WIN32 -D_WIN32_WINDOWS -D_NDEBUG -m64 -IE:\programming\visual_studio_2017\Projects\programming_principles_practice_using_c++ -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_my::count'] main.cpp -o main.html
```
and I got this error: 
```
fatal error: 'xlocinfo.h' file not found
1 error generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
```
What should I do?  Is there no way to have it use the regular MSVC headers that my computer has (or will that not work with Emscripten?)?

By the way, for reference, this is my .emscripten file:
```
import os
LLVM_ROOT='C:/Program Files (x86)/LLVM/bin/'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/Users/Osman/emsdk/clang/e1.38.20_64bit/optimizer.exe'
BINARYEN_ROOT='C:/Users/Osman/emsdk/clang/e1.38.20_64bit/binaryen'
NODE_JS='C:/Program Files/nodejs/node.exe'
PYTHON='C:/Python27/python.exe'
JAVA='C:/Users/Osman/emsdk/java/8.152_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='C:/Users/Osman/emsdk/emscripten/1.38.20'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = 'E:/v8_dev/v8'
TEMP_DIR = 'c:/users/osman/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```
I built LLVM 8.0.0 from the Git monorepo and had it target WebAssembly, and then I set the `EMCC_WASM_BACKEND=1` environment variable.  If there are problems with my .emscripten file, please let me know.  

There's an "opt.exe` in the LLVM bin directory.  Is that the optimizer?  Should I use that instead of the Emscripten one, if so?

**Comment by DragonOsman** [comment]
Okay, never mind, I'd forgotten to put in the .cpp file for `cust_std_lib_facilities.h`.  But when I add the path to that file into the build command, I got this output from Emscripten:
```
em++ -Wall -pedantic -D_WIN32 -D_WIN32_WINDOWS -D_NDEBUG -m64 -IE:\programming\visual_studio_2017\Projects\programming_principles_practice_using_c++ -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_my::count'] main.cpp E:\programming\visual_studio_2017\Projects\programming_principles_practice_using_c++/cust_std_lib_facilities.h -o main.html
shared:DEBUG: EMCC_WASM_BACKEND tells us to use wasm backend
emcc:WARNING: invocation: C:\Users\Osman\emsdk\emscripten\1.38.20\emcc.py -Wall -pedantic -D_WIN32 -D_WIN32_WINDOWS -D_NDEBUG -m64 -IE:\programming\visual_studio_2017\Projects\programming_principles_practice_using_c++ -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_my::count'] main.cpp E:\programming\visual_studio_2017\Projects\programming_principles_practice_using_c++/cust_std_lib_facilities.h -o main.html --emscripten-cxx  (in E:\programming\visual_studio_2017\Projects\programming_principles_practice_using_c++\chapter21ex3\chapter21ex3)
root:DEBUG: Checking JS engine ['C:/Program Files/nodejs/node.exe']
shared:INFO: (Emscripten: Running sanity checks)
emcc:DEBUG: compiling to bitcode
emcc:DEBUG: emcc step "parse arguments and setup" took 0.61 seconds
Traceback (most recent call last):
  File "C:\Users\Osman\emsdk\emscripten\1.38.20\emcc.py", line 3094, in <module>
    sys.exit(run())
  File "C:\Users\Osman\emsdk\emscripten\1.38.20\emcc.py", line 1459, in run
    assert header.endswith(HEADER_ENDINGS), 'if you have one header input, we assume you want to precompile headers, and cannot have source files or other inputs as well: ' + str(headers) + ' : ' + header
AssertionError: if you have one header input, we assume you want to precompile headers, and cannot have source files or other inputs as well: ['main.cpp', 'E:\\programming\\visual_studio_2017\\Projects\\programming_principles_practice_using_c++/cust_std_lib_facilities.h'] : main.cpp
```
How to fix this error?

**Comment by DragonOsman** [comment]
Okay, just in case, I'll close this issue since the problem I'd opened is already solved, and open a new issue for the problem I have now.
