### ISSUE TITLE
Internal compiler error in src/compiler.js! compilation quakeJS

### ISSUE THREAD

**Issue by khmmarket** [kripken/emscripten#7730]
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/kripken/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "TypeError: Runtime.generateStructInfo is not a function" | TypeError: Runtime.generateStructInfo is not a function
    at eval (eval at load (eval at globalEval (/home/alex/emsdk/emscripten/1.38.21/src/compiler.js:110:8)), <anonymous>:54:25)
    at Object.load (eval at globalEval (/home/alex/emsdk/emscripten/1.38.21/src/compiler.js:110:8), <anonymous>:184:9)
    at JSify (eval at globalEval (/home/alex/emsdk/emscripten/1.38.21/src/compiler.js:110:8), <anonymous>:92:20)
    at Object.<anonymous> (/home/alex/emsdk/emscripten/1.38.21/src/compiler.js:226:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
shared:ERROR: '/home/alex/emsdk/node/8.9.1_64bit/bin/node /home/alex/emsdk/emscripten/1.38.21/src/compiler.js /tmp/tmp6VoALa.txt /home/alex/emsdk/emscripten/1.38.21/tests/quakejs-master/ioq3/code/sys/sys_common.js /home/alex/emsdk/emscripten/1.38.21/tests/quakejs-master/ioq3/code/sys/sys_node.js /home/alex/emsdk/emscripten/1.38.21/tests/quakejs-master/ioq3/code/qcommon/vm_js.js /home/alex/emsdk/emscripten/1.38.21/src/library_pthread_stub.js' failed (1)
Makefile:2260: recipe for target 'build/release-js-js/ioq3ded.js' failed

**Comment by kripken** [comment]
I think that project depends on a very old version of emscripten where `Runtime.generateStructInfo` still exists. You should either use that old version, or upgrade the project to modern emscripten.
