### ISSUE TITLE
Compiler assertion failed

### ISSUE THREAD

**Issue by waywardmonkeys** [kripken/emscripten#928]
I am unable to build the code located at https://gist.github.com/waywardmonkeys/5097296

I get this set of errors using current incoming (earlier versions resulted in stack ``RangeError`` problems):

````
$ em++ -std=c++11 -g -O2 -s DISABLE_EXCEPTION_CATCHING=0 -I test/support put_double.pass.cpp 

undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: OutputBuffer + Indenter::CurrIndent*2 - OutputBufferRoot < OutputBufferSize, at: relooper/Relooper.cpp,37,void PrintIndented(const char *, ...) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL13PrintIndentedPKcz (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZN5Block6RenderEb (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))


undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: OutputBuffer + Indenter::CurrIndent*2 - OutputBufferRoot < OutputBufferSize, at: relooper/Relooper.cpp,50,void PutIndented(const char *) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL11PutIndentedPKc (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZN5Block6RenderEb (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: written < left, at: relooper/Relooper.cpp,43,void PrintIndented(const char *, ...) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL13PrintIndentedPKcz (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))

undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: OutputBuffer + Indenter::CurrIndent*2 - OutputBufferRoot < OutputBufferSize, at: relooper/Relooper.cpp,37,void PrintIndented(const char *, ...) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL13PrintIndentedPKcz (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))

undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: OutputBuffer + Indenter::CurrIndent*2 - OutputBufferRoot < OutputBufferSize, at: relooper/Relooper.cpp,50,void PutIndented(const char *) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL11PutIndentedPKc (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZN5Block6RenderEb (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
Warning: .ll contains floating-point values with more than 64 bits. Faking values for them. If they are used, this will almost certainly break horribly!

undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: OutputBuffer + Indenter::CurrIndent*2 - OutputBufferRoot < OutputBufferSize, at: relooper/Relooper.cpp,50,void PutIndented(const char *) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL11PutIndentedPKc (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZN5Block6RenderEb (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))

undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: needed < left, at: relooper/Relooper.cpp,54,void PutIndented(const char *) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL11PutIndentedPKc (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZN5Block6RenderEb (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))

undefined:1238
line, func ? Pointer_stringify(func) : 'unknown function'] + ' at ' + new Erro
                                                                    ^
Assertion failed: OutputBuffer + Indenter::CurrIndent*2 - OutputBufferRoot < OutputBufferSize, at: relooper/Relooper.cpp,50,void PutIndented(const char *) at Error
    at ___assert_func (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZL11PutIndentedPKc (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at __ZN5Block6RenderEb (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN13MultipleShape6RenderEb [as 16] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
    at Array.__ZN11SimpleShape6RenderEb [as 20] (eval at globalEval (/Users/bruce/Development/temp.emscripten/src/compiler.js:105:8))
Traceback (most recent call last):
  File "/Users/bruce/Development/temp.emscripten/emscripten.py", line 691, in <module>
    _main(environ=os.environ)
  File "/Users/bruce/Development/temp.emscripten/emscripten.py", line 679, in _main
    temp_files.run_and_clean(lambda: main(
  File "/Users/bruce/Development/temp.emscripten/tools/tempfiles.py", line 38, in run_and_clean
    return func()
  File "/Users/bruce/Development/temp.emscripten/emscripten.py", line 687, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/Users/bruce/Development/temp.emscripten/emscripten.py", line 577, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/Users/bruce/Development/temp.emscripten/emscripten.py", line 241, in emscript
    assert len(output) == 2, 'Did not receive forwarded data in an output - process failed? We only got: ' + output[0][-300:]
AssertionError: Did not receive forwarded data in an output - process failed? We only got: 
Traceback (most recent call last):
  File "/Users/bruce/Development/temp.emscripten/emcc", line 1240, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/Users/bruce/Development/temp.emscripten/tools/shared.py", line 947, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js:
````

**Comment by waywardmonkeys** [comment]
These are no longer an issue.
